### PR TITLE
Fixes and code improvements

### PR DESCRIPTION
**Pull request by Martinski4GitHub**
- Fixed a couple of "variable not set" errors.
- Fixed a function not having proper return codes.
- Fine-tuning and code improvements.

### CODE REVIEW

**Comment by Martinski4GitHub** [comment]
@ExtremeFiretop,

Please review & run testing & verification for this PR whenever you have the time. I've tested & validated as much as I could, but a 2nd pair of eyes never hurts, of course. :>)

**Comment by ExtremeFiretop** [comment]
> * Fixed a couple of "variable not set" errors.

Can you point this out?
Lots of small changes that drown out the important one lol!

**Comment by Martinski4GitHub** [comment]
> > * Fixed a couple of "variable not set" errors.
> 
> Can you point this out for me? Lots of small changes that drown out the important one lol!
>
I was about to go to bed when I saw your message, LOL!!
I'll add comments to the respective lines on your PR #275 (easier to point them out).

**Review by ExtremeFiretop — APPROVED** [review]

**Comment by ExtremeFiretop** [comment]
All great catches Martinski! Especially the unset variable!
All the other improvements are much appreciated as well! :)

**Comment by ExtremeFiretop** [comment]
> (easier to point them out).

So you feel my struggle? 🤣
All tested well so far!

**Comment by ExtremeFiretop** [comment]
Synced with Gnuton is commit: https://github.com/ExtremeFiretop/MerlinAutoUpdate-Router/pull/186/commits/1b018f140f828f42064610e07213a41e4a872833

**Pull request merged**
