### PR TITLE
Dev 1.1.0 (AiMesh Beta) as next Release

### PR DESCRIPTION
**Pull request by ExtremeFiretop**
MerlinAU Version 1.1.0 released.

What's Changed/Fixed?:

PR: [#179 ](https://github.com/ExtremeFiretop/MerlinAutoUpdate-Router/pull/179)
Include AiMesh Node Versions. Long discussed, long asked. I broke some brain cells over this one. 
No, it does not flash the nodes from the primary, it does however check any AiMesh nodes for updates and sends a summary email for any updates available.. **You still need MerlinAU for each node you wish to auto-update.**  
Meaning you can disable email notifications on each node, and only get one email from the primary instead of one per node.
AiMesh Nodes menu will be disabled on anything but the primary router.

PR: [#183 ](https://github.com/ExtremeFiretop/MerlinAutoUpdate-Router/pull/173)
Improvements for better estimation of "Available RAM", we identified the current method was too conservative, we now have an improved estimation. (Thanks [@Martinski4GitHub](https://github.com/Martinski4GitHub))!

PR:[#184 ](https://github.com/ExtremeFiretop/MerlinAutoUpdate-Router/pull/184)
Fixes & code improvements for new AiMesh Nodes feature (Thanks [@Martinski4GitHub](https://github.com/Martinski4GitHub))!

PR:[#187 ](https://github.com/ExtremeFiretop/MerlinAutoUpdate-Router/pull/187)
Code improvements to minimize the number of NVRAM calls (Thanks [@Martinski4GitHub](https://github.com/Martinski4GitHub))!

Tightening up some code & general code improvements with PRs in-between.
As always, we highly recommend you update whenever possible. Enjoy the new release! :)

### CODE REVIEW

**Comment by ExtremeFiretop** [comment]
@Martinski4GitHub 

Your good to go when ever, as per the last release, we are confirming nothing is blocked (Once you approve!)
Once you approve this, and nothing is confirmed blocked, we still need to validate the release and tagging works as expected.

**Comment by ExtremeFiretop** [comment]
@Martinski4GitHub 

Updated the forum post to reflect your modification :)

**Comment by Martinski4GitHub** [comment]
> MerlinAU Version 1.1.0 released.
> 
> What's Changed/Fixed?:
>....
> 
> PR: [#183 ](https://github.com/ExtremeFiretop/MerlinAutoUpdate-Router/pull/173) Improvements for better estimation of "Available RAM", we identified the current method was too conservative, we now have an improved estimation. (Thanks [@Martinski4GitHub](https://github.com/Martinski4GitHub))!
> 
I modified the description above. Accuracy refers to the measurement of the actual value. What we have is an improved estimation of the amount of "Available RAM." I know it seems pedantic but in engineering the words "accuracy" & "precision" have clear & exact meanings that are more limited than when used in everyday conversation.

**Review by Martinski4GitHub — APPROVED** [review]
Good to go live!

**Comment by ExtremeFiretop** [comment]
@Martinski4GitHub 

YAHOOOO!! NOW we are cookin with fire!
Wheres the BBQ grill I need a steak on this heat.

Seems like once you approved it instantly pushed using the auto-merge this time!
ANND we got our release and tag as expected.

Plus between the last PR for Gnuton and learning how to "update" the branches I think we are over the learning curves now.

**Comment by Martinski4GitHub** [comment]
> @Martinski4GitHub
> 
> YAHOOOO!! NOW we are cookin with fire! Wheres the BBQ grill I need a steak on this heat.
>
Or, as my Father would say: "NOW, we're really cooking with gas!!"

> 
> Seems like once you approved it instantly pushed using the auto-merge this time! ANND we got our release and tag as expected.
> 
Yeah, once approved, it just did everything else automatically. Excellent job on that automation front, Bud!!
Releasing new version updates will be a breeze from now on.  :>) :>)

**Comment by ExtremeFiretop** [comment]
> > @Martinski4GitHub
> > YAHOOOO!! NOW we are cookin with fire! Wheres the BBQ grill I need a steak on this heat.
> 
> Or, as my Father would say: "NOW, we're really cooking with gas!!"
> 
> > Seems like once you approved it instantly pushed using the auto-merge this time! ANND we got our release and tag as expected.
> 
> Yeah, once approved, it just did everything else automatically. Excellent job on that automation front, Bud!! Releasing new version updates will be a breeze from now on. :>) :>)

Thanks buddy!
That was the idea, the less manual process the better, easier on us!

**Pull request merged**
