### PR TITLE
Offline Version Regex

### PR DESCRIPTION
**Pull request by ExtremeFiretop**
Changes made to the regex of the offline version detection to be more in line with what MerlinAU expects.

### CODE REVIEW

**Comment by ExtremeFiretop** [comment]
Problem was identified when flashing the latest offline beta; it still detected it as failed when it wasn't post flash as per the below email:

image
image

The reason is the format versions don't match, post install it's looking for version: **3006.102.2.0_beta1** but pre-flash it automatically detected the zip file as: **3006.102.2.beta1**

This difference in formatting is what is causing the post-flash email to say it failed when it didn't.
To resolve the issue, I changed the wording, and regex around the input version when validated.

**Comment by ExtremeFiretop** [comment]
This was production version of the regex:

image
image


Both of these are wrong.
With this new correction above in this PR this is the result:

image
image

**Comment by Martinski4GitHub** [comment]
> This was production version of the regex:
> ...
> 
> Both of these are wrong. With this new correction above in this PR this is the result:
> ...
>
Based on your screenshots & your testing results, your changes are working well. At the moment, I have no way to test this myself with an actual Alpha or Beta release (none available for my router). I reviewed the changes and they all look good to me. If you're completely happy with your latest results at this point, I'd say let's merge them.

**Comment by ExtremeFiretop** [comment]
> > This was production version of the regex:
> > ...
> > Both of these are wrong. With this new correction above in this PR this is the result:
> > ...
> 
> Based on your screenshots & your testing results, your changes are working well. At the moment, I have no way to test this myself with an actual Alpha or Beta release (none available for my router). I reviewed the changes and they all look good to me. If you're completely happy with your latest results at this point, I'd say let's merge them.

No worries! I also tried the old format with this these changes and it correctly tags them as incorrectly formatted.

So I'm pretty happy with this, seems to work correctly :) should be better than production

**Review by Martinski4GitHub — APPROVED** [review]
Good to go!

**Comment by Martinski4GitHub** [comment]
@ExtremeFiretop,

BTW, I'm slowly starting to think more seriously about looking for a replacement for my current ASUS router within the next 2 to 3 months, so I'm still not in a rush. My AC-class router is still working fine without any issues so far, and it does meet my current needs, but the lack of F/W updates starting next year is not a good place to be. A friend of mine recommended taking a look at the **Firewalla** brand, particularly the **Firewalla Purple** model which, based on the specs, looks good and should meet my home network needs.

https://firewalla.com/products/firewalla-purple

Do you happen to have any friends or relatives who have it and can provide some technical assessment based on their experience with it?

I know of only one person who has one, but it's the **Firewall Purple SE** so not quite the same. So far, he's happy with it but he's not a computer-savvy person so cannot provide more technical details that I'm looking for.

Anyway, just FYI, in case you know someone.

**Comment by ExtremeFiretop** [comment]
> @ExtremeFiretop,
> 
> BTW, I'm slowly starting to think more seriously about looking for a replacement for my current ASUS router within the next 2 to 3 months, so I'm still not in a rush. My AC-class router is still working fine without any issues so far, and it does meet my current needs, but the lack of F/W updates starting next year is not a good place to be. A friend of mine recommended taking a look at the **Firewalla** brand, particularly the **Firewalla Purple** model which, based on the specs, looks good and should meet my home network needs.
> 
> https://firewalla.com/products/firewalla-purple
> 
> Do you happen to have any friends or relatives who have it and can provide some technical assessment based on their experience with it?
> 
> I know of only one person who has one, but it's the **Firewall Purple SE** so not quite the same. So far, he's happy with it but he's not a computer-savvy person so cannot provide more technical details that I'm looking for.
> 
> Anyway, just FYI, in case you know someone.

It's so cute!!! 🥺 

I would need to ask around the office, I already know off the top of my head 2 of my techy friends have Ubitiqui and 2 of my friends also have ASUS routers.

I don't know anyone off the top of my head that uses this but I'll be sure to poke around haha!

I understand the concern of being near end of life with your AC class router, it's probably time to research some good options.

Can I ask what type of requirements your looking for? Any reason you aren't looking at Ubitiqui or ASUS?

**Comment by ExtremeFiretop** [comment]
Typo correction, my phone has no idea what "Ubiquiti" meant lol

**Comment by Martinski4GitHub** [comment]
> > @ExtremeFiretop,
> > BTW, I'm slowly starting to think more seriously about looking for a replacement for my current ASUS router within the next 2 to 3 months, so I'm still not in a rush. My AC-class router is still working fine without any issues so far, and it does meet my current needs, but the lack of F/W updates starting next year is not a good place to be. A friend of mine recommended taking a look at the **Firewalla** brand, particularly the **Firewalla Purple** model which, based on the specs, looks good and should meet my home network needs.
> > https://firewalla.com/products/firewalla-purple
> > Do you happen to have any friends or relatives who have it and can provide some technical assessment based on their experience with it?
> > I know of only one person who has one, but it's the **Firewall Purple SE** so not quite the same. So far, he's happy with it but he's not a computer-savvy person so cannot provide more technical details that I'm looking for.
> > Anyway, just FYI, in case you know someone.
> 
> It's so cute!!! 🥺
> 
> I would need to ask around the office, I already know off the top of my head 2 of my techy friends have Ubitiqui and 2 of my friends also have ASUS routers.
> 
> I don't know anyone off the top of my head that uses this but I'll be sure to poke around haha!
> 
> I understand the concern of being near end of life with your AC class router, it's probably time to research some good options.
> 
> Can I ask what type of requirements your looking for? Any reason you aren't looking at Ubitiqui or ASUS?
>
>
I'm just researching options at this point, including ASUS but, IMO, the prices of their latest BE-class routers cannot be justified given how immature & inconsistent their 3006 F/W still is (based on RMerlin's assessment from a recent post). I'm looking at Ubiquity as well and a friend of mine has one, so I'm going to meet with him and ask for more technical details.

WRT requirements, I'm looking for an AX-class router (minimum) that meets or exceeds the H/W specs of something like the RT-AX86U PRO, WRT RAM & CPU. Small footprint preferred. Maximum price ~$500 USD & must allow adding custom scripting & tools (like Entware) to customize services. Must have OpenVPN & Wireguard, and any other extras are welcome (e.g. SPI, DPI, etc.). That's the general wish list, but more may come as I do more research.

I'm not expecting to make a final decision until perhaps January 2025, unless I find a really good promotion during the Christmas season that would be hard to pass up for the "right" device.

Anyway, as mentioned, I'm not yet in a rush, so don't worry about getting info right away. Take your time; I'm sure taking my time as well.

Thanks, bud.

**Comment by Martinski4GitHub** [comment]
> Typo correction, my phone has no idea what "Ubiquiti" meant lol
>
>
I know what you mean!! I really hate it when my "smart device" thinks it's a better speller than I am and makes "corrections" as I type. 😠🤨 Arghh!!

**Comment by ExtremeFiretop** [comment]
> I'm just researching options at this point, including ASUS but, IMO, the prices of their latest BE-class routers cannot be justified given how immature & inconsistent their 3006 F/W still is (based on RMerlin's assessment from a recent post). I'm looking at Ubiquiti as well and a friend of mine has one, so I'm going to meet with him and ask for more technical details.

I hear you on that one! It's a nice router but hard to imagine I spent as much money as I did on it. And I'm not sure if it's because of WiFi 7 but my 6GHz range on the new router is much much worse than the 6GHz of my older AXE11000. Not sure why

**Pull request merged**
