### PR TITLE
Fixes to get list of F/W file SHA256 signatures.

### PR DESCRIPTION
**Pull request by Martinski4GitHub**
- Fixed a bug in the original command expression where the very first SHA256 signature was removed.
- Modified command to make it a bit less dependent on possible future HTML formatting changes.

### CODE REVIEW

**Comment by Martinski4GitHub** [comment]
@ExtremeFiretop,

Apologies for the delay. While testing my PR changes, I found a bug that was in the original command expression which was removing the very first SHA256 signature line.

I've tested this PR thoroughly, but please review and verify as you always do (you're my "2nd pair of eyes" :>)

**Comment by ExtremeFiretop** [comment]
> * Fixed a bug in the original command expression where the very first SHA256 signature was removed.

Ah! And this is why your my second set of eyes! Great catch! Happy I listened to my gut and didn't make my rush choices at this critical step.

Will test and advise shortly!

**Review by ExtremeFiretop — APPROVED** [review]

**Comment by ExtremeFiretop** [comment]
image

Went through the list and confirmed this has resolved the bug you described.
Merged!

image

**Comment by ExtremeFiretop** [comment]
@Martinski4GitHub 

Anything else of interest for tonight or should we send it off?

**Comment by Martinski4GitHub** [comment]
> @Martinski4GitHub
> 
> Anything else of interest for tonight or should we send it off?
>
I've got nothing else to add tonight. This one is ready to ship!!

**Comment by ExtremeFiretop** [comment]
> > @Martinski4GitHub
> > Anything else of interest for tonight or should we send it off?
> 
> I've got nothing else to add tonight. This one is ready to ship!!

Fantastic!!

I'll package it up tonight and update the forums. Do the regular dance.

After that, I'll go through each of these last few PRs and merge them/sync them with Gnuton. :)

**Comment by ExtremeFiretop** [comment]
Oh! BTW do you use Plex at all?
If so, I'll send you a message in the forums via PM

**Comment by Martinski4GitHub** [comment]
> Oh! BTW do you use Plex at all? If so, I'll send you a message in the forums via PM
>
No, I don't have a Plex Media Server or an account. We simply use regular streaming services like Netflix, Amazon Prime Video, and Apple TV+.

**Comment by ExtremeFiretop** [comment]
> > Oh! BTW do you use Plex at all? If so, I'll send you a message in the forums via PM
> 
> No, I don't have a Plex Media Server or an account. We simply use regular streaming services like Netflix, Amazon Prime Video, and Apple TV+.

No worries, I figured as a way to say thanks for all your assist throughout the last (almost year now) I'd offer to provide your account access to my media server with some 1000+ 4K movies, etc 😉

Offer is on the table if your ever interested in creating an account 😁 

No pressure though, I mostly use Plex and Netflix and a bit of YouTube Premium.

**Comment by ExtremeFiretop** [comment]
Oh I do also have Amazon Prime, but don't use the prime video

**Comment by Martinski4GitHub** [comment]
> > > Oh! BTW do you use Plex at all? If so, I'll send you a message in the forums via PM
> > 
> > 
> > No, I don't have a Plex Media Server or an account. We simply use regular streaming services like Netflix, Amazon Prime Video, and Apple TV+.
> 
> No worries, I figured as a way to say thanks for all your assist throughout the last (almost year now) I'd offer to provide your account access to my media server with some 1000+ 4K movies, etc 😉
> 
> Offer is on the table if your ever interested in creating an account 😁
> 
Thank you. I fully appreciate the offer. I mentioned this to my wife and after her reaction: "Awww, that's nice of him!!" Her first question was: "Which movies does he have available?"

You see, we really like watching movies in the evenings and on weekends, whenever we have the time.
We mostly like to watch a mix of rom-coms, comedies, action thrillers, sci-fi, and some independent, foreign films.
Perhaps, at some point, I might take you up on your offer. Especially now that the summer has started, and we tend to spend most evenings cooling with the AC at home. I'll let you know, but this has now piqued my wife's curiosity :>).

**Comment by ExtremeFiretop** [comment]
> You see, we really like watching movies in the evenings and on weekends, whenever we have the time. We mostly like to watch a mix of rom-coms, comedies, action thrillers, sci-fi, and some independent, foreign films. Perhaps, at some point, I might take you up on your offer. Especially now that the summer has started, and we tend to spend most evenings cooling with the AC at home. I'll let you know, but this has now piqued my wife's curiosity :>).

I noticed you and your wife enjoy the movies a lot so I figured it may be worth it for you. Think on it, no pressure.
I just figured you could benefit, and while I can't take you out for a drink or a steak, I can offer this :) I share it with close friends and family, currently have 4 people streaming some TV and movies.

> Thank you. I fully appreciate the offer. I mentioned this to my wife and after her reaction: "Awww, that's nice of him!!" Her first question was: "Which movies does he have available?"
> 

Not sure if you ever checked my link on my Github profile, but Plexrequest.ca is the domain I own.
Lets say, if a movie isn't available... Clicking a single button on that webpage will automatically make it available on my server within about 30 minutes (I could be dead or alive, completely automated)

image

image

Access to this is also automated on a daily import of any user that has access to my media server.

**Comment by Martinski4GitHub** [comment]
> > You see, we really like watching movies in the evenings and on weekends, whenever we have the time. We mostly like to watch a mix of rom-coms, comedies, action thrillers, sci-fi, and some independent, foreign films. Perhaps, at some point, I might take you up on your offer. Especially now that the summer has started, and we tend to spend most evenings cooling with the AC at home. I'll let you know, but this has now piqued my wife's curiosity :>).
> 
> I noticed you and your wife enjoy the movies a lot so I figured it may be worth it for you. Think on it, no pressure. I just figured you could benefit, and while I can't take you out for a drink or a steak, I can offer this :) I share it with close friends and family, currently have 4 people streaming some TV and movies.
> 
> > Thank you. I fully appreciate the offer. I mentioned this to my wife and after her reaction: "Awww, that's nice of him!!" Her first question was: "Which movies does he have available?"
> 
> Not sure if you ever checked my link on my Github profile, but Plexrequest.ca is the domain I own. Lets say, if a movie isn't available... Clicking a single button on that webpage will automatically make it available on my server within about 30 minutes (I could be dead or alive, completely automated)
> ...
> Access to this is also automated on a daily import of any user that has access to my media server.
>
Nice setup!!! Let me talk it over with my wife. I know she'd like to see what's available; OTOH, we would not want to take advantage of your generosity by "watching too many movies" or "watching too often." IOW, we would not want to get to a point where you feel like "we're overstaying our welcome." Knowing my wife, she would feel terrible about that.

So to avoid any misunderstandings, let us know what the "terms of usage" would be on a given week or month. For example, you could say: "You can watch 4 movies per week, but no more than 2 movies per day."

Once we have the terms spelled out and the agreement is crystal clear between us, my wife & I can feel more comfortable knowing that we are not taking advantage of the situation.

I hope this is clear.

**Comment by ExtremeFiretop** [comment]
> > > You see, we really like watching movies in the evenings and on weekends, whenever we have the time. We mostly like to watch a mix of rom-coms, comedies, action thrillers, sci-fi, and some independent, foreign films. Perhaps, at some point, I might take you up on your offer. Especially now that the summer has started, and we tend to spend most evenings cooling with the AC at home. I'll let you know, but this has now piqued my wife's curiosity :>).
> > 
> > 
> > I noticed you and your wife enjoy the movies a lot so I figured it may be worth it for you. Think on it, no pressure. I just figured you could benefit, and while I can't take you out for a drink or a steak, I can offer this :) I share it with close friends and family, currently have 4 people streaming some TV and movies.
> > > Thank you. I fully appreciate the offer. I mentioned this to my wife and after her reaction: "Awww, that's nice of him!!" Her first question was: "Which movies does he have available?"
> > 
> > 
> > Not sure if you ever checked my link on my Github profile, but Plexrequest.ca is the domain I own. Lets say, if a movie isn't available... Clicking a single button on that webpage will automatically make it available on my server within about 30 minutes (I could be dead or alive, completely automated)
> > ...
> > Access to this is also automated on a daily import of any user that has access to my media server.
> 
> Nice setup!!! Let me talk it over with my wife. I know she'd like to see what's available; OTOH, we would not want to take advantage of your generosity by "watching too many movies" or "watching too often." IOW, we would not want to get to a point where you feel like "we're overstaying our welcome." Knowing my wife, she would feel terrible about that.
> 
> So to avoid any misunderstandings, let us know what the "terms of usage" would be on a given week or month. For example, you could say: "You can watch 4 movies per week, but no more than 2 movies per day."
> 
> Once we have the terms spelled out and the agreement is crystal clear between us, my wife & I can feel more comfortable knowing that we are not taking advantage of the situation.
> 
> I hope this is clear.

Oh haha! I don't offer this as a paid or official service. It's hosted on my personal setup, I have no terms of usage, if I like you - you get an offer ;)

I have a co-worker that literally steams all day everyday (some TV show called suits.) Has like 12 seasons of it or something lol.
I don't care or mind at all, bandwidth is unlimited and I have lots of speed and power to handle multiple continuous 4K streams at once on the home network and server without feeling a hitch.

The only "term" is that if you request TV shows, make it 1 season at a time, the UI has an "all seasons button" but for some shows like forensic files or something with 30+ seasons, that means my server is downloading for the next 2 or 3 days and using LOTS of storage. And while it is setup to clean up unused files, it won't do it that quickly haha!

The only thing which is nice for me, but not a requirement, is that if you can try to keep the content at "original" quality when streaming if possible. It helps on my side, since the server won't need to live transcode the content down, it can just send the file straight to your TV Plex app, or Phone Plex app, Computer browser, whatever method you decide to stream too.

**Comment by ExtremeFiretop** [comment]
> The only thing which is nice for me, but not a requirement, is that if you can try to keep the content at "original" quality when streaming if possible. It helps on my side, since the server won't need to live transcode the content down, it can just send the file straight to your TV Plex app, or Phone Plex app, Computer browser, whatever method you decide to stream too.

I say it's nice because it reduces hardware load and I can then support "EVEN MORE STREAMS!", haha
So 4K content, on 4K TV is great. it's actually less load on my hardware to stream 4K content straight to you than you turning the quality down to 1080.

In the case of my parents for example, they have an old 1080p plasma with a smart roku dongle, so whenever they stream, my server has to transcode down from 4K --> to 1080p live over the air. That is extra load, again not really a big deal, but if everyone is doing that at once you might start to notice lol.

**Comment by Martinski4GitHub** [comment]
> > > > You see, we really like watching movies in the evenings and on weekends, whenever we have the time. We mostly like to watch a mix of rom-coms, comedies, action thrillers, sci-fi, and some independent, foreign films. Perhaps, at some point, I might take you up on your offer. Especially now that the summer has started, and we tend to spend most evenings cooling with the AC at home. I'll let you know, but this has now piqued my wife's curiosity :>).
> > > 
> > > 
> > > I noticed you and your wife enjoy the movies a lot so I figured it may be worth it for you. Think on it, no pressure. I just figured you could benefit, and while I can't take you out for a drink or a steak, I can offer this :) I share it with close friends and family, currently have 4 people streaming some TV and movies.
> > > > Thank you. I fully appreciate the offer. I mentioned this to my wife and after her reaction: "Awww, that's nice of him!!" Her first question was: "Which movies does he have available?"
> > > 
> > > 
> > > Not sure if you ever checked my link on my Github profile, but Plexrequest.ca is the domain I own. Lets say, if a movie isn't available... Clicking a single button on that webpage will automatically make it available on my server within about 30 minutes (I could be dead or alive, completely automated)
> > > ...
> > > Access to this is also automated on a daily import of any user that has access to my media server.
> > 
> > 
> > Nice setup!!! Let me talk it over with my wife. I know she'd like to see what's available; OTOH, we would not want to take advantage of your generosity by "watching too many movies" or "watching too often." IOW, we would not want to get to a point where you feel like "we're overstaying our welcome." Knowing my wife, she would feel terrible about that.
> > So to avoid any misunderstandings, let us know what the "terms of usage" would be on a given week or month. For example, you could say: "You can watch 4 movies per week, but no more than 2 movies per day."
> > Once we have the terms spelled out and the agreement is crystal clear between us, my wife & I can feel more comfortable knowing that we are not taking advantage of the situation.
> > I hope this is clear.
> 
> Oh haha! I don't offer this as a paid or official service. It's hosted on my personal setup, I have no terms of usage, if I like you - you get an offer ;)
> 
> I have a co-worker that literally steams all day everyday (some TV show called suits.) Has like 12 seasons of it or something lol. I don't care or mind at all, bandwidth is unlimited and I have lots of speed and power to handle multiple continuous 4K streams at once on the home network and server without feeling a hitch.
> 
> The only "term" is that if you request TV shows, make it 1 season at a time, the UI has an "all seasons button" but for some shows like forensic files or something with 30+ seasons, that means my server is downloading for the next 2 or 3 days and using LOTS of storage. And while it is setup to clean up unused files, it won't do it that quickly haha!
>
It's extremely rare for us to watch TV shows - there are exceptions (e.g. "Breaking Bad" was one of those rare gems). I'd say about 95% of the time is movies or short series (e.g. "The Haunting of Hill House"). But it's good to know the limitation of "1 season at a time."

> 
> The only thing which is nice for me, but not a requirement, is that if you can try to keep the content at "original" quality when streaming if possible. It helps on my side, since the server won't need to live transcode the content down, it can just send the file straight to your TV Plex app, or Phone Plex app, Computer browser, whatever method you decide to stream too.
>
The TV in our living room is 4K, but the TV in our master bedroom (where we watch most of the time) is only 1080p. So there might be an issue there if the original movie is 4K. Sometimes, my wife likes to watch a movie on her laptop as well. 

Anyway, all this is good info to know in advance. Thanks for the clarifications.
I'll let you know when we decide to take you up on the offer.

Thanks again.

**Comment by ExtremeFiretop** [comment]
> The TV in our living room is 4K, but the TV in our master bedroom (where we watch most of the time) is only 1080p. So there might be an issue there if the original movie is 4K. Sometimes, my wife likes to watch a movie on her laptop as well.
> 
> Anyway, all this is good info to know in advance. Thanks for the clarifications. I'll let you know when we decide to take you up on the offer.
> 
> Thanks again.

Again it's not the end of the world, it adds an extra layer of complexity since it needs to transcode the content to a format supported by the TV player. But honestly not the end of the world, my parents have a TV the same way and I barely notice a spike at all. I might notice a tiny spike (for once)! if you and them and one other person are all transcoding.

The chances of that are probably low on its face considering the time zone difference, and if you want to try it out and see how it runs I can confirm after a few streams how much usage is seen on the server. It's probably gonna be negligible. The server runs a 1000 5950x and a RTX 3070 specifically for transcoding lol. When I say it barely sees anything I mean it.

**Comment by ExtremeFiretop** [comment]
Synced with Gnuton in commit: https://github.com/ExtremeFiretop/MerlinAutoUpdate-Router/pull/186/commits/af2571e1c17021c70514f13b98cac1aae0cc00c2

**Comment by ExtremeFiretop** [comment]
> Nice setup!!! Let me talk it over with my wife. I know she'd like to see what's available; OTOH, we would not want to take advantage of your generosity by "watching too many movies" or "watching too often." IOW, we would not want to get to a point where you feel like "we're overstaying our welcome." Knowing my wife, she would feel terrible about that.
> 

I figured instead of making you make an account to check content available, I exported a full list and send it on SNB ;)
Hopefully that helps review some available content ;)

**Comment by ExtremeFiretop** [comment]
I thought your idea of outlining the ideal "agreement" was a smart idea, so I did that exactly that:

image

**Comment by ExtremeFiretop** [comment]
Meh, sadface.
I had to remove it for now, the formatting was broken on mobile devices. :/

**Comment by Martinski4GitHub** [comment]
> I thought your idea of outlining the ideal "agreement" was a smart idea, so I did that exactly that:
> 
That was a nice touch. I like it!!!

**Comment by Martinski4GitHub** [comment]
> Meh, sadface. I had to remove it for now, the formatting was broken on mobile devices. :/
>
I hate it when that happens! :<(

**Comment by ExtremeFiretop** [comment]
> > Meh, sadface. I had to remove it for now, the formatting was broken on mobile devices. :/
> 
> I hate it when that happens! :<(

I feel you. I went most of the day without realizing until someone that has access pulled out their phone and ruined it for me trying to request something 😭 

The nerve eh?? 😂 Haha JK. When I have time I'll try to reformat the HTML better for mobiles but it's a pain everytime I deal with this lol!!

**Comment by ExtremeFiretop** [comment]
> > Meh, sadface. I had to remove it for now, the formatting was broken on mobile devices. :/
> 
> I hate it when that happens! :<(

Fixed it!

image

(Random side project I was troubleshooting)

**Comment by ExtremeFiretop** [comment]
https://github.com/Ombi-app/Ombi/pull/5127/files

**Pull request merged**
