### PR TITLE
Dev 1.3.5 as Next Stable Release

### PR DESCRIPTION
**Pull request by ExtremeFiretop**
**1. Forms post update = Done**
**2. Readme update = Done**
**3. Version.txt update = Done**

**Dev 1.3.5 as Next Stable Release**

What's Changed/Fixed?:

PR: [ [#353 ](https://github.com/ExtremeFiretop/MerlinAutoUpdate-Router/pull/353)]
Code Improvements for Post-Reboot Script Calls.
- Increased wait timers in the post-update reboot
- Little fixes around the settings file using dos2unix and chmod 0664
- (Thanks [@Martinski4GitHub](https://github.com/Martinski4GitHub) [@Martinski](https://www.snbforums.com/members/69996/))

PR: [ [#354 ](https://github.com/ExtremeFiretop/MerlinAutoUpdate-Router/pull/354)]
Trace log for update email notifications.
- Added code to add some trace log for the post-reboot update email notifications (for debugging purposes).
- (Thanks [@Martinski4GitHub](https://github.com/Martinski4GitHub) [@Martinski](https://www.snbforums.com/members/69996/))

**BUG FIX:** PR: [ [#355 ](https://github.com/ExtremeFiretop/MerlinAutoUpdate-Router/pull/355)]
Various Small Fixes.
- More Regex fixes around versioning.
- Fixed an issue around emails misidentifying as failed when it was really a success.

**BUG FIX:** PR: [ [#356 ](https://github.com/ExtremeFiretop/MerlinAutoUpdate-Router/pull/356)]
Improvements to Acquiring Lock File.
- Fixes an issue where during the post-update reboot, 2 instances of MerlinAU would be called and the 2nd one encountered the lock file, causing the post-update email notification to not get sent.
- Code improvements when the script is trying to obtain a lock file by allowing a 2nd instance to wait for the 1st instance to perform its job and exit. This now means that 2 or more instances could execute in a staggered pattern and not terminate immediately when a lock file is found.
- (Thanks [@Martinski4GitHub](https://github.com/Martinski4GitHub) [@Martinski](https://www.snbforums.com/members/69996/))

As always, we highly recommend you update ASAP as this includes functional improvements and little bug fixes.
**Tested against the latest 3004.388.8_4 and 3006.102.2_2**

**Significant Screenshots:**

image

### CODE REVIEW

**Comment by ExtremeFiretop** [comment]
@Martinski4GitHub 

All good to go here :)

**Comment by Martinski4GitHub** [comment]
> @Martinski4GitHub
> 
> All good to go here :)
>
Just to be crystal clear. Are you "passing me the baton" now so I can merge?
Just want to avoid stepping on your toes while you're doing your thing... Better safe than sorry.

**Comment by Martinski4GitHub** [comment]
> > > @Martinski4GitHub
> > > All good to go here :)
> > 
> > 
> > Just to be crystal clear. Are you "passing me the baton" now so I can merge? Just want to avoid stepping on your toes while you're doing your thing... Better safe than sorry.
> 
> As long as your around I want your final approval the code and notes look good! Always!
>
Got you!! I'm on it...

**Review by Martinski4GitHub — APPROVED** [review]
Approved. Ready to ship!!

**Comment by Martinski4GitHub** [comment]
> > > @Martinski4GitHub
> > > All good to go here :)
> > 
> > 
> > Just to be crystal clear. Are you "passing me the baton" now so I can merge? Just want to avoid stepping on your toes while you're doing your thing... Better safe than sorry.
> 
> As long as your around I want your final approval the code and notes look good! Always!
>
FYI, made a few wording changes in the release notes.

**Comment by ExtremeFiretop** [comment]
> > > > @Martinski4GitHub
> > > > All good to go here :)
> > > 
> > > 
> > > Just to be crystal clear. Are you "passing me the baton" now so I can merge? Just want to avoid stepping on your toes while you're doing your thing... Better safe than sorry.
> > 
> > 
> > As long as your around I want your final approval the code and notes look good! Always!
> 
> FYI, made a few wording changes in the release notes.

I'm adjusting the forum post now to reflect! :) Thank you buddy! Always a pleasure working with a Genius like yourself ;)

**Comment by Martinski4GitHub** [comment]
> > > > > @Martinski4GitHub
> > > > > All good to go here :)
> > > > 
> > > > 
> > > > Just to be crystal clear. Are you "passing me the baton" now so I can merge? Just want to avoid stepping on your toes while you're doing your thing... Better safe than sorry.
> > > 
> > > 
> > > As long as your around I want your final approval the code and notes look good! Always!
> > 
> > 
> > FYI, made a few wording changes in the release notes.
> 
> I'm adjusting the forum post now to reflect! :) Thank you buddy! Always a pleasure working with a Genius like yourself ;)
>
>
Back at you, buddy. Thanks for keeping me on my toes as well and for the 2nd pair of eyes in troubleshooting and eventually finding a solid solution.

We have a good dynamic going on!! After a year of collaboration, let's hope for another good year.

**Comment by ExtremeFiretop** [comment]
> > > > > > @Martinski4GitHub
> > > > > > All good to go here :)
> > > > > 
> > > > > 
> > > > > Just to be crystal clear. Are you "passing me the baton" now so I can merge? Just want to avoid stepping on your toes while you're doing your thing... Better safe than sorry.
> > > > 
> > > > 
> > > > As long as your around I want your final approval the code and notes look good! Always!
> > > 
> > > 
> > > FYI, made a few wording changes in the release notes.
> > 
> > 
> > I'm adjusting the forum post now to reflect! :) Thank you buddy! Always a pleasure working with a Genius like yourself ;)
> 
> Back at you, buddy. Thanks for keeping me on my toes as well and for the 2nd pair of eyes in troubleshooting and eventually finding a solid solution.
> 
> We have a good dynamic going on!! After a year of collaboration, let's hope for another good year.

I have said it before and I'll say it again, we are a great duo, and even Tom mentioned it to me via email.

No single person can ever be expected to catch it all. I may not have the in depth knowledge you have, but I like to think I still throw you a curve ball once in a while 😉 

Hahaha! Another year cheers to that!
Goodnight buddy I'm off to count some sheep 🐏

**Comment by Martinski4GitHub** [comment]
> > > > > > > @Martinski4GitHub
> > > > > > > All good to go here :)
> > > > > > 
> > > > > > 
> > > > > > Just to be crystal clear. Are you "passing me the baton" now so I can merge? Just want to avoid stepping on your toes while you're doing your thing... Better safe than sorry.
> > > > > 
> > > > > 
> > > > > As long as your around I want your final approval the code and notes look good! Always!
> > > > 
> > > > 
> > > > FYI, made a few wording changes in the release notes.
> > > 
> > > 
> > > I'm adjusting the forum post now to reflect! :) Thank you buddy! Always a pleasure working with a Genius like yourself ;)
> > 
> > 
> > Back at you, buddy. Thanks for keeping me on my toes as well and for the 2nd pair of eyes in troubleshooting and eventually finding a solid solution.
> > We have a good dynamic going on!! After a year of collaboration, let's hope for another good year.
> 
> I have said it before and I'll say it again, we are a great duo, and even Tom mentioned it to me via email.
> 
> No single person can ever be expected to catch it all. I may not have the in depth knowledge you have, but I like to think I still throw you a curve ball once in a while 😉
> 
>
Indeed, no single person can do it all, or do it well all the time. It's the product of a team effort.
I hope to hit all your curve balls... :>) LOL

>
> Hahaha! Another year cheers to that! Goodnight buddy I'm off to count some sheep 🐏
>
>
Off to Dreamland for me as well. Have a good night, bud.

**Comment by ExtremeFiretop** [comment]
> Indeed, no single person can do it all, or do it well all the time. It's the product of a team effort. I hope to hit all your curve balls... :>) LOL
> 

You always hit them out of the park ;P Home runs everytime!

**Pull request merged**
