### PR TITLE
Fixes & code improvements

### PR DESCRIPTION
**Pull request by Martinski4GitHub**
Found a couple of issues with PR #280.

- Fixed issue with variable "FW_UpdateDate" not being updated at run time when changes were made to the scheduled CRON job or the number of postponed days.

-  Fixed issue with variable "FW_UpdateDate" not being updated before sending the NEW_FW_UPDATE_STATUS email notification.

- Various code improvements & fine-tuning.

### CODE REVIEW

**Comment by ExtremeFiretop** [comment]
I was already aware of this. Thanks!

**Comment by ExtremeFiretop** [comment]
Yeah I was actually actually mostly done all this myself from last night.

I was just waiting until I got out of bed to submit it but I guess I don't need to get out of bed anymore :)

**Comment by Martinski4GitHub** [comment]
> Yeah I was actually mostly done all this myself from last night.
> 
> I was just waiting until I got out of bed to submit it but I guess I don't need to get out of bed anymore :)
>
Well, you're welcome!! Now go back to sleep!! LOL :>).

**Comment by ExtremeFiretop** [comment]
I have the day off today so I will actually 😂
Chat later buddy, enjoy the day

**Comment by Martinski4GitHub** [comment]
> I have the day off today so I will actually 😂 Chat later buddy, enjoy the day
>
Nice!! Then enjoy your sleep and the rest of the day, bud. We'll talk later.
Signing off.

**Comment by ExtremeFiretop** [comment]
> > I have the day off today so I will actually 😂 Chat later buddy, enjoy the day
> 
> Nice!! Then enjoy your sleep and the rest of the day, bud. We'll talk later. Signing off.

We'll chat this afternoon or this evening whenever your available. I have more things to discuss later. You just happened to beat me to the punch on this one ;)

**Comment by ExtremeFiretop** [comment]
Synced with Gnuton in commit: https://github.com/ExtremeFiretop/MerlinAutoUpdate-Router/pull/186/commits/717c904b75d9e0c5ae6dcee7e691b5881bafca22

**Pull request merged**
