### PR TITLE
Removed timeout from wget calls.

### PR DESCRIPTION
**Pull request by Martinski4GitHub**
Removed the "timeout" parameter from `wget` calls to prevent setting connect timeouts or read timeouts.

### CODE REVIEW

**Comment by Martinski4GitHub** [comment]
@ExtremeFiretop,

My early morning F/W update to the latest **3004.386.14.2** version was not successful due to a connection timeout. For some reason, downloading the ZIP file is taking longer than usual today. So I removed the timeout parameter from the wget calls to prevent such timeouts.

**Review by ExtremeFiretop — APPROVED** [review]

**Comment by ExtremeFiretop** [comment]
> @ExtremeFiretop,
> 
> My early morning F/W update to the latest **3004.386.14.2** version was not successful due to a connection timeout. For some reason, downloading the ZIP file is taking longer than usual today. So I removed the timeout parameter from the wget calls to prevent such timeouts.
> 
> Finally, it took almost 7 minutes to download the firmware ZIP file. This usually takes less than a minute. I don't know why. I've checked my broadband download speeds and it's good, although my upload speed is very slow, it should not affect the downloading of the ZIP file. Later today, I'm going to check my upload speed again and will contact my ISP if it continues to be this slow.
> 
> HomeInternetSpeed

Seeing it happen to you, to me (while testing) and this user, something is definitely up.
7 minutes is insane!! Last night when I tested before release it was done in 15 seconds or so!!

**Comment by Martinski4GitHub** [comment]
> > @ExtremeFiretop,
> > My early morning F/W update to the latest **3004.386.14.2** version was not successful due to a connection timeout. For some reason, downloading the ZIP file is taking longer than usual today. So I removed the timeout parameter from the wget calls to prevent such timeouts.
> > Finally, it took almost 7 minutes to download the firmware ZIP file. This usually takes less than a minute. I don't know why. I've checked my broadband download speeds and it's good, although my upload speed is very slow, it should not affect the downloading of the ZIP file. Later today, I'm going to check my upload speed again and will contact my ISP if it continues to be this slow.
>>
> 
> Seeing it happen to you, to me (while testing) and this user, something is definitely up. 7 minutes is insane!! Last night when I tested before release it was done in 15 seconds or so!!
>
>
Yeah, when I have watched the script working before (e.g. during testing & validation), downloading the ZIP file takes only a few seconds (about 10-15), and the entire F/W update process always seems to take less than a minute until the router goes offline and eventually reboots itself. But this morning, I woke up expecting the router to have upgraded itself to the latest F/W version, only to find it with the same version. Puzzled, I executed the script manually and saw the connection during the download eventually timing out, so right away I figured it must be due to some timeout parameter; and if I was seeing that problem, other users would probably see it as well very soon, if not already.

As you mentioned in your SNB Forum post, the problem appears to be with the SourceForge servers which are very slow to transmit data this morning. Something is certainly going on with their servers...

**Comment by ExtremeFiretop** [comment]
> > > @ExtremeFiretop,
> > > My early morning F/W update to the latest **3004.386.14.2** version was not successful due to a connection timeout. For some reason, downloading the ZIP file is taking longer than usual today. So I removed the timeout parameter from the wget calls to prevent such timeouts.
> > > Finally, it took almost 7 minutes to download the firmware ZIP file. This usually takes less than a minute. I don't know why. I've checked my broadband download speeds and it's good, although my upload speed is very slow, it should not affect the downloading of the ZIP file. Later today, I'm going to check my upload speed again and will contact my ISP if it continues to be this slow.
> > 
> > 
> > Seeing it happen to you, to me (while testing) and this user, something is definitely up. 7 minutes is insane!! Last night when I tested before release it was done in 15 seconds or so!!
> 
> Yeah, when I have watched the script working before (e.g. during testing & validation), downloading the ZIP file takes only a few seconds (about 10-15), and the entire F/W update process always seems to take less than a minute until the router goes offline and eventually reboots itself. But this morning, I woke up expecting the router to have upgraded itself to the latest F/W version, only to find it with the same version. Puzzled, I executed the script manually and saw the connection during the download eventually timing out, so right away I figured it must be due to some timeout parameter; and if I was seeing that problem, other users would probably see it as well very soon, if not already.
> 
> As you mentioned in your SNB Forum post, the problem appears to be with the SourceForge servers which are very slow to transmit data this morning. Something is certainly going on with their servers...

Thats exactly my experience as well. 

I can only assume so many people are downloading things the servers are struggling. Or maybe just bad timing with some maintenance with SourceForge while we had a release sent out?

Either way as long as it downloads the speed it does it at doesn't really matter in my eyes. It's usually done overnight and the speed wouldn't be much faster even if you did it yourself manually. (It's still slow).

Any thoughts on Tom's vote on including a Auto update to the script itself via am opt in setting? Are we at a mature enough phase that people will find it annoying to update themselves?

**Comment by Martinski4GitHub** [comment]
> > > > @ExtremeFiretop,
> > > > My early morning F/W update to the latest **3004.386.14.2** version was not successful due to a connection timeout. For some reason, downloading the ZIP file is taking longer than usual today. So I removed the timeout parameter from the wget calls to prevent such timeouts.
> > > > Finally, it took almost 7 minutes to download the firmware ZIP file. This usually takes less than a minute. I don't know why. I've checked my broadband download speeds and it's good, although my upload speed is very slow, it should not affect the downloading of the ZIP file. Later today, I'm going to check my upload speed again and will contact my ISP if it continues to be this slow.
> > > 
> > > 
> > > Seeing it happen to you, to me (while testing) and this user, something is definitely up. 7 minutes is insane!! Last night when I tested before release it was done in 15 seconds or so!!
> > 
> > 
> > Yeah, when I have watched the script working before (e.g. during testing & validation), downloading the ZIP file takes only a few seconds (about 10-15), and the entire F/W update process always seems to take less than a minute until the router goes offline and eventually reboots itself. But this morning, I woke up expecting the router to have upgraded itself to the latest F/W version, only to find it with the same version. Puzzled, I executed the script manually and saw the connection during the download eventually timing out, so right away I figured it must be due to some timeout parameter; and if I was seeing that problem, other users would probably see it as well very soon, if not already.
> > As you mentioned in your SNB Forum post, the problem appears to be with the SourceForge servers which are very slow to transmit data this morning. Something is certainly going on with their servers...
> 
> Thats exactly my experience as well.
> 
> I can only assume so many people are downloading things the servers are struggling. Or maybe just bad timing with some maintenance with SourceForge while we had a release sent out?
> 
> Either way as long as it downloads the speed it does it at doesn't really matter in my eyes. It's usually done overnight and the speed wouldn't be much faster even if you did it yourself manually. (It's still slow).
>
>
Yes, exactly. Most users likely have it scheduled to do the F/W update in the very early hours of the morning so the download speed should not matter as long as it completes successfully.

> 
> Any thoughts on Tom's vote on including a Auto update to the script itself via am opt in setting? Are we at a mature enough phase that people will find it annoying to update themselves?
>
>
I think an "advanced configuration option" where people have to enable it (should be **disabled** by default) would be the right thing to do, IMO. The other caveat is to make sure that the script auto-update cron schedule does **not** coincide with the F/W Update cron schedule. IOW, both cron jobs should be separated by at least 15 minutes to avoid conflicts with one stepping on the other.

**Comment by Martinski4GitHub** [comment]
@ExtremeFiretop.

Going offline now for my day job :>)
Talk to you later. Have a good day, bud.

**Comment by ExtremeFiretop** [comment]
> @ExtremeFiretop.
> 
> Going offline now for my day job :>) Talk to you later. Have a good day, bud.

I'll start poking at the auto update option. Enjoy the day buddy we'll talk soon (clearly) hahaha

**Comment by ExtremeFiretop** [comment]
Also just wanted to say nice catch on also adjusting it for Gnuton; it was one of the things I checked for haha!

**Pull request merged**
