### PR TITLE
Skip Tailscale Shutdown

### PR DESCRIPTION
**Pull request by ExtremeFiretop**
Skip Tailscale Shutdown as per the 2 "requests" below:

image

image

https://www.snbforums.com/threads/merlinau-v1-2-3-the-ultimate-firmware-auto-updater-now-available-in-amtm.88577/post-915243

### CODE REVIEW

**Comment by ExtremeFiretop** [comment]
Synced with Gnuton here:
https://github.com/ExtremeFiretop/MerlinAutoUpdate-Router/pull/186/commits/adff3cc0c5ae7964411674e00febef14fe224888

**Comment by Martinski4GitHub** [comment]
> 
>  Skip Tailscale Shutdown as per the 2 "requests" below:
> 
The idea of skipping a specific VPN service needed for remote access seems reasonable (but more testing is required to fully validate it, IMO). However, your current approach to the implementation is insufficient because you're skipping some of Entware framework used to stop & start services. IOW, the current solution may work for some services but not for others.

I have an idea for a solution that would work still using the Entware framework. Let me work on it.

**Comment by ExtremeFiretop** [comment]
> > Skip Tailscale Shutdown as per the 2 "requests" below:
> 
> The idea of skipping a specific VPN service needed for remote access seems reasonable (but more testing is required to fully validate it, IMO). However, your current approach to the implementation is insufficient because you're skipping some of Entware framework used to stop & start services. IOW, the current solution may work for some services but not for others.
> 
> I have an idea for a solution that would work still using the Entware framework. Let me work on it.

I currently have a discussion in the forums with Viktor and a user to see for testing.

But I'm all open to a better way to handle the Entware framework. Let me know what your thinking.

**Comment by ExtremeFiretop** [comment]
@Martinski4GitHub 

Is this commit better?

https://github.com/ExtremeFiretop/MerlinAutoUpdate-Router/pull/246/commits/623a89abc11f751957826907afc16ca96932dd82

**Comment by Martinski4GitHub** [comment]
> > > Skip Tailscale Shutdown as per the 2 "requests" below:
> > 
> > 
> > The idea of skipping a specific VPN service needed for remote access seems reasonable (but more testing is required to fully validate it, IMO). However, your current approach to the implementation is insufficient because you're skipping some of Entware framework used to stop & start services. IOW, the current solution may work for some services but not for others.
> > I have an idea for a solution that would work still using the Entware framework. Let me work on it.
> 
> I currently have a discussion in the forums with Viktor and a user to see for testing.
> 
> But I'm all open to a better way to handle the Entware framework. Let me know what your thinking.
>
See PR #247. Essentially, the idea is to temporarily rename the service file so that Entware ignores it when called to stop/start services. Once completed, the service file is renamed back to its original name.

**Comment by ExtremeFiretop** [comment]
> > > > Skip Tailscale Shutdown as per the 2 "requests" below:
> > > 
> > > 
> > > The idea of skipping a specific VPN service needed for remote access seems reasonable (but more testing is required to fully validate it, IMO). However, your current approach to the implementation is insufficient because you're skipping some of Entware framework used to stop & start services. IOW, the current solution may work for some services but not for others.
> > > I have an idea for a solution that would work still using the Entware framework. Let me work on it.
> > 
> > 
> > I currently have a discussion in the forums with Viktor and a user to see for testing.
> > But I'm all open to a better way to handle the Entware framework. Let me know what your thinking.
> 
> See PR #247. Essentially, the idea is to temporarily rename the service file so that Entware ignores it when called to stop/start services. Once completed, the service file is renamed back to its original name.

Is renaming the service file going to cause issues to the running service?
Sorry I've never looked into how entware is implemented or really functions.

**Comment by Martinski4GitHub** [comment]
> > > > > Skip Tailscale Shutdown as per the 2 "requests" below:
> > > > 
> > > > 
> > > > The idea of skipping a specific VPN service needed for remote access seems reasonable (but more testing is required to fully validate it, IMO). However, your current approach to the implementation is insufficient because you're skipping some of Entware framework used to stop & start services. IOW, the current solution may work for some services but not for others.
> > > > I have an idea for a solution that would work still using the Entware framework. Let me work on it.
> > > 
> > > 
> > > I currently have a discussion in the forums with Viktor and a user to see for testing.
> > > But I'm all open to a better way to handle the Entware framework. Let me know what your thinking.
> > 
> > 
> > See PR #247. Essentially, the idea is to temporarily rename the service file so that Entware ignores it when called to stop/start services. Once completed, the service file is renamed back to its original name.
> 
> Is renaming the service file going to cause issues to the running service? Sorry I've never looked into how entware is implemented or really functions.
>
If the service is already running, the code has been cached into memory where it resides until it exits or is terminated.

**Comment by ExtremeFiretop** [comment]
@Martinski4GitHub 

Reopened this and updated with the information I have from your PR.

**Comment by ExtremeFiretop** [comment]
Synced up with Gnuton again here: https://github.com/ExtremeFiretop/MerlinAutoUpdate-Router/pull/186/commits/b700ccc2bce89442981f5ab6659333bec05f770f

**Comment by ExtremeFiretop** [comment]
Synced with Gnuton again here with the latest changes: https://github.com/ExtremeFiretop/MerlinAutoUpdate-Router/pull/186/commits/0e6ca6fc591ab8ad92aac057c112260402da9c40

**Comment by ExtremeFiretop** [comment]
@Martinski4GitHub 

Updated this PR with everything from your PR, plus the fix for the user we discovered here: https://imgur.com/a/M1yiluU#46Mqn0X
Plus the options to enable and disable this "feature"

Please review when you get a moment :)

**Review by Martinski4GitHub — APPROVED** [review]
Looking good.

**Comment by Martinski4GitHub** [comment]
> @Martinski4GitHub
> 
> Updated this PR with everything from your PR, plus the fix for the user we discovered here: https://imgur.com/a/M1yiluU#46Mqn0X Plus the options to enable and disable this "feature"
> 
> Please review when you get a moment :)
>
Looks good to go. Just a couple of things that may need some improvement but nothing major.
I can't really test the new option over Tailscale or WireGuard since I don't use them. All my remote connections are via OpenVPN, and I've never had a problem with it. The connection stays up until the router reboots, and then it comes back up after the router has rebooted.

**Pull request merged**
