### PR TITLE
Update Blocked Models (Readme and Script)

### PR DESCRIPTION
**Pull request by ExtremeFiretop**
Update Blocked Models (Readme and Script)

Including the following models to be safe:

RT-AC1900P (Blocked)
RT-AC68UF (Blocked)
RT-AC68P (Blocked)
RT-N16 (Blocked)

### CODE REVIEW

**Comment by ExtremeFiretop** [comment]
Also updated the forums and the Wiki: https://github.com/ExtremeFiretop/MerlinAutoUpdate-Router/wiki

**Comment by Martinski4GitHub** [comment]
> Also updated the forums and the Wiki: https://github.com/ExtremeFiretop/MerlinAutoUpdate-Router/wiki
<
You're right. They needed to be updated given the latest changes & additions made recently.
Good call with the blocked models.

**Review by Martinski4GitHub — APPROVED** [review]
Approved!!

**Comment by ExtremeFiretop** [comment]
> Approved!!

Thank you thank you!

Guess what I had for dinner tonight... Salmon hahahaha, you planted a seed!

**Comment by ExtremeFiretop** [comment]
> > Also updated the forums and the Wiki: https://github.com/ExtremeFiretop/MerlinAutoUpdate-Router/wiki
> 
> You're right. They needed to be updated given the latest changes & additions made recently. Good call with the blocked models.

Merci!

I am pretty sure they would be blocked anyways (except for the RT-N16)

Because they use the firmware of blocked models already on the list, but I'm not actually positive if those variant models report as variants are not so I figured better be safe than sorry.

**Comment by Martinski4GitHub** [comment]
> > Approved!!
> 
> Thank you thank you!
> 
> Guess what I had for dinner tonight... Salmon hahahaha, you planted a seed!
>
Another good call!!! 👍😉
Salmon is also one of the most nutritious fish around, especially if it's the wild-caught variety. A great way to get the essential Omega-3 fatty acids. And it's got a great taste, IMO, whether it's baked, grilled, seared, or poached. Hope you enjoyed it!!

**Comment by ExtremeFiretop** [comment]
> > > Approved!!
> > 
> > 
> > Thank you thank you!
> > Guess what I had for dinner tonight... Salmon hahahaha, you planted a seed!
> 
> Another good call!!! 👍😉 Salmon is also one of the most nutritious fish around, especially if it's the wild-caught variety. A great way to get the essential Omega-3 fatty acids. And it's got a great taste, IMO, whether it's baked, grilled, seared, or poached. Hope you enjoyed it!!

My parents already did it poached, but tonight for simplicity we had it baked in the air fryer, if was delicious, we were doing groceries today and I had the thought that I hadn't had fish in a while.

My father loves fish and especially seafood so when I lived with them it was much more common around the house!

**Comment by Martinski4GitHub** [comment]
> > > Also updated the forums and the Wiki: https://github.com/ExtremeFiretop/MerlinAutoUpdate-Router/wiki
> > 
> > 
> > You're right. They needed to be updated given the latest changes & additions made recently. Good call with the blocked models.
> 
> Merci!
> 
> I am pretty sure they would be blocked anyways (except for the RT-N16)
>
> Because they use the firmware of blocked models already on the list, but I'm not actually positive if those variant models report as variants are not so I figured better be safe than sorry.
>
>
Also, if any of those router models have less than 512MB of RAM they would be blocked as well with the minimum RAM check.
So I think we had it covered, but it's always good to have redundancy checks based on model IDs.

**Comment by ExtremeFiretop** [comment]
> > > > Also updated the forums and the Wiki: https://github.com/ExtremeFiretop/MerlinAutoUpdate-Router/wiki
> > > 
> > > 
> > > You're right. They needed to be updated given the latest changes & additions made recently. Good call with the blocked models.
> > 
> > 
> > Merci!
> > I am pretty sure they would be blocked anyways (except for the RT-N16)
> > Because they use the firmware of blocked models already on the list, but I'm not actually positive if those variant models report as variants are not so I figured better be safe than sorry.
> 
> Also, if any of those router models have less than 512MB of RAM they would be blocked as well with the minimum RAM check. So I think we had it covered, but it's always good to have redundancy checks based on model IDs.

That's true, I didn't think about that but reviewing the code they would be blocked if they were low RAM models. 

I prefer the model IDs though because it makes it obvious on the main menu as soon as you load the script it's not compatible instead of failing due to low memory, but your right we have more safeties than I realize sometimes!

**Comment by Martinski4GitHub** [comment]
> > > > Approved!!
> > > 
> > > 
> > > Thank you thank you!
> > > Guess what I had for dinner tonight... Salmon hahahaha, you planted a seed!
> > 
> > 
> > Another good call!!! 👍😉 Salmon is also one of the most nutritious fish around, especially if it's the wild-caught variety. A great way to get the essential Omega-3 fatty acids. And it's got a great taste, IMO, whether it's baked, grilled, seared, or poached. Hope you enjoyed it!!
> 
> My parents always did it poached, but tonight for simplicity we had it baked in the air fryer,. It was delicious, we were doing groceries today and I had the thought that I hadn't had fish in a while.
> 
> My father loves fish and especially seafood so when I lived with them it was much more common around the house!
>
>
I was raised in Southern California about 20 minutes from the beach, so we enjoyed seafood quite often when growing up as well. Almost every weekend we had some kind of seafood, mostly fresh fish (tuna, salmon, sea bass) my Mom would get from the market near the pier. And she had all kinds of recipes for fish so we would not get bored with it; I certainly never did. To this day, we all still enjoy fish cooked in many different ways.

**Comment by ExtremeFiretop** [comment]
> I prefer the model IDs though because it makes it obvious on the main menu as soon as you load the script it's not compatible instead of failing due to low memory, but your right we have more safeties than I realize sometimes!

Correction; I was looking at the `check_memory_and_prompt_reboot` function; but you were talking about the `_HasRouterMoreThan256MBtotalRAM_` function; which actually does splash it on the main screen as well.

WE REALLY have more safeties than I realize sometimes ;)

**Pull request merged**
