### PR TITLE
Update MerlinAU.sh Quick Patch for ROG Menu

### PR DESCRIPTION
**Pull request by ExtremeFiretop**
Update MerlinAU.sh 

Quick Patch to Follow your fancy new menu standard on the ROG selection screen.
Tested and all seems to work well :)

### CODE REVIEW

**Comment by ExtremeFiretop** [comment]
If your happy with this, I guess we go to production next?
Let me know your final thoughts, if there's nothing else then lets go for it!

**Review by Martinski4GitHub — APPROVED** [review]
Looks nice. The menus look more consistent WRT "look & feel."

**Comment by Martinski4GitHub** [comment]
Ready for production.

**Comment by ExtremeFiretop** [comment]
> Ready for production.

Gonna touch up the readme and version.text file and then make the post then! 

Lots of good improvements in this round I say. High five buddy 🙏

Back to taking a break for a bit I think unless someone points something out we both missed.

**Comment by ExtremeFiretop** [comment]
> Looks nice. The menus look more consistent WRT "look & feel."

Agreed, as soon as I saw what you did I felt the need to apply it to the ROG menu and it makes the ROG build stuff feel more integrated and less of a bolt on attachment lol!

**Comment by Martinski4GitHub** [comment]
@ExtremeFiretop,

Yeah, the script is looking much more polished and refined as the code matures and we make this kind of improvements.

**Pull request merged**
