### PR TITLE
Match between Gnuton and Merlin for Changelog Behaviour

### PR DESCRIPTION
**Pull request by ExtremeFiretop**
Match between Gnuton and Merlin for Changelog Behaviour

### CODE REVIEW

**Comment by ExtremeFiretop** [comment]
Not sure if your back yet @Martinski4GitHub 

So just figured I'd push this through.

**Comment by Martinski4GitHub** [comment]
> Not sure if your back yet @Martinski4GitHub
> 
> So just figured I'd push this through.
>
Hey, bud. We're back home from vacation. We arrived early this evening, safe & sound.
I hope you've had some time to rest & relax as well.
I'm still catching up with email (work & personal).

**Comment by ExtremeFiretop** [comment]
> > Not sure if your back yet @Martinski4GitHub
> > So just figured I'd push this through.
> 
> Hey, bud. We're back home from vacation. We arrived early this evening, safe & sound. I hope you've had some time to rest & relax as well. I'm still catching up with email (work & personal).

Your back safe and sound! Fantastic! I hope you had a good trip! Feel free to share any highlights! I'm all ears! How was the place you were staying at? Etc?

Honestly my 2 weeks have been so busy, side job has me setting up their new domain controller (old one was nearly 20 years old and EoL is under playing it)

My day job has been going non-stop, so much scripting my brain hurts since we are working on multiple issues for a new deployment.

I actually wish I could share specifics of the code with you because someone of your skill level could probably make easy work of some of the issues I face 😂

Fathers surgery went well, he's recovering well. I got into a fender bender with a new driver... Not at fault and insurance is dealing with it... Not only did the new driver did an illegal turn but didn't have insurance... It's made things extra complicated.

Anyways all that to say I just pumped out MerlinAU not long ago, I didn't notice anything serious broken, this PR was the only small difference I noticed so I figured I'd send it off. I noticed the change to the workflow didn't update the branch so I did it again myself and modified the workflow again (it was missing the steps to commit the changes.. duh).

Hope your not too backed up and can catch up quickly! It's been quiet on the GitHub side since you've been gone hehe.

**Comment by Martinski4GitHub** [comment]
> > > Not sure if your back yet @Martinski4GitHub
> > > So just figured I'd push this through.
> > 
> > 
> > Hey, bud. We're back home from vacation. We arrived early this evening, safe & sound. I hope you've had some time to rest & relax as well. I'm still catching up with email (work & personal).
> 
> Your back safe and sound! Fantastic! I hope you had a good trip! Feel free to share any highlights! I'm all ears! How was the place you were staying at? Etc?
> 
>
Thank you. Yes, it was an excellent trip, very relaxing & enjoyable. We arrived at the Honolulu airport (in Oahu) the evening of Aug-22nd and stayed at the Hilton Hawaiian Village on Waikiki Beach (south side of the Oahu island). We went to 4 islands: Oahu, Hawaii (the Big Island), Maui & Molokai, and stayed on each island for 3 full days, except for Maui (4 days). The natural scenery of the beaches, wilderness parks, crystal clear rivers & waterfalls were just breathtaking & beautiful. So many natural surroundings to be in that give you a very relaxing and calming atmosphere. Some places were really crowded with tourists (as expected), and others were not; but since we were not in a hurry to do things and come back "home" at a certain time, we just relaxed and enjoyed each day.

I got to tell you, things tend to be expensive in all of Hawaii since a lot of products & groceries are shipped from the mainland or imported from elsewhere; but the trip is well worth it, IMO. I'd certainly recommend Hawaii for vacation.

>
> Honestly my 2 weeks have been so busy, side job has me setting up their new domain controller (old one was nearly 20 years old and EoL is under playing it)
> 
> My day job has been going non-stop, so much scripting my brain hurts since we are working on multiple issues for a new deployment.
> 
>
Well, at least being busy with work keeps you out of trouble!! :>)

> I actually wish I could share specifics of the code with you because someone of your skill level could probably make easy work of some of the issues I face 😂
> 
> Fathers surgery went well, he's recovering well.
>
>
I'm glad your Father is doing well in his recovery. I know having surgery can be a scary thing to go through.

>
>
> I got into a fender bender with a new driver... Not at fault and insurance is dealing with it... Not only did the new driver do an illegal turn, but didn't have insurance... It's made things extra complicated.
> 
>
Oh man, that's unfortunate. At least the insurance is taking care of it, but I hate it when some drivers don't have their own insurance.

>
>
> Anyways all that to say I just pumped out MerlinAU not long ago, I didn't notice anything serious broken, this PR was the only small difference I noticed so I figured I'd send it off. I noticed the change to the workflow didn't update the branch so I did it again myself and modified the workflow again (it was missing the steps to commit the changes.. duh).
> 
>
Yeah, I saw that as I was going through the emails & messages from GitHub. So far so good, but the "real test" for the script will be when the next F/W update gets issued for both RMerlin & Gnuton.

>
> Hope your not too backed up and can catch up quickly! It's been quiet on the GitHub side since you've been gone hehe.
>
I'm almost caught up on my personal emails. My work emails will take a bit more time. I will go to bed early today and get back to my "normal" schedule (I'm still on Hawaii's time - 3 hours early - so my body needs to "resync" with local time).

**Comment by ExtremeFiretop** [comment]
> 
> Thank you. Yes, it was an excellent trip, very relaxing & enjoyable. We arrived at the Honolulu airport (in Oahu) the evening of Aug-22nd and stayed at the Hilton Hawaiian Village on Waikiki Beach (south side of the Oahu island). We went to 4 islands: Oahu, Hawaii (the Big Island), Maui & Molokai, and stayed on each island for 3 full days, except for Maui (4 days). The natural scenery of the beaches, wilderness parks, crystal clear rivers & waterfalls were just breathtaking & beautiful. So many natural surroundings to be in that give you a very relaxing and calming atmosphere. Some places were really crowded with tourists (as expected), and others were not; but since we were not in a hurry to do things and come back "home" at a certain time, we just relaxed and enjoyed each day.

It sounds like an excellent time! I've never been to Hawaii; but who doesn't know how beautiful it is? 
I should really put it on the list with my girlfriend someday soon. We are the type to enjoy some nice beaches and beautiful scenery as well :) It's unfortunate some places get crowded with tourists; but as you mentioned your not in a rush on vacation, just think of it as part of the experience when it's such a nice and populate place!

> 
> I got to tell you, things tend to be expensive in all of Hawaii since a lot of products & groceries are shipped from the mainland or imported from elsewhere; but the trip is well worth it, IMO. I'd certainly recommend Hawaii for vacation.

I BELIEVE IT! Again i've never been, but I have zero doubt that things are more expensive there. Usually the american dollar gets you pretty far in other places around the world though ;)

> 
> I'm almost caught up on my personal emails. My work emails will take a bit more time. I will go to bed early today and get back to my "normal" schedule (I'm still on Hawaii's time - 3 hours early - so my body needs to "resync" with local time).

I was actually just heading to bed myself when I got this message so I totally understand ;) Jet lag is a real thing, the most intense for me was when visiting France and England. Took at least week if not more to fully shift my sleep schedule.

> 
> Yeah, I saw that as I was going through the emails & messages from GitHub. So far so good, but the "real test" for the script will be when the next F/W update gets issued for both RMerlin & Gnuton.

Agreed! I'm looking forwards to seeing how it works when both release, also looking forwards to seeing if anyone reports anything and if so, what. Naturally we can review and review endlessly, but only in the wild will the little odd issues will show up. 

> 
> Oh man, that's unfortunate. At least the insurance is taking care of it, but I hate it when some drivers don't have their own insurance.

Tell me about it. I wasn't happy that day, it's a fairly new car too. I have a 2021 Genesis G70, love the sport luxury feel of the car, it's almost my first car I bought brand new as the first owner so I have extra attachment to it for that. Luckily the damage is minimal, about 2k to 3k *CAD* of damage to my front passenger side. It's book for repairs on the 17th and will take a few days and I get a loaner in the meantime.

I'm not sure how it works for you guys in states but I'm sure it's pretty similar, here in Canada we only get one "freebie" when it comes to accidents, as in one non-at-fault accident no matter who the fault was, often called "accident forgiveness" policy or "forgive and forget" policy depending where you live.

I really didn't want to blow that before the age of 30 lol, luckily on my side it wasn't much of an argument, the police and the insurance both agreed the other drive did an illegal turn at an intersection where it was posted all over, and the other drive wasn't even insured so the blame falls on him, my insurance company isn't happy since they won't have another insurance company to collect money from though.

> 
> I'm glad your Father is doing well in his recovery. I know having surgery can be a scary thing to go through.

I almost feel I was more scared than him, he walked out of the surgery with a patch over his eye and a big smile making pirate jokes, and I was just picturing some crazy doctor going at his eye with needles haha! (I'm sure my imagination is far off from the truth!)

**Pull request merged**
