### PR TITLE
Code change to address script file path issue.

### PR DESCRIPTION
**Pull request by Martinski4GitHub**
Code change to address possible script file path issue reported in SNB Forums WRT the scheduled cron job.

### CODE REVIEW

**Comment by Martinski4GitHub** [comment]
@ExtremeFiretop,

This PR is an attempt to address the cron job path issue described in this SNB Forums post:

https://www.snbforums.com/threads/merlinau-v1-1-2-the-ultimate-firmware-auto-updater-now-available-in-amtm.88577/page-18#post-905380

But without knowing what the actual root cause is, I can't say it's a fix.

**Comment by ExtremeFiretop** [comment]
> @ExtremeFiretop,
> 
> This PR is an attempt to address the cron job path issue described in this SNB Forums post:
> 
> https://www.snbforums.com/threads/merlinau-v1-1-2-the-ultimate-firmware-auto-updater-now-available-in-amtm.88577/page-18#post-905380
> 
> But without knowing what the actual root cause is, I can't say it's a fix.

You already guessed better than me. 
I couldn't replicate any of his behavior that's why I thought I'd tag you into that one lol.

**Review by ExtremeFiretop — APPROVED** [review]

**Comment by Martinski4GitHub** [comment]
> > But without knowing what the actual root cause is, I can't say it's a fix.
> 
> You already guessed better than me. I couldn't replicate any of his behavior that's why I thought I'd tag you into that one lol.
>
I'm hoping that the OP will come back with more exact details about how he's manually launching the script. I think that's where the clues may be. I can't think of anything else at this point without more data or a way to recreate the "bad path."

**Comment by ExtremeFiretop** [comment]
> > > But without knowing what the actual root cause is, I can't say it's a fix.
> > 
> > 
> > You already guessed better than me. I couldn't replicate any of his behavior that's why I thought I'd tag you into that one lol.
> 
> I'm hoping that the OP will come back with more exact details about how he's manually launching the script. I think that's where the clues may be. I can't think of anything else at this point without more data or a way to recreate the "bad path."

I saw nothing in the code that would make the cron populate with /./ Instead of the regular syntax it's just so weird.

He is extremely quick to reply usually. I think he is even the type to respond at 3am my time (midnight your time) so I would expect a reply sometime tonight or early tomorrow at the latest.

**Comment by ExtremeFiretop** [comment]
@Martinski4GitHub 

As expected the user replied last night, but the feedback wasn't too helpful (for me anyways) to identify what was causing this.
Lets hope this change is all that was needed, else I feel some deep dive investigation upcoming.

**Comment by Martinski4GitHub** [comment]
> @Martinski4GitHub
> 
> As expected the user replied last night, but the feedback wasn't too helpful (for me anyways) to identify what was causing this. Lets hope this change is all that was needed, else I feel some deep dive investigation upcoming.
>
Yes, he did reply quickly but, as you said, the information was not really useful, unfortunately.
I still cannot see how the script path got mangled like that with the extra 2 chars: "`/.`" It's very odd.

**Pull request merged**
