### PR TITLE
Update MerlinAU.sh

### PR DESCRIPTION
**Pull request by Martinski4GitHub**
Some code cleanup & improvements.

Still looking into a problem where the log directory path keeps changing every time I start the script. It doesn't honor the selection I make using the menu option. Very annoying.

I know where the bug is. I just need to figure out a fix for it.

### CODE REVIEW

**Comment by ExtremeFiretop** [comment]
Finally got the beta stuff figured out.

Damn that like banging my head against the wall for half an hour. Lol
Eventually you get a headache but knock down the wall.

I'll wait until this gets merged to submit my PR.

**Comment by ExtremeFiretop** [comment]
Reviewing your PR now, I see you managed to fix it and I need to understand how lol. Give me 5 minutes

**Comment by Martinski4GitHub** [comment]
@ExtremeFiretop,

OK, the bug is fixed. When you get a chance, give a once-over to make sure I didn't miss anything,

**Comment by Martinski4GitHub** [comment]
> Finally got the beta stuff figured out.
> 
Excellent buddy!! Good going.

>
> Damn that like banging my head against the wall for half an hour. Lol Eventually you get a headache but knock down the wall.
>
Oh yeah, I got scars & bumps from that myself. I think they've got callouses already :>)

**Comment by ExtremeFiretop** [comment]
> > Finally got the beta stuff figured out.
> 
> Excellent buddy!! Good going.
> 
> > Damn that like banging my head against the wall for half an hour. Lol Eventually you get a headache but knock down the wall.
> 
> Oh yeah, I got scars & bumps from that myself. I think they've got callouses already :>)

Hahaha I know, not sure how you implemented that the first time without losing your mind.
I thought it understood it the first time I reviewed it, changing the versions (388.6) to numbers (388006000) for comparison, etc.
But when it came to implementing some kinda switch to add beta as a lower number I was kinda lost. 

I ended up implementing a weighting system, if beta is found it automatically add a -1000 weight to the build number/version so beta is considered lower than production.

Thank the lord that one is over.
As for your PR, it looks good! Lots corrections to my crappy notepad formatting... LOL Sorry.

**Comment by ExtremeFiretop** [comment]
Okay @Martinski4GitHub 

About to merge this in, looks good to me. I gotta ask, how are you doing the edits without having to cleanup all these blank returns?

I'm using notepad++ on windows with the scripting language set to bash, and I'm struggling to identify when I do it lol.
I'm at the point now where whenever I hit "enter" on my keyboard to go a line down I go back to adjust the empty space it left lol.

**Comment by Martinski4GitHub** [comment]
> > > Finally got the beta stuff figured out.
> > 
> > 
> > Excellent buddy!! Good going.
> > > Damn that like banging my head against the wall for half an hour. Lol Eventually you get a headache but knock down the wall.
> > 
> > 
> > Oh yeah, I got scars & bumps from that myself. I think they've got callouses already :>)
> 
> Hahaha I know, not sure how you implemented that the first time without losing your mind. I thought it understood it the first time I reviewed it, changing the versions (388.6) to numbers (388006000) for comparison, etc. But when it came to implementing some kinda switch to add beta as a lower number I was kinda lost.
>
Actually, that's a classic method to convert a version string into a numeric value for comparison purposes. It's been used for decades. I've written the same function in C, C++, Java, Bash, C-Shell & JavaScript for exactly the same purpose.

> 
> I ended up implementing a weighting system, if beta is found it automatically add a -1000 weight to the build number/version so beta is considered lower than production.
> 
Yeah, I'm almost done reviewing it. Good idea to add a weighting system.

> 
> Thank the lord that one is over. As for your PR, it looks good! Lots corrections to my crappy notepad formatting... LOL Sorry.
>
I haven't used Windows Notepad for at least 20 years now. Honestly, no self-respecting programmer would be caught dead using it :>) It's just awful, clunky & lacks critical features needed for daily coding. I'd recommend **Visual Studio Code**. That's written by programmers for programmers. At the bare minimum, get a copy of **Notepad++** and just dump Notepad. You'll never miss it.

**Comment by Martinski4GitHub** [comment]
> Okay @Martinski4GitHub
> 
> About to merge this in, looks good to me. I gotta ask, how are you doing the edits without having to cleanup all these blank returns?
> 
> I'm using notepad++ on windows with the scripting language set to bash, and I'm struggling to identify when I do it lol. I'm at the point now where whenever I hit "enter" on my keyboard to go a line down I go back to adjust the empty space it left lol.
>
I use **Visual Studio Code** for shell scripting; used to have **Atom** editor but the project was end-of-life just last year. That was a really good editor for coding scripts. **Visual Studio Code** is excellent too, but it's overkill for shell scripts. It's got so many features & configuration options, that you can get lost trying to customize it to your liking, and it's got so many extensions that you can install (like add-ons) that chances are somebody already wrote an extension for something you think you need.

**Comment by Martinski4GitHub** [comment]
>
> I'm using notepad++ on windows with the scripting language set to bash, and I'm struggling to identify when I do it lol. I'm at the point now where whenever I hit "enter" on my keyboard to go a line down I go back to adjust the empty space it left lol.
>
I believe Notepad++ has several configuration options to select the type of "indentation" you want to have when you hit Enter for the next line. I don't use it for coding, but it's useful for taking quick notes, making to-do lists, and just writing down things you want to keep around for a day or two. I know it can be configured for different programming languages, but I never looked into that.

**Comment by ExtremeFiretop** [comment]
> > I'm using notepad++ on windows with the scripting language set to bash, and I'm struggling to identify when I do it lol. I'm at the point now where whenever I hit "enter" on my keyboard to go a line down I go back to adjust the empty space it left lol.
> 
> I believe Notepad++ has several configuration options to select the type of "indentation" you want to have when you hit Enter for the next line. I don't use it for coding, but it's useful for taking quick notes, making to-do lists, and just writing down things you want to keep around for a day or two. I know it can be configured for different programming languages, but I never looked into that.

Crap, if only I knew about this setting before the start of the project.. *Eye roll*

image

**Pull request merged**
