### PR TITLE
Allow Test of Login Credentials

### PR DESCRIPTION
**Pull request by ExtremeFiretop**
Allow Test of Login Credentials as requested by:

https://www.snbforums.com/threads/merlinau-v1-0-5-the-ultimate-firmware-auto-updater-now-available-in-amtm.88577/post-895275

### CODE REVIEW

**Review by Martinski4GitHub — APPROVED** [review]
Looks good. Approved.

**Comment by Martinski4GitHub** [comment]
@ExtremeFiretop,

Some time ago (around the mid-2000s, IIRC, on one of the projects I was working on), I wrote a C++ library function that handled password user inputs. Among its many features was allowing users to choose whether to make the password visible and show the password length as they type. It also handled min & max length. Anyway, I think I can make a similar (but simpler) function for our script to make password input a lot more user-friendly & better than having no feedback whatsoever and not knowing whether you're typing the correct chars (especially for those of us who have long, complex password strings).

What do you think?

**Comment by ExtremeFiretop** [comment]
> @ExtremeFiretop,
> 
> Some time ago (around the mid-2000s, IIRC, on one of the projects I was working on), I wrote a C++ library function that handled password user inputs. Among its many features was allowing users to choose whether to make the password visible and show the password length as they type. It also handled min & max length. Anyway, I think I can make a similar (but simpler) function for our script to make password input a lot more user-friendly & better than having no feedback whatsoever and not knowing whether you're typing the correct chars (especially for those of us who have long, complex password strings).
> 
> What do you think?

I love it, it's one of the many things I think me and others would like to have considering the password input on a shell is blanked out right now.

**Comment by Martinski4GitHub** [comment]
>
> > What do you think?
> 
> I love it, it's one of the many things I think me and others would like to have considering the password input on a shell is blanked out right now.
>
OK, I'll start working on it this evening. Give me until tomorrow to submit a PR.

**Comment by ExtremeFiretop** [comment]
> > > What do you think?
> > 
> > 
> > I love it, it's one of the many things I think me and others would like to have considering the password input on a shell is blanked out right now.
> 
> OK, I'll start working on it this evening. Give me until tomorrow to submit a PR.

No rush, I was thinking we push an update out soon,nir does have some pretty important fixes for LAN access and the ROG stuff, but at the same time they all know it's coming and the one person that had an issue is fixed for now. 

The hussle is over for this release cycle anyways, take all the time you need. :) I know your busy with other things this month so no rush.

My birthday is coming up so I'll probably be AFK for the weekend of March 9th and 10th.

**Comment by Martinski4GitHub** [comment]
> 
> No rush, I was thinking we push an update out soon, it does have some pretty important fixes for LAN access and the ROG stuff, but at the same time they all know it's coming and the one person that had an issue is fixed for now.
> 
OK, great. It should be done by tomorrow evening for sure. If nothing else comes up, the next master release could be issued over this coming weekend.

> The hussle is over for this release cycle anyways, take all the time you need. :) I know your busy with other things this month so no rush.
>
Actually, it's the next couple of months (Mar & Apr) that will be very busy, the workload this week already started ramping up, slowly but surely, including a few more meetings to discuss pending issues from the backlog, customer requests, etc.

> 
> My birthday is coming up so I'll probably be AFK for the weekend of March 9th and 10th.
>
Well, I'll wish you an early Happy Birthday, just in case we don't talk much after this weekend.

**Pull request merged**
