### PR TITLE
Update MerlinAU.sh with Memory Warnings

### PR DESCRIPTION
**Pull request by ExtremeFiretop**
Added the discussed warnings both in the menu and the run script.

1. Integrate the RAM Check: 
Use the _HasRouterMoreThan256MBtotalRAM_() function to determine if the router has more than 256MB of total RAM. If it doesn't, and the ZIP file size is over 50MB, we should enforce the requirement of a USB-attached drive for storing the ZIP file.

2. Warning Message in Menu: 
Display a warning message in the main menu if the router has only 256MB of RAM and no USB drive is selected as the zip destination.

### CODE REVIEW

**Comment by ExtremeFiretop** [comment]
3. Also beautified the script menu and ROG prompts a bit.

**Comment by ExtremeFiretop** [comment]
4. Also moved the logging start location out of the regular user prompts as per the current standard.

**Comment by Martinski4GitHub** [comment]
> Added the discussed warnings both in the menu and the run script.
> 
>     1. Integrate the RAM Check:
>        Use the _HasRouterMoreThan256MBtotalRAM_() function to determine if the router has more than 256MB of total RAM. If it doesn't, and the ZIP file size is over 50MB, we should enforce the requirement of a USB-attached drive for storing the ZIP file.
> 
>     2. Warning Message in Menu:
>        Display a warning message in the main menu if the router has only 256MB of RAM and no USB drive is selected as the zip destination.
> 
Everything is looking good!

**Comment by ExtremeFiretop** [comment]
> > Added the discussed warnings both in the menu and the run script.
> > ```
> > 1. Integrate the RAM Check:
> >    Use the _HasRouterMoreThan256MBtotalRAM_() function to determine if the router has more than 256MB of total RAM. If it doesn't, and the ZIP file size is over 50MB, we should enforce the requirement of a USB-attached drive for storing the ZIP file.
> > 
> > 2. Warning Message in Menu:
> >    Display a warning message in the main menu if the router has only 256MB of RAM and no USB drive is selected as the zip destination.
> > ```
> 
> Everything is looking good!

Whoot woot!

**Pull request merged**
