### PR TITLE
Dev 1.3.3 as Next Stable Release

### PR DESCRIPTION
**Pull request by ExtremeFiretop**
Dev 1.3.3 as Next Stable Release

Mostly to test the new workflow, but also to include the latest PR in production.

What's Changed/Fixed?:

PR: [ #342 ]
Code Improvements. Versioning Regex.

As always, we highly recommend you update ASAP as this includes functional improvements and little bug fixes.

### CODE REVIEW

**Comment by Martinski4GitHub** [comment]
> Dev 1.3.3 as Next Stable Release
> 
> Mostly to test the new workflow, but also to include the latest PR in production.
> ...
>
OK, let me try now to test the workflow. Fingers crossed.. :>)

**Review by Martinski4GitHub — APPROVED** [review]
Production ready & good to go!!

**Comment by ExtremeFiretop** [comment]
> Production ready & good to go!!

Okay! I'll quickly ready the post and update the readme.  One momento!

**Comment by Martinski4GitHub** [comment]
> > Dev 1.3.3 as Next Stable Release
> > Mostly to test the new workflow, but also to include the latest PR in production.
> > ...
> 
> OK, let me try now to test the workflow. Fingers crossed.. :>)
>
>
QUESTION: 
Is it supposed to do the **merge** automatically **after** the approval?
So far, the merge has not been done automatically.
FYI.

**Comment by ExtremeFiretop** [comment]
> > > Dev 1.3.3 as Next Stable Release
> > > Mostly to test the new workflow, but also to include the latest PR in production.
> > > ...
> > 
> > 
> > OK, let me try now to test the workflow. Fingers crossed.. :>)
> 
> QUESTION: Is it supposed to do the **merge** automatically **after** the approval? So far, the merge has not been done automatically. FYI.
> 

Only if I enable auto-merge on my side which I did not today because I didn't have the post ready and wasn't sure when you were going to be available :)

image

> P.S. Do you want me to do the **merge** manually now? If not, I'll let you do it when you feel ready with the README and the post.

I have the post ready, so merge whenever your ready manually! Lets monitor the workflow together (under the actions tab above)

**Comment by Martinski4GitHub** [comment]
> > > > Dev 1.3.3 as Next Stable Release
> > > > Mostly to test the new workflow, but also to include the latest PR in production.
> > > > ...
> > > 
> > > 
> > > OK, let me try now to test the workflow. Fingers crossed.. :>)
> > 
> > 
> > QUESTION: Is it supposed to do the **merge** automatically **after** the approval? So far, the merge has not been done automatically. FYI.
> 
> Only if I enable auto-merge on my side which I did not today because I didn't have the post ready and wasn't sure when you were going to be available :)
> 
>
Got it!!

> 
> > P.S. Do you want me to do the **merge** manually now? If not, I'll let you do it when you feel ready with the README and the post.
> 
> I have the post ready, so merge whenever your ready manually! Lets monitor the workflow together (under the actions tab above)
>
>
OK, about to do it in 3... 2... 1...

**Review by Martinski4GitHub — APPROVED** [review]
Approved!!

**Comment by ExtremeFiretop** [comment]
> Approved!!

Well; it worked once I updated the version.txt! LOL!
Clearly it's been a while since we've done this.

**Comment by Martinski4GitHub** [comment]
> > Approved!!
> 
> Well; it worked once I updated the version.txt! LOL! Clearly it's been a while since we've done this.
>
>
Yeah, I noticed that. I also just received a couple of email notifications about some failures. 
Did you get them as well?

AutoTagAndReleaseonPRMergeFailed

**Comment by ExtremeFiretop** [comment]
> > > Approved!!
> > 
> > 
> > Well; it worked once I updated the version.txt! LOL! Clearly it's been a while since we've done this.
> 
> Yeah, I noticed that. I also just received a couple of email notifications about some failures. Did you get them as well?
> 
> AutoTagAndReleaseonPRMergeFailed

Oh that's cool! Yes I get them but I wasn't sure if you did. Good to know if something goes wrong your aware.

As soon as I checked the actions tab; I saw it fail on the "tag already exists" and I went oh right... the version.txt file lol!
Quickly committed that change; and the workflow worked as expected and updated everything and made the release.

What I think I'll do is make it a habit to update the version.txt file right away, so like.... now... in dev. 
So that step is never overlooked when we go live.

**Comment by ExtremeFiretop** [comment]
> 
> What I think I'll do is make it a habit to update the version.txt file right away, so like.... now... in dev. So that step is never overlooked when we go live.

Actually; would doing that mess with the dev branch if people wanted to download that? since the version in the script is still 1.3.3? I guess I would need to update both now right?

**Comment by Martinski4GitHub** [comment]
> > > > Approved!!
> > > 
> > > 
> > > Well; it worked once I updated the version.txt! LOL! Clearly it's been a while since we've done this.
> > 
> > 
> > Yeah, I noticed that. I also just received a couple of email notifications about some failures. Did you get them as well?
> > AutoTagAndReleaseonPRMergeFailed
> 
> Oh that's cool! Yes I get them but I wasn't sure if you did. Good to know if something goes wrong your aware.
> 
>
Yeah, it's the first time I got them. Good to be aware.


> As soon as I checked the actions tab; I saw it fail on the "tag already exists" and I went oh right... the version.txt file lol! Quickly committed that change; and the workflow worked as expected and updated everything and made the release.
> 
> What I think I'll do is make it a habit to update the version.txt file right away, so like.... now... in dev. So that step is never overlooked when we go live.
>
>
OK, that's fine although, technically, both branches are exactly the same version right now.

**Comment by Martinski4GitHub** [comment]
> > What I think I'll do is make it a habit to update the version.txt file right away, so like.... now... in dev. So that step is never overlooked when we go live.
> 
> Actually; would doing that mess with the dev branch if people wanted to download that? since the version in the script is still 1.3.3? I guess I would need to update both now right?
>
>
I'd say the **version.txt** file on the 'develop' branch gets updated only when the code is actually modified with PR. Otherwise, it remains the same as the latest 'master' branch.

My 2 cents.

**Comment by ExtremeFiretop** [comment]
> > > > > Approved!!
> > > > 
> > > > 
> > > > Well; it worked once I updated the version.txt! LOL! Clearly it's been a while since we've done this.
> > > 
> > > 
> > > Yeah, I noticed that. I also just received a couple of email notifications about some failures. Did you get them as well?
> > > AutoTagAndReleaseonPRMergeFailed
> > 
> > 
> > Oh that's cool! Yes I get them but I wasn't sure if you did. Good to know if something goes wrong your aware.
> 
> Yeah, it's the first time I got them. Good to be aware.
> 
> > As soon as I checked the actions tab; I saw it fail on the "tag already exists" and I went oh right... the version.txt file lol! Quickly committed that change; and the workflow worked as expected and updated everything and made the release.
> > What I think I'll do is make it a habit to update the version.txt file right away, so like.... now... in dev. So that step is never overlooked when we go live.
> 
> OK, that's fine although, technically, both branches are exactly the same version right now.

That's why I'm not sure if its better I wait and just try to remember again in the future or if I should go ahead and update now even though they are they are technically both identical

**Comment by ExtremeFiretop** [comment]
> > > What I think I'll do is make it a habit to update the version.txt file right away, so like.... now... in dev. So that step is never overlooked when we go live.
> > 
> > 
> > Actually; would doing that mess with the dev branch if people wanted to download that? since the version in the script is still 1.3.3? I guess I would need to update both now right?
> 
> I'd say the **version.txt** file on the 'develop' branch gets updated only when the code is actually modified with PR. Otherwise, it remains the same as the latest 'master' branch.
> 
> My 2 cents.

Works for me! We'll just have to make note that there's 3 things to update when we go live and they never really changed but I think I was so focused on making sure the workflow worked I forgot step 3.

1. Update the forums
2. Update the readme
3. Update the version.txt lol

**Comment by Martinski4GitHub** [comment]
> > > > What I think I'll do is make it a habit to update the version.txt file right away, so like.... now... in dev. So that step is never overlooked when we go live.
> > > 
> > > 
> > > Actually; would doing that mess with the dev branch if people wanted to download that? since the version in the script is still 1.3.3? I guess I would need to update both now right?
> > 
> > 
> > I'd say the **version.txt** file on the 'develop' branch gets updated only when the code is actually modified with PR. Otherwise, it remains the same as the latest 'master' branch.
> > My 2 cents.
> 
> Works for me! We'll just have to make note that there's 3 things to update when we go live and they never really changed but I think I was so focused on making sure the workflow worked I forgot step 3.
> 
>     1. Update the forums
>     2. Update the readme
>     3. Update the version.txt lol
>
>
Sounds good to me. I'll make a note to update the **version.txt** on my next PR, if not already updated.

P.S.
I'm being summoned: Dinner is ready!!
Talk to you later. >:)

**Comment by ExtremeFiretop** [comment]
> > > > > What I think I'll do is make it a habit to update the version.txt file right away, so like.... now... in dev. So that step is never overlooked when we go live.
> > > > 
> > > > 
> > > > Actually; would doing that mess with the dev branch if people wanted to download that? since the version in the script is still 1.3.3? I guess I would need to update both now right?
> > > 
> > > 
> > > I'd say the **version.txt** file on the 'develop' branch gets updated only when the code is actually modified with PR. Otherwise, it remains the same as the latest 'master' branch.
> > > My 2 cents.
> > 
> > 
> > Works for me! We'll just have to make note that there's 3 things to update when we go live and they never really changed but I think I was so focused on making sure the workflow worked I forgot step 3.
> > ```
> > 1. Update the forums
> > 2. Update the readme
> > 3. Update the version.txt lol
> > ```
> 
> Sounds good to me. I'll make a note to update the **version.txt** on my next PR, if not already updated.
> 
> P.S. I'm being summoned: Dinner is ready!! Talk to you later. >:)

Exactly. 

That's going to be the rule of thumb I think for both of us. Whoever does the first PR to dev also updates the version.txt. so that it's all done in sync.

Enjoy dinner my friend!

**Comment by Martinski4GitHub** [comment]
> > > > > > What I think I'll do is make it a habit to update the version.txt file right away, so like.... now... in dev. So that step is never overlooked when we go live.
> > > > > 
> > > > > 
> > > > > Actually; would doing that mess with the dev branch if people wanted to download that? since the version in the script is still 1.3.3? I guess I would need to update both now right?
> > > > 
> > > > 
> > > > I'd say the **version.txt** file on the 'develop' branch gets updated only when the code is actually modified with PR. Otherwise, it remains the same as the latest 'master' branch.
> > > > My 2 cents.
> > > 
> > > 
> > > Works for me! We'll just have to make note that there's 3 things to update when we go live and they never really changed but I think I was so focused on making sure the workflow worked I forgot step 3.
> > > ```
> > > 1. Update the forums
> > > 2. Update the readme
> > > 3. Update the version.txt lol
> > > ```
> > 
> > 
> > Sounds good to me. I'll make a note to update the **version.txt** on my next PR, if not already updated.
> > P.S. I'm being summoned: Dinner is ready!! Talk to you later. >:)
> 
> Exactly.
> 
> That's going to be the rule of thumb I think for both of us. Whoever does the first PR to dev also updates the version.txt. so that it's all done in sync.
>
>
We're in full agreement.

> 
>
> Enjoy dinner my friend!
>
>
Thanks. It was gooood!! (baked salmon, rice with quinoa & steamed vegetables -  salmon is my favorite fish to eat :>).

Have a good night, bud, and enjoy your weekend.

**Pull request merged**
