### PR TITLE
Include Password Tab Debounce

### PR DESCRIPTION
**Pull request by ExtremeFiretop**
Include Password Tab Debounce

### CODE REVIEW

**Comment by ExtremeFiretop** [comment]
@Martinski4GitHub 

I can't find anything else that needs work after this :)
Let me know how you feel about packaging it up and sending it out.

**Review by Martinski4GitHub — APPROVED** [review]
Looks good.

**Comment by Martinski4GitHub** [comment]
> @Martinski4GitHub
> 
> I can't find anything else that needs work after this :) Let me know how you feel about packaging it up and sending it out.
>
I think it's ready to go anytime you're ready, either this evening or sometime over the weekend.

I'll be offline for a while this evening (I forgot that my wife & I are supposed to meet some old friends for dinner - I thought it was tomorrow evening).

**Comment by ExtremeFiretop** [comment]
> > @Martinski4GitHub
> > I can't find anything else that needs work after this :) Let me know how you feel about packaging it up and sending it out.
> 
> I think it's ready to go anytime you're ready, either this evening or sometime over the weekend.
> 
> I'll be offline for a while this evening (I forgot that my wife & I are supposed to meet some old friends for dinner - I thought it was tomorrow evening).

I'll start packaging it up and making the changes tonight then. Tomorrow we can relax on the weekend :)

Enjoy dinner my friend! And enjoy the next few months as best you can, I'll know to just merge changes after this one without waiting for review, you'll always be tagged as a reviewer anyways as a code owner.

**Comment by Martinski4GitHub** [comment]
> 
> I'll start packaging it up and making the changes tonight then. Tomorrow we can relax on the weekend :)
> 
> Enjoy dinner my friend! And enjoy the next few months as best you can, I'll know to just merge changes after this one without waiting for review, you'll always be tagged as a reviewer anyways as a code owner.
>
Sounds good. I'll be popping in & out on occasions. You can always leave me a message, of course. If it seems like an urgent fix is needed, I can take some time (especially over the weekends) to investigate & find a resolution.

**Comment by ExtremeFiretop** [comment]
> > I'll start packaging it up and making the changes tonight then. Tomorrow we can relax on the weekend :)
> > Enjoy dinner my friend! And enjoy the next few months as best you can, I'll know to just merge changes after this one without waiting for review, you'll always be tagged as a reviewer anyways as a code owner.
> 
> Sounds good. I'll be popping in & out on occasions. You can always leave me a message, of course. If it seems like an urgent fix is needed, I can take some time (especially over the weekends) to investigate & find a resolution.

At this point I think our tool is pretty rock solid, any updates would be small fixes or just maintenance releases. (I think)

Obviously if I have a big issue and I'm stuck I may ping you, but just know I got you covered while your away! 
I gotchu!

**Comment by ExtremeFiretop** [comment]
@Martinski4GitHub Viktor is requesting your assistance with your latest PR for some kind of issue. I'm didn't follow much about it originally but I'm trying to catch up now

**Pull request merged**
