### PR TITLE
Code Improvements

### PR DESCRIPTION
**Pull request by Martinski4GitHub**
Various code improvements & fine-tuning.

### CODE REVIEW

**Comment by Martinski4GitHub** [comment]
@ExtremeFiretop,

Nothing critical or urgent on this PR. Just some fine-tuning  & improvements.

Note that I moved the call for "POST_REBOOT_FW_UPDATE_SETUP" and the "Flashing Firmware..." log message right **before** ejecting the USB-attached drive. I think that's the best place now **after** taking the time to stop Diversion & the Entware services & then removing cron jobs from 3rd-party add-ons.

Take your time & review the PR when you have time. There's no rush.

**Review by ExtremeFiretop — APPROVED** [review]

**Comment by ExtremeFiretop** [comment]
Looks good to me! 
And I agree, as we add extra steps, it's best to keep the messaging as close to the actual flash as possible.

**Comment by ExtremeFiretop** [comment]
image

**Comment by Martinski4GitHub** [comment]
> image

Nice!! The order of the messaging/notifications is much better & makes more sense now.

**Comment by ExtremeFiretop** [comment]
> > image
> 
> Nice!! The order of the messaging/notifications is much better & makes more sense now.

I have a PR coming up in a few minutes btw; while testing the latest 3006 beta I noticed more tweaks to do. :)

**Pull request merged**
