### PR TITLE
Refine PR305 to Block By Branch

### PR DESCRIPTION
**Pull request by ExtremeFiretop**
Refine PR305 to Block By Branch

### CODE REVIEW

**Comment by Martinski4GitHub** [comment]
> Refine PR305 to Block By Branch
>
LOL!! I just found your message!! It looks like we both have been working on the same idea.

**Comment by Martinski4GitHub** [comment]
> Refine PR305 to Block By Branch
>
>
I just reviewed your PR and the code is pretty much similar to mine except that I made my changes near the top of the script so the actual function was left the same as before. Either way should work fine.

Note that in my PR I'm allowing for a future possibility that some of the AX-class PRO routers may eventually get a **3006.102** F/W update (just in case it happens). I just put a minimum **3004.388** version for now (it can be adjusted, of course).

**Comment by ExtremeFiretop** [comment]
> > Refine PR305 to Block By Branch
> 
> LOL!! I just found your message!! It looks like we both have been working on the same idea.

2 great minds think alike! LOL!

I just got the message now, I was finishing some documentation for work. Heading out to pickup the girlfriend now, will be back in 39 minutes.

**Comment by Martinski4GitHub** [comment]
> > > Refine PR305 to Block By Branch
> > 
> > 
> > LOL!! I just found your message!! It looks like we both have been working on the same idea.
> 
> 2 great minds think alike! LOL!
> 
>
Indeed!! LOL!!

>
> I just got the message now, I was finishing some documentation for work. Heading out to pickup the girlfriend now, will be back in 39 minutes.
>
>
Yeah OK, got it. Take your time. There's no rush. I'm told we're about to have dinner in about 10-15 minutes, so I'll be back online in an hour or so.

**Comment by ExtremeFiretop** [comment]
> > > > Refine PR305 to Block By Branch
> > > 
> > > 
> > > LOL!! I just found your message!! It looks like we both have been working on the same idea.
> > 
> > 
> > 2 great minds think alike! LOL!
> 
> Indeed!! LOL!!
> 
> > I just got the message now, I was finishing some documentation for work. Heading out to pickup the girlfriend now, will be back in 39 minutes.
> 
> Yeah OK, got it. Take your time. There's no rush. I'm told we're about to have dinner in about 10-15 minutes, so I'll be back online in an hour or so.

Je suis back! I am back! Enjoy dinner :) Just merged yours in!

**Comment by ExtremeFiretop** [comment]
Exactly 39 minutes too. Wow I am good.

**Pull request closed without merging**
