### PR TITLE
PATH to list built-in binary paths first

### PR DESCRIPTION
**Pull request by Martinski4GitHub**
Set up **PATH** to give top priority to built-in binaries.

This addresses the issue where users have equivalent Entware binaries installed and those get called instead.

See this post:

https://www.snbforums.com/threads/merlinau-v1-3-7-the-ultimate-firmware-auto-updater-gnuton-support.91326/page-3#post-936128

### CODE REVIEW

**Comment by Martinski4GitHub** [comment]
@ExtremeFiretop.

The fix in this PR addresses the problem reported in SNBForums and any future issues where some users have set up the **PATH** environment variable to give top priority to Entware binaries.

**Review by ExtremeFiretop — APPROVED** [review]

**Comment by ExtremeFiretop** [comment]
I requested he try and report back.

How did you know it's an environment path? Does it happen if you manually install coreutils?

**Comment by Martinski4GitHub** [comment]
> I requested he try and report back.
> 
> How did you know it's an environment path? Does it happen if you manually install coreutils?
>
Although not very often, I've seen this type of problem come up to the surface before where some users have installed a bunch of Entware utilities that have the same name as the built-in binaries and, in some rare cases, the behavior between the built-in & Entware versions is much different which leads to some errors or odd events.

The actual root cause is that the current default setup in Entware is to give top priority to Entware binaries in the **PATH** environment variable so those binaries get called first over the built-in binaries, hence the issues reported. This affects all Entware utilities installed but, as mentioned, the issues come up only when the behavior is different between the native & the external binary.

**Comment by ExtremeFiretop** [comment]
@Martinski4GitHub I created this branch: https://github.com/ExtremeFiretop/MerlinAutoUpdate-Router/blob/WebFun/MerlinAU.asp

I am testing changes using this file to install: https://github.com/ExtremeFiretop/MerlinAutoUpdate-Router/blob/WebFun/install.sh
and uninstall: https://github.com/ExtremeFiretop/MerlinAutoUpdate-Router/blob/WebFun/uninstall.sh between changes :) 

It's just a little side project for when I'm bord. feel free to poke at it with me though if you have any ideas.

**Comment by Martinski4GitHub** [comment]
> @Martinski4GitHub I created this branch: https://github.com/ExtremeFiretop/MerlinAutoUpdate-Router/blob/WebFun/MerlinAU.asp
> 
> I am testing changes using this file to install: https://github.com/ExtremeFiretop/MerlinAutoUpdate-Router/blob/WebFun/install.sh and uninstall: https://github.com/ExtremeFiretop/MerlinAutoUpdate-Router/blob/WebFun/uninstall.sh between changes :)
> 
> It's just a little side project for when I'm bord. feel free to poke at it with me though if you have any ideas.
>
>
You're a glutton for punishment!!! LOL!!!

I don't think I'll have the time to take a look until after I'm done with my deliverables for my day job and have finished setting up all the 3 new PRO routers over the holidays, plus other commitments I've made.

BTW, yesterday I finished setting up the new RT-AX86U-PRO at my parents' home. So far it's been working great for their somewhat simple network requirements; but we'll give it a full week or two before we can fully evaluate how it's really doing. Very good Wi-Fi coverage on their property and, as of this evening, they tell me that they see no need to add their old RT-AC68U as an AP. The 2.4GHz signal reaches far enough into their garage that its automatic door & lights work well and can be controlled from their phones.

Next weekend, I'll be setting up the new router for my in-laws.

**Comment by ExtremeFiretop** [comment]
> 
> You're a glutton for punishment!!! LOL!!!
> 

From you? Or from the WebUI? Cause I feel like the WebUI is punishment enough 😂 LOL

> I don't think I'll have the time to take a look until after I'm done with my deliverables for my day job and have finished setting up all the 3 new PRO routers over the holidays, plus other commitments I've made.
> 

No worries, it's slowly actually getting pretty good. The more time you give me the more you might actually like it be the time you take a look 😉

> BTW, yesterday I finished setting up the new RT-AX86U-PRO at my parents' home. So far it's been working great for their somewhat simple network requirements; but we'll give it a full week or two before we can fully evaluate how it's really doing. Very good Wi-Fi coverage on their property and, as of this evening, they tell me that they see no need to add their old RT-AC68U as an AP. The 2.4GHz signal reaches far enough into their garage that its automatic door & lights work well and can be controlled from their phones.
> 
> Next weekend, I'll be setting up the new router for my in-laws.

This is great news! I'm assuming that the familiar doesn't get Merlin firmware with their simple setup? Or do you still go the Merlin route without many scripts? 

I know some people like Merlin firmware due to extra bug fixes, security enhancements such as the recently discussed idea of removing AICloud, or some extra customizations he has baked in even though they don't plan on using many scripts. (Seems pretty common on the Gnuton community actually to not even know what AMTM is unless shown).

I'm happy to hear the coverage is good! The 6GHz on my primary 98 Pro could use some improvement that's for sure...

**Comment by ExtremeFiretop** [comment]
> 
> You're a glutton for punishment!!! LOL!!!
> 

I just realized this means I enjoy punishment not that I'm looking to receive punishment hahaha! Either way, I'm ready for whatever punishment your looking to give! WebUI isn't enough clearly 😂 LOL

**Comment by Martinski4GitHub** [comment]
> > You're a glutton for punishment!!! LOL!!!
> 
> From you? Or from the WebUI? Cause I feel like the WebUI is punishment enough 😂 LOL
>
>
From both??? Just kidding, LOL!! 
The F/W built-in web server is just so limited (as intended), that it's harder to work with when compared with a standard regular server (e.g. Apache).

> 
> > I don't think I'll have the time to take a look until after I'm done with my deliverables for my day job and have finished setting up all the 3 new PRO routers over the holidays, plus other commitments I've made.
> 
> No worries, it's slowly actually getting pretty good. The more time you give me the more you might actually like it be the time you take a look 😉
> 
>
Then, I won't look at it until next year!!! LOL!!!

>
> > BTW, yesterday I finished setting up the new RT-AX86U-PRO at my parents' home. So far it's been working great for their somewhat simple network requirements; but we'll give it a full week or two before we can fully evaluate how it's really doing. Very good Wi-Fi coverage on their property and, as of this evening, they tell me that they see no need to add their old RT-AC68U as an AP. The 2.4GHz signal reaches far enough into their garage that its automatic door & lights work well and can be controlled from their phones.
> > Next weekend, I'll be setting up the new router for my in-laws.
> 
> This is great news! I'm assuming that the familiar doesn't get Merlin firmware with their simple setup? Or do you still go the Merlin route without many scripts?
> 
> I know some people like Merlin firmware due to extra bug fixes, security enhancements such as the recently discussed idea of removing AICloud, or some extra customizations he has baked in even though they don't plan on using many scripts. (Seems pretty common on the Gnuton community actually to not even know what AMTM is unless shown).
> 
> I'm happy to hear the coverage is good! The 6GHz on my primary 98 Pro could use some improvement that's for sure...
>
Oh, yeah, they all get RMerlin's F/W for several reasons, but mainly because of the ability to run 3rd-party scripts since I installed my own set of scripts in addition to YazDHCP & YazFi.

**Comment by Martinski4GitHub** [comment]
> > You're a glutton for punishment!!! LOL!!!
> 
> I just realized this means I enjoy punishment not that I'm looking to receive punishment hahaha! Either way, I'm ready for whatever punishment your looking to give! WebUI isn't enough clearly 😂 LOL
>
>
LOL!!!  Yeah, that's basically what it means. Maybe it's more of an American expression?

**Pull request merged**
