### PR TITLE
Code to report found Mount Points

### PR DESCRIPTION
**Pull request by Martinski4GitHub**
Added code to report found Mount Points in case of failure to match an expected path to a mount point path.

### CODE REVIEW

**Comment by ExtremeFiretop** [comment]
Reviewing now :)

**Review by ExtremeFiretop — APPROVED** [review]

**Comment by ExtremeFiretop** [comment]
Testing now :)

**Comment by ExtremeFiretop** [comment]
Works as promised! Nice one buddy!

**Comment by Martinski4GitHub** [comment]
> Works as promised! Nice one buddy!
> 
When I read your response to the issue, I knew right away what to do and where to do it so I decided to add the code since it was quick & simple. Hopefully, next time when a similar issue happens WRT USB drive mount points, we'll have more details to figure out what may have caused the error.

**Pull request merged**
