### PR TITLE
Set the repo branch variable to "master" for production release

### PR DESCRIPTION
**Pull request by Martinski4GitHub**
The repo branch variable must be set  to "**master**" for production releases:
```
SCRIPT_BRANCH="master"
```

### CODE REVIEW

**Comment by ExtremeFiretop** [comment]
@Martinski4GitHub 

I see your PR?!?!

**Comment by Martinski4GitHub** [comment]
> @Martinski4GitHub
> 
> I see your PR?!?!
> 
Are you able to see all my comments in PR #263 as well?
If yes, then it looks like my account has been reinstated!!

**Comment by ExtremeFiretop** [comment]
> > @Martinski4GitHub
> > I see your PR?!?!
> 
> Are you able to see all my comments in PR #263 as well? If yes, then it looks like my account has been reinstated!!

Everything is back! I can see your repos, your comments and your PRs!

**Comment by Martinski4GitHub** [comment]
> > > @Martinski4GitHub
> > > I see your PR?!?!
> > 
> > 
> > Are you able to see all my comments in PR #263 as well? If yes, then it looks like my account has been reinstated!!
> 
> Everything is back! I can see your repos, your comments and your PRs!
>
Excellent!!! Back in business, Baby!!! :>)

**Comment by ExtremeFiretop** [comment]
> > > > @Martinski4GitHub
> > > > I see your PR?!?!
> > > 
> > > 
> > > Are you able to see all my comments in PR #263 as well? If yes, then it looks like my account has been reinstated!!
> > 
> > 
> > Everything is back! I can see your repos, your comments and your PRs!
> 
> Excellent!!! Back in business, Baby!!! :>)

Thank the heavens and the GitHub Support Engineers!

**Comment by Martinski4GitHub** [comment]
> > > > > @Martinski4GitHub
> > > > > I see your PR?!?!
> > > > 
> > > > 
> > > > Are you able to see all my comments in PR #263 as well? If yes, then it looks like my account has been reinstated!!
> > > 
> > > 
> > > Everything is back! I can see your repos, your comments and your PRs!
> > 
> > 
> > Excellent!!! Back in business, Baby!!! :>)
> 
> Thank the heavens and the GitHub Support Engineers!
>
I'm still wondering how to avoid the same "spammy" flag in the future.
Has the cause of the problem been addressed/fixed?
Is there anything I can or need to do to prevent a re-occurrence?

Anyway, we'll live to fight for another day!! :>)

**Comment by ExtremeFiretop** [comment]
> > > > > > @Martinski4GitHub
> > > > > > I see your PR?!?!
> > > > > 
> > > > > 
> > > > > Are you able to see all my comments in PR #263 as well? If yes, then it looks like my account has been reinstated!!
> > > > 
> > > > 
> > > > Everything is back! I can see your repos, your comments and your PRs!
> > > 
> > > 
> > > Excellent!!! Back in business, Baby!!! :>)
> > 
> > 
> > Thank the heavens and the GitHub Support Engineers!
> 
> I'm still wondering how to avoid the same "spammy" flag in the future. Has the cause of the problem been addressed/fixed? Is there anything I can or need to do to prevent a re-occurrence?
> 
> Anyway, we'll live to fight for another day!! :>)

Back to work on Gnuton!

I would of merged this in but I handled it this morning after your message on SNB and I couldn't see this PR at the time sadly.

**Comment by Martinski4GitHub** [comment]
> > 
> > 
> > I'm still wondering how to avoid the same "spammy" flag in the future. Has the cause of the problem been addressed/fixed? Is there anything I can or need to do to prevent a re-occurrence?
> > Anyway, we'll live to fight for another day!! :>)
> 
> Back to work on Gnuton!
> 
> I would of merged this in but I handled it this morning after your message on SNB and I couldn't see this PR at the time sadly.
>
No worries, bud. We were both trying to function under unusual circumstances. In the end, you fixed the problem & handled it. That's all that matters now.

I'm about to go offline as my wife & I had already plans to watch another movie.
We'll talk tomorrow!  Have a good night, bud!!

**Comment by ExtremeFiretop** [comment]
> > > I'm still wondering how to avoid the same "spammy" flag in the future. Has the cause of the problem been addressed/fixed? Is there anything I can or need to do to prevent a re-occurrence?
> > > Anyway, we'll live to fight for another day!! :>)
> > 
> > 
> > Back to work on Gnuton!
> > I would of merged this in but I handled it this morning after your message on SNB and I couldn't see this PR at the time sadly.
> 
> No worries, bud. We were both trying to function under unusual circumstances. In the end, you fixed the problem & handled it. That's all that matters now.
> 
> I'm about to go offline as my wife & I had already plans to watch another movie. We'll talk tomorrow! Have a good night, bud!!

Have a good evening buddy! My girlfriend already has pirates of the Caribbean on, so chat more tomorrow! I can't miss out on a good movie like that.

**Pull request closed without merging**
