### PR TITLE
Dev 0.2.40 Targeted as latest master/stable release

### PR DESCRIPTION
**Pull request by ExtremeFiretop**
Dev 0.2.40 Targeted as latest master/stable release

### CODE REVIEW

**Comment by ExtremeFiretop** [comment]
@Martinski4GitHub 

Merged all our improvements and hard work and troubleshooting into master/production.

Merry Christmas!! Happy Holidays!!

**Comment by Martinski4GitHub** [comment]
> @Martinski4GitHub
> 
> Merged all our improvements and hard work and troubleshooting into master/production.
> 
> Merry Christmas!! Happy Holidays!!
>
Let's open the champagne early & start toasting!!  :>)

**Comment by ExtremeFiretop** [comment]
> > @Martinski4GitHub
> > Merged all our improvements and hard work and troubleshooting into master/production.
> > Merry Christmas!! Happy Holidays!!
> 
> Let's open the champagne early & start toasting!! :>)

I never really went to sleep last night. I got a couple hours of zzz's
I've been toasting since Friday ;) Haha!

**Comment by ExtremeFiretop** [comment]
@Martinski4GitHub 

Just realize for me the script doesn't seem to run as a Cron job anymore :(
I don't know when that started happening.

Will troubleshoot some more tomorrow.

**Comment by Martinski4GitHub** [comment]
> @Martinski4GitHub
> 
> Just realized for me the script doesn't seem to run as a Cron job anymore :( I don't know when that started happening.
> 
> If I run other scripts in the jffs/scripts folder as crons they work normally. And our script works if I manually run this command: sh /./jffs/scripts/MerlinAU.sh run_now
> 
> But that command as a cron job seems to do nothing for me. I adjusted the cron to be every 1 minute and I have an update available and it still is doing nothing, while the other script I have to ping google every mintue is working fine on the same cron schedule.
> 
That's a very odd behavior. Just to clarify: the cron job "hook" is indeed found in the "**/jffs/scripts/services-start**" file, and the cron job entry does exist under **crontab** BUT when the job actually runs via cron nothing happens. However, running the same command manually via CLI "**sh /jffs/scripts/MerlinAU.sh run_now**" works fine, so something in the cron mechanism appears to fail when calling the script.

Is my understanding correct?
ATM, I don't see what could be causing that. If all the pieces are in place and "all the ducks are in a row" (so to speak) the call to the script should work unless there's a syntax error somewhere.

**Comment by Martinski4GitHub** [comment]
> @Martinski4GitHub
> 
> Just realized for me the script doesn't seem to run as a Cron job anymore :( I don't know when that started happening.
> 
> If I run other scripts in the jffs/scripts folder as crons they work normally. And our script works if I manually run this command: sh /./jffs/scripts/MerlinAU.sh run_now
> 
> But that command as a cron job seems to do nothing for me. I adjusted the cron to be every 1 minute and I have an update available and it still is doing nothing, while the other script I have to ping google every mintue is working fine on the same cron schedule.
>
OK, on a hunch I put a log message before and after the code that prevents running the script multiple times simultaneously, and that's where it fails because it gets 2 processes running when called from crontab. So I know what the problem is and I'm working on a fix. Good catch, buddy!!!

**Comment by ExtremeFiretop** [comment]
> > @Martinski4GitHub
> > Just realized for me the script doesn't seem to run as a Cron job anymore :( I don't know when that started happening.
> > If I run other scripts in the jffs/scripts folder as crons they work normally. And our script works if I manually run this command: sh /./jffs/scripts/MerlinAU.sh run_now
> > But that command as a cron job seems to do nothing for me. I adjusted the cron to be every 1 minute and I have an update available and it still is doing nothing, while the other script I have to ping google every mintue is working fine on the same cron schedule.
> 
> OK, on a hunch I put a log message before and after the code that prevents running the script multiple times simultaneously, and that's where it fails because it gets 2 processes running when called from crontab. So I know what the problem is and I'm working on a fix. Good catch, buddy!!!

No, whats a good catch is how you just freaking knew that on a whim/hunch!!! Like wth?!?! No testing? No troubleshooting?
I was chasing a syntax error for probably an hour until I said "it's christmas, it's late, I'm off to bed and will troubleshoot more tomorrow"

No need! Martins on the case that was nuts! Great catch Martin!

**Comment by Martinski4GitHub** [comment]
>
> No, whats a good catch is how you just freaking knew that on a whim/hunch!!! Like wth?!?! No testing? No troubleshooting? I was chasing a syntax error for probably an hour last night before bed, (I assumed the same thing you initially did) until I said "it's christmas, it's late, I'm off to bed and will troubleshoot more tomorrow"
> 
> No need! Martins on the case! Hahaha. I just woke up and that was nuts! Looked to me like you just took that out of the air. Great catch Martin!
>
Sometimes, your intuition (based on accummulated knowledge/experience) points you in the right direction and you just get lucky!! :>)

**Pull request merged**
