### PR TITLE
Dev 1.2.0 As Next Stable Release

### PR DESCRIPTION
**Pull request by ExtremeFiretop**
MerlinAU Version 1.2.0 released.

What's Changed/Fixed?:

PR: [#226 ](https://github.com/ExtremeFiretop/MerlinAutoUpdate-Router/pull/226) - Changes to support new "3006.102.X" F/W versions  (Thanks [@Martinski4GitHub](https://github.com/Martinski4GitHub))!

Some initial changes to support upcoming "3006.102.X" F/W versions.

-Modified code to use the corresponding NVRAM variable: "led_disable" (old F/W) or "AllLED" (new F/W).
-Modified code to get the corresponding filename & URL for the F/W Changelog.
-Modified code to always get the long F/W version string so that we make correct numerical comparisons between "3004.388.X.Y" & "3006.102.X.Y" versions.
-Code improvements to minimize some calls to NVRAM.
-Fixed bug when "F/W Changelog Check Approval" did not always change the setting to "BLOCK" in a scenario where the user was eager to update, and would run MerlinAU before it's nightly check.

Significant screenshots:

Behind the scene changes

### CODE REVIEW

**Comment by ExtremeFiretop** [comment]
@Martinski4GitHub 

Ready for you when you are :)
Enabled auto-merge on my part once you approve, the post is ready for the forums.

Your move! :D

**Comment by Martinski4GitHub** [comment]
> @Martinski4GitHub
> 
> Ready for you when you are :) Enabled auto-merge on my part once you approve, the post is ready for the forums.
> 
> Your move! :D
>
Give me about 15 minutes to complete my testing & verification - just to be sure.

**Comment by ExtremeFiretop** [comment]
> > @Martinski4GitHub
> > Ready for you when you are :) Enabled auto-merge on my part once you approve, the post is ready for the forums.
> > Your move! :D
> 
> Give me about 15 minutes to complete my testing & verification - just to be sure.

No worries, no rush but I figured I'd give you the switch this time since this was a Martinski special. Hehe

I ran it on my router and I couldn't find any issues, but I didn't dig too deeply. I let it run until it was ready to update when cancelled at the last run.

I did of course confirm the primary changes (as mentioned in your PR)

**Review by Martinski4GitHub — APPROVED** [review]
Good to go.

**Pull request merged**
