### PR TITLE
Update MerlinAU.sh

### PR DESCRIPTION
**Pull request by Martinski4GitHub**
Some very minor changes to email messages to keep consistent wording & formatting.
More changes coming up after this.

### CODE REVIEW

**Review by ExtremeFiretop — APPROVED** [review]

**Comment by ExtremeFiretop** [comment]
Ah, yes I like this.

**Comment by ExtremeFiretop** [comment]
Ha, I was just reviewing the conflicts and you did it all for me. <3

**Comment by Martinski4GitHub** [comment]
> Ha, I was just reviewing the conflicts and you did it all for me. <3
>
Yeah, this is the first time I had conflicts, but they were easy to resolve. I also just merged my changes as well since they were simple, and to make sure there were no more conflicts and to put everything in sync before the next PR I'll be submitting.

**Comment by ExtremeFiretop** [comment]
> > Ha, I was just reviewing the conflicts and you did it all for me. <3
> 
> Yeah, this is the first time I had conflicts, but they were easy to resolve. I also just merged my changes as well since they were simple, and to make sure there were no more conflicts and to put everything in sync before the next PR I'll be submitting.

I feel we are generally pretty good on the conflict part so no worries haha!

Did you see my message on the forums to stop running services? I noticed we would need to exclude MerlinAU from that loop probably.

**Comment by Martinski4GitHub** [comment]
> > > Ha, I was just reviewing the conflicts and you did it all for me. <3
> > 
> > 
> > Yeah, this is the first time I had conflicts, but they were easy to resolve. I also just merged my changes as well since they were simple, and to make sure there were no more conflicts and to put everything in sync before the next PR I'll be submitting.
> 
> I feel we are generally pretty good on the conflict part so no worries haha!
> 
I just had the same conflicts when I updated my personal fork repository. For some reason, the merge algorithm couldn't quite reconcile the differences. They were subtle, but not something we have not done in the past. Very odd.

>
> Did you see my message on the forums to stop running services? I noticed we would need to exclude MerlinAU from that loop probably.
>
Our script doesn't run as a service, at least not in the way that is normally thought of. Services are either started directly by the OS, or via the Entware API. We don't fall into either category, unlike other add-ons. So by stopping all Entware services with the new code, it should take care of all add-ons that are run as a "service" via Entware. I don't think we need to do anything else. IOW, I don't think we should start killing other add-ons that are not services.

**Comment by ExtremeFiretop** [comment]
> > > > Ha, I was just reviewing the conflicts and you did it all for me. <3
> > > 
> > > 
> > > Yeah, this is the first time I had conflicts, but they were easy to resolve. I also just merged my changes as well since they were simple, and to make sure there were no more conflicts and to put everything in sync before the next PR I'll be submitting.
> > 
> > 
> > I feel we are generally pretty good on the conflict part so no worries haha!
> 
> I just had the same conflicts when I updated my personal fork repository. For some reason, the merge algorithm couldn't quite reconcile the differences. They were subtle, but not something we have not done in the past. Very odd.
> 
> > Did you see my message on the forums to stop running services? I noticed we would need to exclude MerlinAU from that loop probably.
> 
> Our script doesn't run as a service, at least not in the way that is normally thought of. Services are either started directly by the OS, or via the Entware API. We don't fall into either category, unlike other add-ons. So by stopping all Entware services with the new code, it should take care of all add-ons that are run as a "service" via Entware. I don't think we need to do anything else. IOW, I don't think we should start killing other add-ons that are not services.

So basically we stop not over-reach is what your saying, if it's a service with entware it with stop when we stop entware, otherwise lets not overeach and let the system do the rest on shutdown?

**Comment by ExtremeFiretop** [comment]
> > > > Ha, I was just reviewing the conflicts and you did it all for me. <3
> > > 
> > > 
> > > Yeah, this is the first time I had conflicts, but they were easy to resolve. I also just merged my changes as well since they were simple, and to make sure there were no more conflicts and to put everything in sync before the next PR I'll be submitting.
> > 
> > 
> > I feel we are generally pretty good on the conflict part so no worries haha!
> 
> I just had the same conflicts when I updated my personal fork repository. For some reason, the merge algorithm couldn't quite reconcile the differences. They were subtle, but not something we have not done in the past. Very odd.
> 
> > Did you see my message on the forums to stop running services? I noticed we would need to exclude MerlinAU from that loop probably.
> 
> Our script doesn't run as a service, at least not in the way that is normally thought of. Services are either started directly by the OS, or via the Entware API. We don't fall into either category, unlike other add-ons. So by stopping all Entware services with the new code, it should take care of all add-ons that are run as a "service" via Entware. I don't think we need to do anything else. IOW, I don't think we should start killing other add-ons that are not services.

About to downgrade the router to a beta to test the changes, BRB ;)

**Comment by Martinski4GitHub** [comment]
> > Our script doesn't run as a service, at least not in the way that is normally thought of. Services are either started directly by the OS, or via the Entware API. We don't fall into either category, unlike other add-ons. So by stopping all Entware services with the new code, it should take care of all add-ons that are run as a "service" via Entware. I don't think we need to do anything else. IOW, I don't think we should start killing other add-ons that are not services.
> 
> So basically we don't over-reach is what your saying, if it's a service with entware it with stop when we stop entware, otherwise lets not overeach and let the system do the rest on shutdown?
>
Yes, that's my thinking at his point. I could be wrong but I don't foresee problems with add-ons that are not services.

**Pull request merged**
