### PR TITLE
Dev 1.3.2 as Next Stable Release

### PR DESCRIPTION
**Pull request by ExtremeFiretop**
Dev 1.3.2 as Next Stable Release

What's Changed/Fixed?:

PR: [ [#311 ](https://github.com/ExtremeFiretop/MerlinAutoUpdate-Router/pull/311)]
Code Improvements. Various code improvements & fine-tuning when it comes to messaging.
(Thanks [@Martinski4GitHub](https://github.com/Martinski4GitHub) [@Martinski](https://www.snbforums.com/members/69996/))

As always, we highly recommend you update ASAP as this includes lots of functional improvements and little bug fixes.

### CODE REVIEW

**Comment by ExtremeFiretop** [comment]
@Martinski4GitHub 

Not sure if you want to add anything else, I know it's not much but I rather send it out before I forget and it's so small.
Also want to double check that the latest changes I made for the workflow now function correctly.

Auto-merge is enabled once approved on your side I believe.

**Comment by Martinski4GitHub** [comment]
> @Martinski4GitHub
> 
> Not sure if you want to add anything else, I know it's not much but I rather send it out before I forget and it's so small. Also want to double check that the latest changes I made for the workflow now function correctly.
> 
> Auto-merge is enabled once approved on your side I believe.
>
>
I have nothing else to add at this point. It looks like the **3006.102.2** version will be out fairly soon so this is a good time to get the "latest & greatest" out into the field 😉.

BTW, I just realized that it's already been a year since I started contributing to this project. It was around the beginning of Oct-2023 that I made my 1st PR. Time has really flown by really fast!!

I'll approve right now & hopefully, things will run smoothly now.

**Review by Martinski4GitHub — APPROVED** [review]
Approved!!!

**Comment by ExtremeFiretop** [comment]
> > @Martinski4GitHub
> > Not sure if you want to add anything else, I know it's not much but I rather send it out before I forget and it's so small. Also want to double check that the latest changes I made for the workflow now function correctly.
> > Auto-merge is enabled once approved on your side I believe.
> 
> I have nothing else to add at this point. It looks like the **3006.102.2** version will be out fairly soon so this is a good time to get the "latest & greatest" out into the field 😉.
> 

Agreed!

> BTW, I just realized that it's already been a year since I started contributing to this project. It was around the beginning of Oct-2023 that I made my 1st PR. Time has really flown by really fast!!
> 

I was just thinking the same thing last week! I think I ever mentioned it to my girlfriend how time flies and this project has grown more than I could ever imagen over the last year! (With your help of course!) Plex is always around as a reward if you so choose ;)

> I'll approve right now & hopefully, things will run smoothly now.

ANDDD IT DID NOT. LOL.
```
Run git push origin main
remote: error: GH006: Protected branch update failed for refs/heads/main.        
remote: 
remote: - Changes must be made through a pull request.        
remote: 
remote: - Required status check "check-branches" is expected.        
To https://github.com/ExtremeFiretop/MerlinAutoUpdate-Router
 ! [remote rejected] main -> main (protected branch hook declined)
error: failed to push some refs to 'https://github.com/ExtremeFiretop/MerlinAutoUpdate-Router'
Error: Process completed with exit code 1.
```

I manually updated it now, I'll have to maybe change the protection rules?

**Comment by Martinski4GitHub** [comment]
> > > @Martinski4GitHub
> > > Not sure if you want to add anything else, I know it's not much but I rather send it out before I forget and it's so small. Also want to double check that the latest changes I made for the workflow now function correctly.
> > > Auto-merge is enabled once approved on your side I believe.
> > 
> > 
> > I have nothing else to add at this point. It looks like the **3006.102.2** version will be out fairly soon so this is a good time to get the "latest & greatest" out into the field 😉.
> 
> Agreed!
> 
> > BTW, I just realized that it's already been a year since I started contributing to this project. It was around the beginning of Oct-2023 that I made my 1st PR. Time has really flown by really fast!!
> 
> I was just thinking the same thing last week! I think I ever mentioned it to my girlfriend how time flies and this project has grown more than I could ever imagen over the last year! (With your help of course!) Plex is always around as a reward if you so choose ;)
> 
> > I'll approve right now & hopefully, things will run smoothly now.
> 
> ANDDD IT DID NOT. LOL.
> 
> ```
> Run git push origin main
> remote: error: GH006: Protected branch update failed for refs/heads/main.        
> remote: 
> remote: - Changes must be made through a pull request.        
> remote: 
> remote: - Required status check "check-branches" is expected.        
> To https://github.com/ExtremeFiretop/MerlinAutoUpdate-Router
>  ! [remote rejected] main -> main (protected branch hook declined)
> error: failed to push some refs to 'https://github.com/ExtremeFiretop/MerlinAutoUpdate-Router'
> Error: Process completed with exit code 1.
> ```
>
>
Yeah, I noticed that the **version.txt** & **README.md** files were not updated automatically with the version string.

>
> 
> I manually updated it now, I'll have to maybe change the protection rules?
>
>
Sounds good.

**Comment by ExtremeFiretop** [comment]
> > I manually updated it now, I'll have to maybe change the protection rules?
> 
> Sounds good.

I actually noticed I don't want to disable branch protection lol, that would completely null and void the entire workflow we have that works...
Hmm. Will keep digging.

**Comment by Martinski4GitHub** [comment]
> > > I manually updated it now, I'll have to maybe change the protection rules?
> > 
> > 
> > Sounds good.
> 
> I actually noticed I don't want to disable branch protection lol, that would completely null and void the entire workflow we have that works... Hmm. Will keep digging.
>
>
OK, yeah, that makes sense. As the saying goes: "There's  a method to the madness."  Shovel away!! 😉

**Comment by ExtremeFiretop** [comment]
There has to be a way to authorize the action bot to be able to push directly to the branch right?

It would feel nuts to me that I'd have to have the action bot do the same steps of opening a PR in dev to make these changes lol.

**Comment by Martinski4GitHub** [comment]
> There has to be a way to authorize the action bot to be able to push directly to the branch right?
> 
> It would feel nuts to me that I'd have to have the action bot do the same steps of opening a PR in dev to make these changes lol.
>
>
I would think so in order to automate updates to specific files, especially if the update is coming from the repo owner or someone who has write access & privileges.

Is there a way to allow "direct" edit/write access to only some specific files (e.g. version.txt) within the protection rules?

If not, perhaps GitHub may simply require all "file writes" to have an associated Pull Request for record-keeping purposes and accountability. That way there's always a record of who did what & when to what file.

**Comment by ExtremeFiretop** [comment]
> > There has to be a way to authorize the action bot to be able to push directly to the branch right?
> 
> I would think so in order to automate updates to specific files, especially if the update is coming from the repo owner or someone who has write access & privileges.
> 
> > It would feel nuts to me that I'd have to have the action bot do the same steps of opening a PR in dev to make these changes lol.
> 
> Is there a way to allow "direct" edit/write access to only some specific files (e.g. version.txt) within the protection rules?
> 
> If not, perhaps GitHub may simply require all "file writes" to have an associated Pull Request for record-keeping purposes and accountability. That way there's always a record of who did what & when to what file.

I made some changes.

1. Allowed you and me to force push directly to the main branch:
image
2. I setup a PAT token (Personal access tokens) here: https://github.com/settings/tokens 
3. I gave setup the PAT token as a Secret for Github actions called: **PAT_TOKEN**
4. I adjusted the workflow in dev to use the new *PAT_TOKEN* in commit: https://github.com/ExtremeFiretop/MerlinAutoUpdate-Router/commit/789117552c5bf56751331ed4f1508a87a8baf1f2

Now we test? Maybe I can quickly switch the branch or version in main for a quick second and then re-run the workflow?

**Comment by ExtremeFiretop** [comment]
I used this as my guide: https://stackoverflow.com/questions/76267018/how-can-i-protect-a-github-branch-and-allow-only-github-actions-to-push-to-it-an

**Comment by Martinski4GitHub** [comment]
> > > There has to be a way to authorize the action bot to be able to push directly to the branch right?
> > 
> > 
> > I would think so in order to automate updates to specific files, especially if the update is coming from the repo owner or someone who has write access & privileges.
> > > It would feel nuts to me that I'd have to have the action bot do the same steps of opening a PR in dev to make these changes lol.
> > 
> > 
> > Is there a way to allow "direct" edit/write access to only some specific files (e.g. version.txt) within the protection rules?
> > If not, perhaps GitHub may simply require all "file writes" to have an associated Pull Request for record-keeping purposes and accountability. That way there's always a record of who did what & when to what file.
> 
> I made some changes.
> 
>     1. Allowed you and me to force push directly to the main branch:
>    ...   
> 
>     2. I setup a PAT token (Personal access tokens) here: https://github.com/settings/tokens
> 
>     3. I gave setup the PAT token as a Secret for Github actions called: **PAT_TOKEN**
> 
>     4. I adjusted the workflow in dev to use the new _PAT_TOKEN_ in commit: [7891175](https://github.com/ExtremeFiretop/MerlinAutoUpdate-Router/commit/789117552c5bf56751331ed4f1508a87a8baf1f2)
> 
> 
> Now we test? Maybe I can quickly switch the branch or version in main for a quick second and then re-run the workflow?
>
>
Very good findings, bud!! Sounds like an excellent plan. Very promising.

**Comment by ExtremeFiretop** [comment]
@Martinski4GitHub 

I've given up and just rolled back both dev and main to their original state after the latest merge.
Not sure where to go from here.

**Comment by Martinski4GitHub** [comment]
> @Martinski4GitHub
> 
> I've given up and just rolled back both dev and main to their original state after the latest merge. Not sure where to go from here.
>
>
You may need to "sleep on it" so your brain works out some of the details and makes the connections that are not immediately obvious. Oftentimes, I've come up with solutions after I've slept on the problem.

Have a good night, bud. Sleep tight :>).

**Comment by ExtremeFiretop** [comment]
> > @Martinski4GitHub
> > I've given up and just rolled back both dev and main to their original state after the latest merge. Not sure where to go from here.
> 
> You may need to "sleep on it" so your brain works out some of the details and makes the connections that are not immediately obvious. Oftentimes, I've come up with solutions after I've slept on the problem.
> 
> Have a good night, bud. Sleep tight :>).

Yeah I'm going to sleep on it, for now I just rolled it all back and deleted whatever history I can.
I removed all of tonights commit history, and rolled everything back, including all the permissions and changes to the branch protection settings. Also rolled back the workflow to a time pre-this-idea lol.

Only this thing I can't delete/remove is the closed PRs from the PR history, but all their related commits are detached and not related to any changes. 

I'm getting frustrated, between Googling and poking at every possible configuration I can think of, none of them seemed to work... I'm not sure why

**Comment by ExtremeFiretop** [comment]
@Martinski4GitHub 

I finally got it working using this method:

https://github.com/orgs/community/discussions/25305#discussioncomment-10728028

Now it finally does everything automated, I made a mess of our PRs while I was trying to test it though lol.

**Comment by ExtremeFiretop** [comment]
Here is the screenshots displaying it worked:

image

image

image

**Comment by Martinski4GitHub** [comment]
> @Martinski4GitHub
> 
> I finally got it working using this method:
> 
> https://github.com/orgs/community/discussions/25305#discussioncomment-10728028
> 
> Now it finally does everything automated, I made a mess of our PRs while I was trying to test it though lol.
>
>
Excellent, bud!!  The PR history is indeed very long now, LOL. But it's not a big deal. Only us (devs) really look at it.

**Comment by Martinski4GitHub** [comment]
> Here is the screenshots displaying it worked:
> 
>
Looking really good now!! Great job!!
Let me know if there's anything different that I need to do on my end when submitting or merging PRs.

P.S. 
My wife and I are about to visit my in-laws to check on her mother, so I'll be offline for a while. Talk to you later.

**Comment by ExtremeFiretop** [comment]
> > @Martinski4GitHub
> > I finally got it working using this method:
> > https://github.com/orgs/community/discussions/25305#discussioncomment-10728028
> > Now it finally does everything automated, I made a mess of our PRs while I was trying to test it though lol.
> 
> Excellent, bud!! The PR history is indeed very long now, LOL. But it's not a big deal. Only us (devs) really look at it.

Exactly. I realized the PR list is now a full page of me testing this over the last 2 days lol, but if you actually spend time looking at anyone's PR list that uses GitHub actions it seems everyone has points of "just gotta test it until it works" LOL. 

t's not uncommon, even on Gnuton s branch I noticed he also wrestles GitHub actions sometimes.

When it comes to the next release I'll just exclude / remove all those PRs from the release notes and it's like it never happened.

**Comment by ExtremeFiretop** [comment]
> > Here is the screenshots displaying it worked:
> 
> Looking really good now!! Great job!! Let me know if there's anything different that I need to do on my end when submitting or merging PRs.
> 

Nope! The only thing we need to worry about updating is the version.text file now! I realize we will probably still update the version ahead of time, but if we forgot it won't ;) (along with the branch string)

> P.S. My wife and I are about to visit my in-laws to check on her mother, so I'll be offline for a while. Talk to you later.

No worries! I'll be around for the next few hours, otherwise, chat tomorrow!

**Comment by Martinski4GitHub** [comment]
> > > @Martinski4GitHub
> > > I finally got it working using this method:
> > > https://github.com/orgs/community/discussions/25305#discussioncomment-10728028
> > > Now it finally does everything automated, I made a mess of our PRs while I was trying to test it though lol.
> > 
> > 
> > Excellent, bud!! The PR history is indeed very long now, LOL. But it's not a big deal. Only us (devs) really look at it.
> 
> Exactly. I realized the PR list is now a full page of me testing this over the last 2 days lol, but if you actually spend time looking at anyone's PR list that uses GitHub actions it seems everyone has points of "just gotta test it until it works" LOL.
> 
> t's not uncommon, even on Gnuton s branch I noticed he also wrestles GitHub actions sometimes.
> 
>
Yeah, I imagine a lot of projects in GitHub have the same kind of workflow requirements where, as part of issuing a production release, they would like to be able to automatically check & modify certain files as necessary for strings like versions, dates & repository branches.

>
> When it comes to the next release I'll just exclude / remove all those PRs from the release notes and it's like it never happened.
>
>
OK, sounds good.

**Comment by Martinski4GitHub** [comment]
> > > Here is the screenshots displaying it worked:
> > 
> > 
> > Looking really good now!! Great job!! Let me know if there's anything different that I need to do on my end when submitting or merging PRs.
> 
> Nope! The only thing we need to worry about updating is the version.text file now! I realize we will probably still update the version ahead of time, but if we forgot it won't ;) (along with the branch string)
> 
>
I don't quite understand what you mean in the above sentence.
What exactly is it that we need to worry about WRT the **version.txt** file?
Is it that we cannot update it manually "**_too early_**" before issuing a release?
Or, is it that we should **not** update it manually at all because if we do, it will break the logic?

**Comment by ExtremeFiretop** [comment]
> > > > Here is the screenshots displaying it worked:
> > > 
> > > 
> > > Looking really good now!! Great job!! Let me know if there's anything different that I need to do on my end when submitting or merging PRs.
> > 
> > 
> > Nope! The only thing we need to worry about updating is the version.text file now! I realize we will probably still update the version ahead of time, but if we forgot it won't ;) (along with the branch string)
> 
> I don't quite understand what you mean in the above sentence. What exactly is it that we need to worry about WRT the **version.txt** file? Is it that we cannot update it manually "**_too early_**" before issuing a release? Or, is it that we should **not** update it manually at all because if we do, it will break the logic?

It's probably getting late for you after that visit ;) it's okay! I shall explain;

I mentioned that the "only thing we need to worry about updating" is the version.txt file, so it's not that we cannot update it early, or that we don't update it at all, it's that we  need to be concerned about updating it. 

That's it. That's all we update! :D same as always.

**Comment by ExtremeFiretop** [comment]
>I realize we will probably still update the version ahead of time, but if we forgot it won't ;) (along with the branch string)
> 

Unless maybe this was the line were you confused by? If that's the case I shall explain this one just to be absolutely 120% clear. 

When I say "I realize we will probably still update the version ahead of time" I meant in the script, along with the branch string (dev/master) in the script.

If we forgot, it won't, based on the version.txt file. :)

**Comment by ExtremeFiretop** [comment]
@Martinski4GitHub 

Actually, you provoked an interesting thought, any reason why I couldn't use the same type of workflow in dev? So that when I do my reverse sync back into dev, that it automatically changes the version and branch string in the script?

We could probably even do the version.txt file that way (which is how you provoked this thought chain) lol

**Comment by Martinski4GitHub** [comment]
> > > > 
> > > > Looking really good now!! Great job!! Let me know if there's anything different that I need to do on my end when submitting or merging PRs.
> > > 
> > > 
> > > Nope! The only thing we need to worry about updating is the version.text file now! I realize we will probably still update the version ahead of time, but if we forgot it won't ;) (along with the branch string)
> > 
> > 
> > I don't quite understand what you mean in the above sentence. What exactly is it that we need to worry about WRT the **version.txt** file? Is it that we cannot update it manually "**_too early_**" before issuing a release? Or, is it that we should **not** update it manually at all because if we do, it will break the logic?
> 
> It's probably getting late for you after that visit ;) it's okay! I shall explain;
> 
> I mentioned that the "only thing we need to worry about updating" is the version.txt file, so it's not that we cannot update it early, or that we don't update it at all, it's that we need to be concerned about updating it.
> 
> That's all we update! :D same as always. That's it that's all folks! Anything else is automated.
>
>
OK, excellent!! That was my expectation but it was not crystal clear.

**Comment by ExtremeFiretop** [comment]
> > > > > Looking really good now!! Great job!! Let me know if there's anything different that I need to do on my end when submitting or merging PRs.
> > > > 
> > > > 
> > > > Nope! The only thing we need to worry about updating is the version.text file now! I realize we will probably still update the version ahead of time, but if we forgot it won't ;) (along with the branch string)
> > > 
> > > 
> > > I don't quite understand what you mean in the above sentence. What exactly is it that we need to worry about WRT the **version.txt** file? Is it that we cannot update it manually "**_too early_**" before issuing a release? Or, is it that we should **not** update it manually at all because if we do, it will break the logic?
> > 
> > 
> > It's probably getting late for you after that visit ;) it's okay! I shall explain;
> > I mentioned that the "only thing we need to worry about updating" is the version.txt file, so it's not that we cannot update it early, or that we don't update it at all, it's that we need to be concerned about updating it.
> > That's all we update! :D same as always. That's it that's all folks! Anything else is automated.
> 
> OK, excellent!! That was my expectation but it was not crystal clear.

No worries!

I realized after the fact I changed the context from talking about the version.txt file to the script file, without clarifying that, which is why I decided to clarify the second line I believe may have caused the confusion. :)

In summary though, your thoughts are correct and your also correct when you mentioned we will probably continue to update the version in the script (and in the version.txt file) but the script is technically automated

**Comment by Martinski4GitHub** [comment]
> > I realize we will probably still update the version ahead of time, but if we forgot it won't ;) (along with the branch string)
> 
> Unless maybe this was the line were you confused by? If that's the case I shall explain this one just to be absolutely 120% clear.
> 
> When I say "I realize we will probably still update the version ahead of time" I meant in the script, along with the branch string (dev/master) in the script.
> 
>
Yes, the last sentence was rather confusing, and it "muddied the waters" for the whole message. It was missing the key phrase "**_in the script_**" which you have now explained:

"I realize we will probably still update the version ***_in the script_*** ahead of time  ..."

With the key phrase added, the last sentence is now clear and the entire message makes sense.
Thanks for the clarification.

**Comment by Martinski4GitHub** [comment]
> @Martinski4GitHub
> 
> Actually, you provoked an interesting thought, any reason why I couldn't use the same type of workflow in dev? So that when I do my reverse sync back into dev, that it automatically changes the version and branch string in the script?
> 
> We could probably even do the version.txt file that way (which is how you provoked this thought chain) lol
>
>
I'd say it's up to you if you want to do the work to automate those steps for the "development" branch. IMO, I don't think it's really needed at this point since we're pretty good at making those changes ourselves as we modify or add new code during the development & testing phase.

**Comment by ExtremeFiretop** [comment]
> > @Martinski4GitHub
> > Actually, you provoked an interesting thought, any reason why I couldn't use the same type of workflow in dev? So that when I do my reverse sync back into dev, that it automatically changes the version and branch string in the script?
> > We could probably even do the version.txt file that way (which is how you provoked this thought chain) lol
> 
> I'd say it's up to you if you want to do the work to automate those steps for the "development" branch. IMO, I don't think it's really needed at this point since we're pretty good at making those changes ourselves as we modify or add new code during the development & testing phase.

Agreed. 

It was an idea I poked around for a bit, but realized I'd have to actually change the logic flow. It wouldn't be a simple "copy and paste" because to update the version in the text file is different than using it as a reference version which is what we currently do for production.

So in the end, it's more work than it's worth. Dev is our playground anyways I only wanted to update production to not mess up or forget something in production releases.

**Comment by Martinski4GitHub** [comment]
> > > @Martinski4GitHub
> > > Actually, you provoked an interesting thought, any reason why I couldn't use the same type of workflow in dev? So that when I do my reverse sync back into dev, that it automatically changes the version and branch string in the script?
> > > We could probably even do the version.txt file that way (which is how you provoked this thought chain) lol
> > 
> > 
> > I'd say it's up to you if you want to do the work to automate those steps for the "development" branch. IMO, I don't think it's really needed at this point since we're pretty good at making those changes ourselves as we modify or add new code during the development & testing phase.
> 
> Agreed.
> 
> It was an idea I poked around for a bit, but realized I'd have to actually change the logic flow. It wouldn't be a simple "copy and paste" because to update the version in the text file is different than using it as a reference version which is what we currently do for production.
> 
> So in the end, it's more work than it's worth. Dev is our playground anyways I only wanted to update production to not mess up or forget something in production releases.
>
>
Exactly!! The "**main**" branch with production releases is where everything has to be updated "just right" and be in alignment (i.e. version strings, repo branch name, all debug code disabled) so that all users can download & install the correct latest version. The "**dev**" branch is our sandbox where we can modify/add/test/play with the code as we wish with the understanding that sometimes it may not be yet fully "tested & stable."

**Pull request merged**
