### PR TITLE
Updated MerlinAU.sh

### PR DESCRIPTION
**Pull request by Martinski4GitHub**
Made a couple of changes regarding when to check that the LOG directory actually exists.

### CODE REVIEW

**Comment by ExtremeFiretop** [comment]
Looks good to me!

**Comment by Martinski4GitHub** [comment]
> Looks good to me!
Just submitted changes to the wait times as discussed (3min + 3min).

**Comment by Martinski4GitHub** [comment]
> > Looks good to me!
> 
Just submitted changes to the wait times as discussed (3min + 3min).

**Comment by ExtremeFiretop** [comment]
Merged!

**Comment by Martinski4GitHub** [comment]
> Merged!
>
It was very good timing that all these issues were caught before the Main version release had more exposure as it was. All these recent changes make the solution more robust, IMO.

Happy Holidays, buddy!!!
(Hopefully, no more "surprises" until next year - not that I don't enjoy this kind of collaborative efforts)

**Comment by ExtremeFiretop** [comment]
> > Merged!
> 
> It was very good timing that all these issues were caught before the Main version release had more exposure as it was. All these recent changes make the solution much more robust, IMO.
> 
> Happy Holidays, buddy!!! (Hopefully, no more "surprises" until next year - not that I don't enjoy this kind of collaborative efforts)

I'll promote to production once I test it fully in the morning! Happy holidays buddy, job well done as always. This makes me verrrryyy happy hahaha

**Comment by Martinski4GitHub** [comment]
> > > Merged!
> > 
> > 
> > It was very good timing that all these issues were caught before the Main version release had more exposure as it was. All these recent changes make the solution much more robust, IMO.
> > Happy Holidays, buddy!!! (Hopefully, no more "surprises" until next year - not that I don't enjoy this kind of collaborative efforts)
> 
> I'll promote to production once I test it fully in the morning! 
> 
Absolutely. The "Trust But Verify" philosophy is a sign of an experienced developer.

>
> Happy holidays buddy, job well done as always. 
>
Right back at you!!  Here's a "¡Salud!" to you and your family.

>
> This makes me verrrryyy happy hahaha
>
You and me both!!

**Comment by ExtremeFiretop** [comment]
Just wanted to mention that this has been successfully tested. I would of merged it into production but I figured let's talk out the LED situation of your latest PR first

**Pull request merged**
