### PR TITLE
Minor UI Improvement

### PR DESCRIPTION
**Pull request by Martinski4GitHub**
Added a user-friendly/human-readable schedule line below the "F/W Update Cron Schedule" menu option.

Example screenshot:
MerlinAU_v1 3 9_CronSchedule

### CODE REVIEW

**Comment by Martinski4GitHub** [comment]
@ExtremeFiretop,

My cousin, who is not a Linux user at all (purely a Windows user), suggested having a more user-friendly & human-readable line below the cron schedule so that users like him can very easily read what the cron schedule syntax means without having to go through the menu option to "edit" the entry. Since I agree and it was pretty simple to add, I just did it.

Please take a look whenever you get a chance. Nothing urgent - just a nice, cosmetic touch, IMO.

**Comment by ExtremeFiretop** [comment]
> @ExtremeFiretop,
> 
> My cousin, who is not a Linux user at all (purely a Windows user), suggested having a more user-friendly & human-readable line below the cron schedule so that users like him can very easily read what the cron schedule syntax means without having to go through the menu option to "edit" the entry. Since I agree and it was pretty simple to add, I just did it.
> 
> Please take a look whenever you get a chance. Nothing urgent - just a nice, cosmetic touch, IMO.

Love the suggestion! Pass my thanks!

**Review by ExtremeFiretop — APPROVED** [review]

**Comment by TheS1R** [comment]
Suggestion: Can this also be applied below the "Toggle Auto-Updates for MerlinAU Script" menu option if enabled?

**Comment by ExtremeFiretop** [comment]
> Suggestion: Can this also be applied below the "Toggle Auto-Updates for MerlinAU Script" menu option if enabled?

That's a great idea Tom! I'm not sure if Martinski wants to run with it or not, I know he's busy, I might take it and run with it unless he replies today sometime :)

**Comment by ExtremeFiretop** [comment]
> Suggestion: Can this also be applied below the "Toggle Auto-Updates for MerlinAU Script" menu option if enabled?

Were you thinking something like this?

image

**Comment by TheS1R** [comment]
Yes, exactly!

**Comment by Martinski4GitHub** [comment]
> > Suggestion: Can this also be applied below the "Toggle Auto-Updates for MerlinAU Script" menu option if enabled?
> 
> Were you thinking something like this?
> 
>
I was thinking more like this *without* the ENABLED line.

MerlinAU_ScriptAutoUpdateSchedule

The default setting is DISABLED but once it's ENABLED by the user, it becomes just 2 lines (like the other cron schedule for F/W Updates) - simpler and less crowded. I just submitted PR #376 for this change.

My 2 cents.

**Comment by ExtremeFiretop** [comment]
> > > Suggestion: Can this also be applied below the "Toggle Auto-Updates for MerlinAU Script" menu option if enabled?
> > 
> > 
> > Were you thinking something like this?
> 
> I was thinking more like this _without_ the ENABLED line.
> 
> MerlinAU_ScriptAutoUpdateSchedule
> 
> The default setting is DISABLED but once it's ENABLED by the user, it becomes just 2 lines (like the other cron schedule for F/W Updates) - simpler and less crowded. I just submitted PR #376 for this change.
> 
> My 2 cents.

I'm actually quite indifferent, it does make it look a bit long when I look at it now, but I do like the clear indicator it's enabled.

I'll merge it in and see what @TheS1R thinks!
It's only dev after all ;)

**Comment by Martinski4GitHub** [comment]
> > > > Suggestion: Can this also be applied below the "Toggle Auto-Updates for MerlinAU Script" menu option if enabled?
> > > 
> > > 
> > > Were you thinking something like this?
> > 
> > 
> > I was thinking more like this _without_ the ENABLED line.
>> ...
> > The default setting is DISABLED but once it's ENABLED by the user, it becomes just 2 lines (like the other cron schedule for F/W Updates) - simpler and less crowded. I just submitted PR #376 for this change.
> > My 2 cents.
> 
> I'm actually quite indifferent, it does make it look a bit long when I look at it now, but I do like the clear indicator it's enabled.
> 
> I'll merge it in and see what @TheS1R thinks! It's only dev after all ;)
>
With the ENABLED line included, the menu option becomes 4 lines in total which violates one of my company's design principles for menu design. It's just too busy at 4 lines - even having 3 lines is already pushing it, but it improves the "user experience."

Just my 2 cents.

**Comment by TheS1R** [comment]
> > > > > Suggestion: Can this also be applied below the "Toggle Auto-Updates for MerlinAU Script" menu option if enabled?
> > > > 
> > > > 
> > > > Were you thinking something like this?
> > > 
> > > 
> > > I was thinking more like this _without_ the ENABLED line.
> > > ...
> > > The default setting is DISABLED but once it's ENABLED by the user, it becomes just 2 lines (like the other cron schedule for F/W Updates) - simpler and less crowded. I just submitted PR #376 for this change.
> > > My 2 cents.
> > 
> > 
> > I'm actually quite indifferent, it does make it look a bit long when I look at it now, but I do like the clear indicator it's enabled.
> > I'll merge it in and see what @TheS1R thinks! It's only dev after all ;)
> 
> With the ENABLED line included, the menu option becomes 4 lines in total which violates one of my company's design principles for menu design. It's just "too busy & crowded" at 4 lines - even having 3 lines is already pushing it, but it improves the "user experience."
> 
> Just my 2 cents.

I agree, especially since I often access **amtm** from mobile phone.

**Comment by ExtremeFiretop** [comment]
Done deal!

Thanks guys @TheS1R and @Martinski4GitHub 

The new look is how it stays ;) happy to know we addressed your suggestions @TheS1R !!

**Pull request merged**
