### PR TITLE
Update MerlinAU.sh

### PR DESCRIPTION
**Pull request by Martinski4GitHub**
Added code to run a check & see if a new F/W update is available. This is done ***ONLY*** if the user has enabled F/W Update Checks; otherwise, we have to respect the user's selection not to check.

### CODE REVIEW

**Comment by ExtremeFiretop** [comment]
Crap. I merged directly to the branch instead of making a new one..

Well look at this, while I roll back lol!: https://github.com/ExtremeFiretop/MerlinAutoUpdate-Router/commit/af3bd4ce5538be25c919d3f47468a9d1aff7f53a

**Comment by ExtremeFiretop** [comment]
Okay. Sorry about that, rolled back the changes to dev, let me make a new branch this time lol!

**Comment by ExtremeFiretop** [comment]
Made a new branch and PR so we can compare properly.

**Comment by ExtremeFiretop** [comment]
Okay so I see, you just threw it in the cron check at the start of the script. While I specifically put it past the disabled check of the run now function.

Difference is yours would run at the start of the script everytime if the update is enabled, while mine would only run if the update is enabled and the user selects to check for updates, not at the start of every script run.

I wanted this to be interactive only since if it was a cron job I would let it rely on the automatic watchdog at 2AM.
However reviewing your suggestion, I kinda like the idea of checking everytime our script runs, basically you end up with having the watchdog that checks at 2AM every morning, and our check which checks whenever the cron is run as configured by the user.

Any thoughts?

**Comment by Martinski4GitHub** [comment]
> Okay so I see, you just threw it in the cron check at the start of the script. While I specifically put it past the disabled check of the run now function.
> 
> Difference is yours would run at the start of the script everytime if the update is enabled, while mine would only run if the update is enabled and the user selects to check for updates, not at the start of every script run.
> 
> I wanted this to be interactive only since if it was a cron job I would let it rely on the automatic watchdog at 2AM. However reviewing your suggestion, I kinda like the idea of checking everytime our script runs, basically you end up with having the watchdog that checks at 2AM every morning, and our check which checks whenever the cron is run. ( as configured by the user.), lets say 12AM by default)
> 
> Any thoughts?
>
Yeah, I put the call at the start of the script to run every time because I thought that it wouldn't hurt to do it based on when the script runs (i.e. manual run or based on the cron schedule) since the user has control over that versus the F/W schedule that runs around 2am.  This way, if there's a new F/W Update the day before, the user doesn't have to wait until the following morning at 2am; instead during a manual run or the the cron job running at, say, 12am would catch thee new F/W version available.

P.S. Just updated PR #77 with an improvement to make sure we honor the user's selection.

**Comment by ExtremeFiretop** [comment]
> > Okay so I see, you just threw it in the cron check at the start of the script. While I specifically put it past the disabled check of the run now function.
> > Difference is yours would run at the start of the script everytime if the update is enabled, while mine would only run if the update is enabled and the user selects to check for updates, not at the start of every script run.
> > I wanted this to be interactive only since if it was a cron job I would let it rely on the automatic watchdog at 2AM. However reviewing your suggestion, I kinda like the idea of checking everytime our script runs, basically you end up with having the watchdog that checks at 2AM every morning, and our check which checks whenever the cron is run. ( as configured by the user.), lets say 12AM by default)
> > Any thoughts?
> 
> Yeah, I put the call at the start of the script to run every time because I thought that it wouldn't hurt to do it based on when the script runs (i.e. manual run or based on the cron schedule) since the user has control over that versus the F/W schedule that runs around 2am. This way, if there's a new F/W Update the day before, the user doesn't have to wait until the following morning at 2am; instead during a manual run or the the cron job running at, say, 12am would catch the new F/W version available.
> 
> P.S. Just updated PR #77 with an improvement to make sure we honor the user's selection.

Agreed.

I like the idea of kinda "adding" a update check the user has control over, since the 2am watchdog the user cannot control.

What I was doing was kinda trying to "play nice" side by side with the 2am watchdog. But this is more control by adding an additional watchdog the user controls .

For an update script that's a better implementation. I'll merge yours in now and adjust my PR.

**Pull request merged**
