### PR TITLE
Update MerlinAU.sh

### PR DESCRIPTION
**Pull request by ExtremeFiretop**
Allow Pre-approval of the Changelog check

### CODE REVIEW

**Comment by ExtremeFiretop** [comment]
@Martinski4GitHub 

This seems to work, let me know what you think of this type of solution?
I decided to try moving the uninstall to the advanced options with this solution.

**Comment by Martinski4GitHub** [comment]
> @Martinski4GitHub
> 
> This seems to work, let me know what you think of this type of solution? I decided to try moving the uninstall to the advanced options with this solution.
>
The overall solution looks good, but I have 2 suggestions:

1) I think the new menu option should be listed in the "**Advanced Options Menu**" below the "**Toggle Changelog Check**" selection. IMO, this new feature fits better under that sub-menu since both are related to the release changelog, so when the "**Changelog Check**" is **ENABLED** or **DISABLED**, the user can see the effect on the new "Approved/Blocked" feature right away.

2) The titles for the new menu option are not consistent:

```
ap)  Pre-approve F/W Update Changelog
     [Currently BLOCKED]
```

```
ap)  Approve Update Changelog
     [Currently APPROVED]
```

I think the wording should be more consistent, perhaps something like this:

```
ap)  Approve F/W Update after Changelog Check
     [Currently BLOCKED]
```

```
ap)  Block F/W Update due to Changelog Check
     [Currently APPROVED]
```

Or you could just set it as a simple toggle:

```
ap)  Toggle F/W Update after Changelog Check
     [Currently APPROVED/BLOCKED]
```

My 2 cents.

**Comment by ExtremeFiretop** [comment]
> > @Martinski4GitHub
> > This seems to work, let me know what you think of this type of solution? I decided to try moving the uninstall to the advanced options with this solution.
> 
> The overall solution looks good, but I have 2 suggestions:
> 
> 1. I think the new menu option should be listed in the "**Advanced Options Menu**" below the "**Toggle Changelog Check**" selection. IMO, this new feature fits better under that sub-menu since both are related to the release changelog, so when the "**Changelog Check**" is **ENABLED** or **DISABLED**, the user can see the effect on the new "Approved/Blocked" feature right away.
> 2. The titles for the new menu option are not consistent:
> 
> ```
> ap)  Pre-approve F/W Update Changelog
>      [Currently BLOCKED]
> ```
> 
> ```
> ap)  Approve Update Changelog
>      [Currently APPROVED]
> ```
> 
> I think the wording should be more consistent, perhaps something like this:
> 
> ```
> ap)  Approve F/W Update after Changelog Check
>      [Currently BLOCKED]
> ```
> 
> ```
> ap)  Block F/W Update due to Changelog Check
>      [Currently APPROVED]
> ```
> 
> Or you could just set it as a simple toggle:
> 
> ```
> ap)  Toggle F/W Update after Changelog Check
>      [Currently APPROVED/BLOCKED]
> ```
> 
> My 2 cents.

I've made the quick typo fix for suggestion 2, but I'm not sure how I feel about suggestion 1.
The advanced menu is for things that are "advanced" and we want "hidden away".

This is a feature that will be used by probably 'most' people not a select few, and should be front and centre on the main menu, I don't want users digging through menus to try and find an approve an update if that makes sense? lol

I understand it may feel like it fits better under the Changelog Check but that would mean hiding an important switch, I think we should be thinking about the users experience over what looks nicest in this regard :)

Unless you have ideas to address my concern? 
Maybe add a warning at the top like when an update is available? Or maybe just move both options out of the Advanced options and have both the Changelog Check and the approval in the main menu?

**Comment by ExtremeFiretop** [comment]
> > @Martinski4GitHub
> > This seems to work, let me know what you think of this type of solution? I decided to try moving the uninstall to the advanced options with this solution.
> 
> The overall solution looks good, but I have 2 suggestions:
> 
> 1. I think the new menu option should be listed in the "**Advanced Options Menu**" below the "**Toggle Changelog Check**" selection. IMO, this new feature fits better under that sub-menu since both are related to the release changelog, so when the "**Changelog Check**" is **ENABLED** or **DISABLED**, the user can see the effect on the new "Approved/Blocked" feature right away.
> 2. The titles for the new menu option are not consistent:
> 
> ```
> ap)  Pre-approve F/W Update Changelog
>      [Currently BLOCKED]
> ```
> 
> ```
> ap)  Approve Update Changelog
>      [Currently APPROVED]
> ```
> 
> I think the wording should be more consistent, perhaps something like this:
> 
> ```
> ap)  Approve F/W Update after Changelog Check
>      [Currently BLOCKED]
> ```
> 
> ```
> ap)  Block F/W Update due to Changelog Check
>      [Currently APPROVED]
> ```
> 
> Or you could just set it as a simple toggle:
> 
> ```
> ap)  Toggle F/W Update after Changelog Check
>      [Currently APPROVED/BLOCKED]
> ```
> 
> My 2 cents.

Also keep in mind with the current implementation it only shows on the main menu "if" there's a high risk phrase found. If there isn't it isn't visible at all.

Maybe if I made it visible all the time it would make more sense under the advanced options?

**Comment by ExtremeFiretop** [comment]
@Martinski4GitHub 

Refactored the code so it wasn't so duplicating.

**Comment by Martinski4GitHub** [comment]
> > 
> > 1. I think the new menu option should be listed in the "**Advanced Options Menu**" below the "**Toggle Changelog Check**" selection. IMO, this new feature fits better under that sub-menu since both are related to the release changelog, so when the "**Changelog Check**" is **ENABLED** or **DISABLED**, the user can see the effect on the new "Approved/Blocked" feature right away.
>>
>> ...
> 
> .... The advanced menu is for things that are "advanced" and we want "hidden away".
> 
>
Well, that's a surprising viewpoint. I've never used secondary menus as a way to "hide away" menu options. Sub-menus become necessary when the top Main Menu is already too "crowded" or too "busy" with enough options. The standard guidelines can vary based on several factors (e.g. WebGUI vs text-based UI), but normally you don't want to present more than 8 to 10 items in one single menu level, so once you reach the threshold, you split the top options into sub-categories that group items together which have related functionality, serve similar purpose, touch on related features. But again, sub-menus are never meant to be a method to have items "hidden away."

>
> This is a feature that will be used by probably 'most' people on many future updates, not a select few only once, and should be front and centre on the main menu, I don't want users digging through menus to try and find and approve an changelog check if that makes sense? lol
> 
>
Currently, we essentially have a 2-level menu structure, with only 2 sub-menus so "digging through menus" is not how I would qualify the current menu navigation & user experience; but I certainly understand that some menu options should be more "readily available" than others - after all, findability, accessibility & usability are very important aspects of a good menu design.

>
> I understand it may feel like it fits better under the Changelog Check but that would mean hiding an important switch, I think we should be thinking about the users experience over what looks nicest in this regard :)
> 
> Unless you have ideas to address my concern? Maybe add a warning at the top like when an update is available? Or maybe just move both options out of the Advanced options and have both the Changelog Check and the approval in the main menu?
>
Yes, I think that moving the two related options to the Main Menu would work well in this case because the setting of one clearly affects the other.

My 2 cents.

**Comment by Martinski4GitHub** [comment]
> @Martinski4GitHub
> 
> Refactored the code so it wasn't so duplicating.
>
Very good call. I like it!!

**Comment by ExtremeFiretop** [comment]
> > > 1. I think the new menu option should be listed in the "**Advanced Options Menu**" below the "**Toggle Changelog Check**" selection. IMO, this new feature fits better under that sub-menu since both are related to the release changelog, so when the "**Changelog Check**" is **ENABLED** or **DISABLED**, the user can see the effect on the new "Approved/Blocked" feature right away.
> > > 
> > > ...
> > 
> > 
> > .... The advanced menu is for things that are "advanced" and we want "hidden away".
> 
> Well, that's a surprising viewpoint. I've never used secondary menus as a way to "hide away" menu options. Sub-menus become necessary when the top Main Menu is already too "crowded" or too "busy" with enough options. The standard guidelines can vary based on several factors (e.g. WebGUI vs text-based UI), but normally you don't want to present more than 8 to 10 items in one single menu level, so once you reach the threshold, you split the top options into sub-categories that group items together which have related functionality, serve similar purpose, touch on related features. But again, sub-menus are never meant to be a method to have items "hidden away."
> 
> > This is a feature that will be used by probably 'most' people on many future updates, not a select few only once, and should be front and centre on the main menu, I don't want users digging through menus to try and find and approve an changelog check if that makes sense? lol
> 
> Currently, we essentially have a 2-level menu structure, with only 2 sub-menus so "digging through menus" is not how I would qualify the current menu navigation & user experience; but I certainly understand that some menu options should be more "readily available" than others - after all, findability, accessibility & usability are very important aspects of a good menu design.
> 
> > I understand it may feel like it fits better under the Changelog Check but that would mean hiding an important switch, I think we should be thinking about the users experience over what looks nicest in this regard :)
> > Unless you have ideas to address my concern? Maybe add a warning at the top like when an update is available? Or maybe just move both options out of the Advanced options and have both the Changelog Check and the approval in the main menu?
> 
> Yes, I think that moving the two related options to the Main Menu would work well in this case because the setting of one clearly affects the other.
> 
> My 2 cents.

@Martinski4GitHub 

Thanks for your viewpoint and opinion, I'll submit another commit later tonight that we positions some stuff around and you tell me if this feels more or less within that standard guidelines you mentioned.

I do want this to be easily accessible.
Maybe hidden away was bad choice of words, I'd consider a "hidden" menu to be a menu with essentially no display.

The options exist without any clear indicator, for example at my work often times my powershell scripts use Control+D to enable debug mode on my script without any clear menu or indication that such a control exists.
(If you know, you know).

So your right, hidden was probably not the right word but what I mean is ness viewed. Less used. More advanced so not so common, if that made sense :)

**Comment by Martinski4GitHub** [comment]
> 
> @Martinski4GitHub
> 
> Thanks for your viewpoint and opinion, I'll submit another commit later tonight that will repositions some stuff around and you tell me if this feels more or less within that standard guidelines you mentioned.
> 
OK, that sounds good. I'm about to have dinner in a few minutes so I'll check again later tonight.

>
> I do want this to be easily accessible. Maybe hidden away was bad choice of words, I'd consider a "hidden" menu to be a menu with essentially no display.
> 
> The options exist without any clear indicator, for example at my work often times my powershell scripts use Control+D to enable debug mode on my script without any clear menu or indication that such a control exists. (If you know, you know).
> 
> So your right, hidden was probably not the right word but what I mean is n less viewed. Less used. More advanced so not so common, if that made sense :)
>
OK, I get what you meant now. Sub-menus are not "hidden" per se but simply not "displayed" on the top menu and, therefore, not immediately accessible to the user at first glance.

In some projects I've worked on, we also include some undocumented keypress combinations that toggle ON/OFF some extra debugging or more verbose logging features, so when our technical support teams go on-site to troubleshoot problems they can use that to gather more debugging data to analyze. Those are in fact "hidden" options that only a few people would know about.

Thanks for clarifying.

**Comment by ExtremeFiretop** [comment]
@Martinski4GitHub 

Check out commit: https://github.com/ExtremeFiretop/MerlinAutoUpdate-Router/pull/220/commits/3aa6598cea51ae0bf79c23fe6ada28db60afbe84

This is what it generally looks like now...
Main Menu (With Node and Approval Option)
image

Main Menu (With Node and Without Approval Option)
image

Advanced Menu:
image

**Comment by ExtremeFiretop** [comment]
Oh and Main Menu (No Nodes):
image

**Comment by Martinski4GitHub** [comment]
> @Martinski4GitHub
> 
> Check out commit: [3aa6598](https://github.com/ExtremeFiretop/MerlinAutoUpdate-Router/commit/3aa6598cea51ae0bf79c23fe6ada28db60afbe84)
> 
> This is what it generally looks like now... 
> Main Menu (With Node and Approval Option) 
> ...
> Main Menu (With Node and Without Approval Option)
> ...
>
> Oh and Main Menu (No Nodes): 
> ...
>
The Main Menu in all its various forms looks just right!! Ready to ship :>)

**Review by Martinski4GitHub — APPROVED** [review]
Good to go.

**Comment by ExtremeFiretop** [comment]
> Good to go.

Thank you!
Happy I was able to address your concerns while also keeping it front and center. There's always a compromise haha! 

I updated the title of this PR since it for merged and that's it for now I don't really have much more for this release yet.

I'll update Gnuton to match sometime today

**Comment by Martinski4GitHub** [comment]
> > Good to go.
> 
> Thank you! Happy I was able to address your concerns while also keeping it front and center. There's always a compromise haha!
> 
> I updated the title of this PR since it got merged and that's it for now I don't really have much more for this release yet.
> 
> I'll update Gnuton to match sometime today
>
I just submitted a PR to adjust the wording in some titles & messages for clarity & consistency throughout the UI.
Some minor improvements as well - nothing major. Please review & validate when you have a chance.
I'll run the latest code through the Linter tool sometime within the next 2 days to double-check.

**Comment by ExtremeFiretop** [comment]
> > > Good to go.
> > 
> > 
> > Thank you! Happy I was able to address your concerns while also keeping it front and center. There's always a compromise haha!
> > I updated the title of this PR since it got merged and that's it for now I don't really have much more for this release yet.
> > I'll update Gnuton to match sometime today
> 
> I just submitted a PR to adjust the wording in some titles & messages for clarity & consistency throughout the UI. Some minor improvements as well - nothing major. Please review & validate when you have a chance. I'll run the latest code through the Linter tool sometime within the next 2 days to double-check.

I approved your PR and merged it in :) Sounds good to me, no rush on the linter tool I think the next release will be next weekend.

Gnuton has been updated to match this PR in commit: https://github.com/ExtremeFiretop/MerlinAutoUpdate-Router/pull/186/commits/27d9c54fe0e5808a822524a86539b860526a5f54

**Pull request merged**
