### PR TITLE
Code improvements.

### PR DESCRIPTION
**Pull request by Martinski4GitHub**
A few code improvements to minimize the number of NVRAM calls for a couple of settings that should not change often, especially during script execution.

### CODE REVIEW

**Review by ExtremeFiretop — APPROVED** [review]

**Comment by ExtremeFiretop** [comment]
@Martinski4GitHub 

Look at you go man! Once it had the time to sit down and review man did he ever!
LOL. You know.. I was thinking, I probably could of done lots of this stuff while my PR was still unmerged! 
I feel like sometimes I should handle the cleanup to get better at it and I feel bad having you be the linter every time.

This was much appreciated change though! Agreed it's best to call t once and then reference the result everytime.

**Comment by ExtremeFiretop** [comment]
@Martinski4GitHub 

Just tested and results are beautiful!

**Comment by Martinski4GitHub** [comment]
>
> Look at you go man! Once it had the time to sit down and review man did he ever! LOL. You know.. I was thinking, I probably could of done lots of this stuff while my PR was still unmerged! I feel like sometimes I should handle the cleanup to get better at it and I feel bad having you be the linter every time.
> 
No worries. Doing the code review actually gave me a chance to understand a bit more about AiMesh Node functionality & management from the Main Router's perspective so it was also a learning opportunity for me as well.

>
> Just tested and results are beautiful! Team effort! I threw a lot of code at you but it's actually looking pretty polished now for the node management.
>
Yeah, I think it's ready to be released "to the wild." Unless you want to issue a **Beta** version first and get a few more mileage & feedback from actual users with Mesh Nodes.

BTW, the latest "**386.13**" F/W version update for **AC**- models was released today so it would be a good time for a script release update with the improved "Available RAM" memory status. Anytime you feel ready.

**Comment by ExtremeFiretop** [comment]
> > Look at you go man! Once it had the time to sit down and review man did he ever! LOL. You know.. I was thinking, I probably could of done lots of this stuff while my PR was still unmerged! I feel like sometimes I should handle the cleanup to get better at it and I feel bad having you be the linter every time.
> 
> No worries. Doing the code review actually gave me a chance to understand a bit more about AiMesh Node functionality & management from the Main Router's perspective so it was also a learning opportunity for me as well.
> 
> > Just tested and results are beautiful! Team effort! I threw a lot of code at you but it's actually looking pretty polished now for the node management.
> 
> Yeah, I think it's ready to be released "to the wild." Unless you want to issue a **Beta** version first and get a few more mileage & feedback from actual users with Mesh Nodes.
> 
> BTW, the latest "**386.13**" F/W version update for **AC**- models was released today so it would be a good time for a script release update with the improved "Available RAM" memory status. Anytime you feel ready.

I'm ready now, let's send it out. I was waiting to make sure you felt comfortable.

I'll start to package 1.1.0 now, we can call it a beta release for the nodes but it seems like it works exactly as I expected and advertised right now so makes me happy!

Pretty much exactly what I had in mind.
Are you in the path of totality for the solar eclipse tomorrow?

I'm about an hours drive, I'll probably be looking up at the sky's tomorrow!

**Comment by Martinski4GitHub** [comment]
> > 
> > Yeah, I think it's ready to be released "to the wild." Unless you want to issue a **Beta** version first and get a few more mileage & feedback from actual users with Mesh Nodes.
> > BTW, the latest "**386.13**" F/W version update for **AC**- models was released today so it would be a good time for a script release update with the improved "Available RAM" memory status. Anytime you feel ready.
> 
> I'm ready now, let's send it out. I was waiting to make sure you felt comfortable.
> 
> I'll start to package 1.1.0 now, we can call it a beta release for the nodes but it seems like it works exactly as I expected and advertised right now so makes me happy!
>
Sounds good. The first release of a new feature always tends to be the point "where the rubber meets the road" and where s/w maturity begins based on real-world user feedback, so I feel it's ready to go. Let's get real mileage on it!!

> 
> Pretty much exactly what I had in mind. Are you in the path of totality for the solar eclipse tomorrow?
> 
> I'm about an hours drive, I'll probably be looking up at the sky's tomorrow!
>
I'm on the West Coast of the US, and the path of totality enters in the middle of Texas so I'm way off the path, but I'll probably be watching it sometime during the Live Stream.

**Pull request merged**
