### PR TITLE
Update MerlinAU.sh

### PR DESCRIPTION
**Pull request by Martinski4GitHub**
Just some minor formatting changes to make it easier to read/review.

### CODE REVIEW

**Review by ExtremeFiretop — APPROVED** [review]

**Comment by ExtremeFiretop** [comment]
Looks easier to read to me! Approved and Merged!

**Comment by Martinski4GitHub** [comment]
> Looks easier to read to me! Approved and Merged!
>
Glad you think so. I know some formatting changes seem pedantic and perhaps unnecessary at times, but I'm so used to certain formatting "style" & indentation levels that anything else sometimes feels harder to read through quickly. 

Also, at work, we regularly do code reviews so our coding standards are very explicit about certain rules to increase code readability and, therefore, increase future maintainability and refactoring.

Just wanted to let you know some of the reasoning behind my reformatting changes, just in case you were wondering why and to avoid any misinterpretation of such changes.

**Comment by ExtremeFiretop** [comment]
> > Looks easier to read to me! Approved and Merged!
> 
> Glad you think so. I know some formatting changes seem pedantic and perhaps unnecessary at times, but I'm so used to certain formatting "style" & indentation levels that anything else sometimes feels harder to read through quickly.
> 
> Also, at work, we regularly do code reviews so our coding standards are very explicit about certain rules to increase code readability and, therefore, increase future maintainability and refactoring.
> 
> Just wanted to let you know some of the reasoning behind my reformatting changes, just in case you were wondering why and to avoid any misinterpretation of such changes.

No all good with me!!

that's exactly what I expected, if me or you get hit by a bus it's best we keep things as easy to read as possible lol! 

I totally get it.

**Comment by ExtremeFiretop** [comment]
Pft, I forgot to include the minimum version in the message. Oh well something to do tomorrow

**Comment by ExtremeFiretop** [comment]
> > > Looks easier to read to me! Approved and Merged!
> > 
> > 
> > Glad you think so. I know some formatting changes seem pedantic and perhaps unnecessary at times, but I'm so used to certain formatting "style" & indentation levels that anything else sometimes feels harder to read through quickly.
> > Also, at work, we regularly do code reviews so our coding standards are very explicit about certain rules to increase code readability and, therefore, increase future maintainability and refactoring.
> > Just wanted to let you know some of the reasoning behind my reformatting changes, just in case you were wondering why and to avoid any misinterpretation of such changes.
> 
> No all good with me!!
> 
> that's exactly what I expected, if me or you get hit by a bus it's best we keep things as easy to read as possible lol!
> 
> I totally get it.

Also I usually just slap stuff together and the second it 'works' I submit the PR so the fact that you keep a much more vigorous standard is nice because you help me polish the code, I don't see any issues at all! :)

**Comment by ExtremeFiretop** [comment]
> > > > Looks easier to read to me! Approved and Merged!
> > > 
> > > 
> > > Glad you think so. I know some formatting changes seem pedantic and perhaps unnecessary at times, but I'm so used to certain formatting "style" & indentation levels that anything else sometimes feels harder to read through quickly.
> > > Also, at work, we regularly do code reviews so our coding standards are very explicit about certain rules to increase code readability and, therefore, increase future maintainability and refactoring.
> > > Just wanted to let you know some of the reasoning behind my reformatting changes, just in case you were wondering why and to avoid any misinterpretation of such changes.
> > 
> > 
> > No all good with me!!
> > that's exactly what I expected, if me or you get hit by a bus it's best we keep things as easy to read as possible lol!
> > I totally get it.
> 
> Also I usually just slap stuff together and the second it 'works' I submit the PR so the fact that you keep a much more vigorous standard is nice because you help me polish the code, even when I don't see any issues at all! :) Turns B level code to A/A+ level code haha

This is also the reason sometimes I feel me doing code review for you is pointless since I know you pump out such polished stuff there's little I ever need to change, but I still do review it! I need to make sure I follow at least 90% of the changes else I could be confused down the line lol.

And while I do consider this project a fun pass time I also do consider it pretty important and groundbreaking so let's do it right when/where we can!

**Comment by Martinski4GitHub** [comment]
> > > No all good with me!!
> > > that's exactly what I expected, if me or you get hit by a bus it's best we keep things as easy to read as possible lol!
> > > I totally get it.
> > 
> > 
> > Also I usually just slap stuff together and the second it 'works' I submit the PR so the fact that you keep a much more vigorous standard is nice because you help me polish the code, even when I don't see any issues at all! :) Turns B level code to A/A+ level code haha
> 
> This is also the reason sometimes I feel me doing code review for you is pointless since I know you pump out such polished stuff there's little I ever need to change, but I still do review it! I need to make sure I follow at least 90% of the changes else I could be confused down the line lol.
> 
As the saying goes: "Two heads are better than one."  So yes, please keep me on my toes as well since I can make (and have made) mistakes in the past, so a 2nd pair of eyes reviewing the code is helpful. Also, part of the philosophy behind doing code reviews, including among experienced s/w developers, is that "nobody is infallible." Even for us old-timers who have been coding for decades, having another person take a look with fresh eyes can be, well, refreshing, especially when hidden assumptions are discovered that need to be reevaluated.

>
> And while I do consider this project a fun pass time I also do consider it pretty important and groundbreaking so let's do it right when/where we can!
>
Exactly!!

**Pull request merged**
