### PR TITLE
Updated MerlinAU.sh

### PR DESCRIPTION
**Pull request by Martinski4GitHub**
Fixed a bug causing the execution of the cron job to fail because multiple PIDs of the script were found when called from crontab so put a new mechanism in place using a lock file as semaphore.
Fine-tuned placement of the "signals trap" statement.
Some code improvements in the "_DoCleanUp_" function.

### CODE REVIEW

**Review by ExtremeFiretop — APPROVED** [review]

**Comment by ExtremeFiretop** [comment]
Testing now.

Will advise of the results shortly.

**Comment by ExtremeFiretop** [comment]
Can confirm, this lock file method is better.

It still detects if I'm running the script twice and exists, however, it allows the Cron job to be executed at the expected time.

This is better :) That being said, find the attached file: [GT-AXE11000_FW_Update_2023-12-26_09_35_00.log](https://github.com/ExtremeFiretop/MerlinAutoUpdate-Router/files/13772168/GT-AXE11000_FW_Update_2023-12-26_09_35_00.log)

It still never flashes for me and always stops at the same part.

 Seems to maybe have something to do with: 

```
    routerURLstr="$(_GetRouterURL_)"
    # DEBUG: Print the LAN IP to ensure it's being set correctly
    printf "\nRouter Web URL is: ${routerURLstr}\n"

    printf "${GRNct}**IMPORTANT**:${NOct}\nThe firmware flash is about to start.\n"
    printf "Press Enter to stop now, or type ${GRNct}Y${NOct} to continue.\n"
    printf "Once started, the flashing process CANNOT be interrupted.\n"
    if ! _WaitForYESorNO_ "Continue"
    then _DoCleanUp_ 1 "$keepZIPfile" ; return 1 ; fi

    #------------------------------------------------------------#
    # Restart the WebGUI to make sure nobody else is logged in
    # so that the F/W Update can start without interruptions.
    #------------------------------------------------------------#
    /sbin/service restart_httpd && sleep 5
```

Still testing.

**Comment by ExtremeFiretop** [comment]
So far the issue seems to be the line at around ~1971:
I am testing this as the solution now:

```
	if [ "$inMenuMode" = true ]; then
    printf "${GRNct}**IMPORTANT**:${NOct}\nThe firmware flash is about to start.\n"
    printf "Press Enter to stop now, or type ${GRNct}Y${NOct} to continue.\n"
    printf "Once started, the flashing process CANNOT be interrupted.\n"
		if ! _WaitForYESorNO_ "Continue"
		then _DoCleanUp_ 1 "$keepZIPfile" ; return 1 ; fi
	fi
```

**Comment by ExtremeFiretop** [comment]
Bingo.

That worked as found here:

[GT-AXE11000_FW_Update_2023-12-26_09_55_00.log](https://github.com/ExtremeFiretop/MerlinAutoUpdate-Router/files/13772244/GT-AXE11000_FW_Update_2023-12-26_09_55_00.log)

Will submit a PR shortly.

**Comment by ExtremeFiretop** [comment]
PR Submitted here: https://github.com/ExtremeFiretop/MerlinAutoUpdate-Router/pull/56

**Comment by Martinski4GitHub** [comment]
> So far the issue seems to be the line at around ~1971: I am testing this as the solution now:
> 
> ```
> 	if [ "$inMenuMode" = true ]; then
>     printf "${GRNct}**IMPORTANT**:${NOct}\nThe firmware flash is about to start.\n"
>     printf "Press Enter to stop now, or type ${GRNct}Y${NOct} to continue.\n"
>     printf "Once started, the flashing process CANNOT be interrupted.\n"
> 		if ! _WaitForYESorNO_ "Continue"
> 		then _DoCleanUp_ 1 "$keepZIPfile" ; return 1 ; fi
> 	fi
> ```
>
Another good find!! You're on a roll, buddy. Keep going!!! :>)

**Comment by ExtremeFiretop** [comment]
> > So far the issue seems to be the line at around ~1971: I am testing this as the solution now:
> > ```
> > 	if [ "$inMenuMode" = true ]; then
> >     printf "${GRNct}**IMPORTANT**:${NOct}\nThe firmware flash is about to start.\n"
> >     printf "Press Enter to stop now, or type ${GRNct}Y${NOct} to continue.\n"
> >     printf "Once started, the flashing process CANNOT be interrupted.\n"
> > 		if ! _WaitForYESorNO_ "Continue"
> > 		then _DoCleanUp_ 1 "$keepZIPfile" ; return 1 ; fi
> > 	fi
> > ```
> 
> Another good find!! You're on a roll, buddy. Keep going!!! :>)

Thank you. You as well! :) I noticed I didn't use your new _DoExit_ 1 and _DoExit_ 0 functions. Will correct that in a moment.

**Comment by Martinski4GitHub** [comment]
> > > So far the issue seems to be the line at around ~1971: I am testing this as the solution now:
> > > ```
> > > 	if [ "$inMenuMode" = true ]; then
> > >     printf "${GRNct}**IMPORTANT**:${NOct}\nThe firmware flash is about to start.\n"
> > >     printf "Press Enter to stop now, or type ${GRNct}Y${NOct} to continue.\n"
> > >     printf "Once started, the flashing process CANNOT be interrupted.\n"
> > > 		if ! _WaitForYESorNO_ "Continue"
> > > 		then _DoCleanUp_ 1 "$keepZIPfile" ; return 1 ; fi
> > > 	fi
> > > ```
> > 
> > 
> > Another good find!! You're on a roll, buddy. Keep going!!! :>)
> 
> Thank you. You as well! :) I noticed I didn't use your new _DoExit_ 1 and _DoExit_ 0 functions. Will correct that in a moment.
> 
Yeah, I found that as well and submitted PR #60.
P.S. Looks like we both found it & fixed it at the same time :>)

**Comment by ExtremeFiretop** [comment]
> > > > So far the issue seems to be the line at around ~1971: I am testing this as the solution now:
> > > > ```
> > > > 	if [ "$inMenuMode" = true ]; then
> > > >     printf "${GRNct}**IMPORTANT**:${NOct}\nThe firmware flash is about to start.\n"
> > > >     printf "Press Enter to stop now, or type ${GRNct}Y${NOct} to continue.\n"
> > > >     printf "Once started, the flashing process CANNOT be interrupted.\n"
> > > > 		if ! _WaitForYESorNO_ "Continue"
> > > > 		then _DoCleanUp_ 1 "$keepZIPfile" ; return 1 ; fi
> > > > 	fi
> > > > ```
> > > 
> > > 
> > > Another good find!! You're on a roll, buddy. Keep going!!! :>)
> > 
> > 
> > Thank you. You as well! :) I noticed I didn't use your new _DoExit_ 1 and _DoExit_ 0 functions. Will correct that in a moment.
> 
> Yeah, I found that as well and submitted PR #60. P.S. Looks like we both found it & fixed it at the same time :>)

Yours was better so it wins hahaha! We work will together in this partnership. Thank you for always covering my back! This was a perfect solution.

**Comment by Martinski4GitHub** [comment]
> 
> Yours was better so it wins hahaha! We work well together in this partnership. Thank you for always covering my back! This was a perfect solution.
>
Yes, we have a very good collaborative "rhythm" & partnership going, which is not always easy to find.
And thank you for covering my mistakes as well (e.g. the cron job faux pas).
This deserves another celebratory toast!!  (says he while having a small glass of wine - to finish a bottle from Christmas Eve :) - just before heading to have dinner with my folks).
Enjoy your evening my friend!!

**Comment by Martinski4GitHub** [comment]
> > Yours was better so it wins hahaha! We work well together in this partnership. Thank you for always covering my back! This was a perfect solution.
> 
> Yes, we have a very good collaborative "rhythm" & partnership going, which is not always easy to find. And thank you for covering my mistakes as well (e.g. the cron job faux pas). This deserves another celebratory toast!! (says he while having a small glass of wine - to finish a bottle from Christmas Eve :) - just before heading out to have dinner with my folks). Enjoy your evening my friend!!

**Comment by ExtremeFiretop** [comment]
> > Yours was better so it wins hahaha! We work well together in this partnership. Thank you for always covering my back! This was a perfect solution.
> 
> Yes, we have a very good collaborative "rhythm" & partnership going, which is not always easy to find. And thank you for covering my mistakes as well (e.g. the cron job faux pas). This deserves another celebratory toast!! (says he while having a small glass of wine - to finish a bottle from Christmas Eve :) - just before heading to have dinner with my folks). Enjoy your evening my friend!!

Enjoy the evening and the wine haha! And of course, every oversight is my responsibility just as much. I appreciate the time you put in! Your skill and intuition is sometimes like magic!

Chat soon my friend!

**Pull request merged**
