### PR TITLE
Update MerlinAU.sh Allow Upgrade from Beta to Release

### PR DESCRIPTION
**Pull request by ExtremeFiretop**
Update MerlinAU.sh Allow Upgrade from Beta to Release

Added a toggle to enable or disable beta firmware updates.

### CODE REVIEW

**Comment by ExtremeFiretop** [comment]
@Martinski4GitHub 

I changed my mind. I submmited the PR now. It's ready. Tested it and successfully stopped and started my upgrade from beta 1 to production.

**Comment by ExtremeFiretop** [comment]
Quick changes to cleanup my stupid windows notepad returns

**Comment by ExtremeFiretop** [comment]
Resolved conflicts. Ready for merge.

**Comment by ExtremeFiretop** [comment]
@Martinski4GitHub 

At this point. I guess we are pretty much done the project?
Looks functional, safe, well written, tightly coded. I like it. I like it a lot.

I'm gonna run it through the full paces tonight and probably tomorrow, and test an upgrade situation from our currently production version. Also test all the settings while upgrading in both interactive and non-interactive modes, and do an fresh uninstall and install, check to make sure it's all clean.

Also want to test to see if Viktor really solved BACKUPMON. 
But otherwise, I think this is near the end for now my friend. Until next time that is! You always know where to find me if needed, I'm around the forums and here and easy to reach.

I don't expect us to have many things to tweak or change after this, but I'll have fun keeping an eye on the forums for a while and see :)

**Comment by ExtremeFiretop** [comment]
Oh: and I'll retest with all my add-ons re-installed as well.

**Comment by Martinski4GitHub** [comment]
> @Martinski4GitHub
> 
> At this point. I guess we are pretty much done the project? Looks functional, safe, well written, tightly coded. I like it. I like it a lot.
> 
I was going to look into writing a function to unmount the USB drive(s) just before calling the **curl** command to do the F/W flash; but I'll do it tomorrow. My folks here want to watch a movie in a few minutes (don't know yet which one they decided to watch).

>
> I'm gonna run it through the full paces tonight and probably tomorrow, and test an upgrade situation from our current production version. Also test all the settings while upgrading in both interactive and non-interactive modes, and do an fresh uninstall and install, check to make sure it's all clean.
>
Yeah, that's a good idea. You seem to have a knack for doing good, methodical testing. That's a good skill to have.

> 
> Also want to test to see if Viktor really solved BACKUPMON. But otherwise, I think this is near the end for now my friend. Until next time that is! You always know where to find me if needed, I'm around the forums and here and easy to reach.
> 
I'll also take a look into the problem with blank drive labels that Viktor seems to have still. I read through the DMs and I think I understand what's going on. He's a nice, good fellow, always willing to help others, so I'd like to return the favor by trying to help him figure out that problem, as much as I can. I've helped him before and provided a few functions for Backupmon.

>
> I don't expect us to have many things to tweak or change after this, .....
>
Famous last words!!!!

**Comment by ExtremeFiretop** [comment]
> Oh: and I'll retest with all my add-ons re-installed as well.



> > @Martinski4GitHub
> > At this point. I guess we are pretty much done the project? Looks functional, safe, well written, tightly coded. I like it. I like it a lot.
> 
> I was going to look into writing a function to unmount the USB drive(s) just before calling the **curl** command to do the F/W flash; but I'll do it tomorrow. My folks here want to watch a movie in a few minutes (don't know yet which one they decided to watch).
> 
> > I'm gonna run it through the full paces tonight and probably tomorrow, and test an upgrade situation from our current production version. Also test all the settings while upgrading in both interactive and non-interactive modes, and do an fresh uninstall and install, check to make sure it's all clean.
> 
> Yeah, that's a good idea. You seem to have a knack for doing good, methodical testing. That's a good skill to have.
> 
> > Also want to test to see if Viktor really solved BACKUPMON. But otherwise, I think this is near the end for now my friend. Until next time that is! You always know where to find me if needed, I'm around the forums and here and easy to reach.
> 
> I'll also take a look into the problem with blank drive labels that Viktor seems to have still. I read through the DMs and I think I understand what's going on. He's a nice, good fellow, always willing to help others, so I'd like to return the favor by trying to help him figure out that problem, as much as I can. I've helped him before and provided a few functions for Backupmon.
> 
> > I don't expect us to have many things to tweak or change after this, .....
> 
> Famous last words!!!!

I think it's a good idea, we technically can let the system handle sure, it but I don't see anything wrong with unloading it before the last curl. If anything it limits potential for stuff to go wrong if we handle it ourselves before the flash.

Don't forget Martin your the reason this project is so great. You offering your hand and knowledge allowed me to take an idea I had just last October just a few months ago and a tiny script (only maybe few hundred lines long) into this masterpiece.

You deserve all the praise, it did take us a few months (About 3 on and off) but I would still be doing research and only chipping away at this bit by bit otherwise, there are points where I can think out the logic, other times, having someone to bounce the ideas and just talk it out makes the world of difference in identifying the path forward quickly and effectively.

Truthfully how I often work is by testing, I don't trust my own code or anyone else's 99% of the time. Even big production companies. Whisker? Their litter robots? Shark? Their AI vacuums? Eufy and their camera? Doesn't matter I've reported bugs and requested software changes to all those companies and had it followed through to the end lol. 

That's why you notice I'm good at picking out stuff lol. At work I don't script often, so I test the stuff for 12 hours straight just making little tweaks here and there.

It's the reason I'm good at testing, but also the reason I'm so impressed by your code. Your code is actually near spotless everytime and the confidence level is very apparent. Couldn't be paired with anyone better. I had a lot of fun. Learned a lot along the way, and hope to continue to become more fluent as time goes on!

Enjoy the movie! I'll provide a quick update tomorrow before sending word to thelonelycoder.

**Pull request merged**
