### PR TITLE
Dev 0.2.52 as Next Stable/Master Release

### PR DESCRIPTION
**Pull request by ExtremeFiretop**
Dev 0.2.52 as Next Stable/Master Release

### CODE REVIEW

**Comment by ExtremeFiretop** [comment]
@Martinski4GitHub 

3004.388.6 final has been released.

https://www.snbforums.com/threads/asuswrt-merlin-3004-388-6-beta-is-now-available.88336/post-887176

Will be monitoring closely tonight and tomorrow. (My delay is set to zero)

**Comment by ExtremeFiretop** [comment]
You know what I just thought about, right now our script is at the mercy of the routers automatic watchdog for updates, unless you go to the UI and click "check now" for updates the scripts "check" doesn't find anything.

Would be nice if the scripts check forced the watchdog check when you ran from the UI manually.
I'll have to look into if that's possible.

**Comment by ExtremeFiretop** [comment]
> @Martinski4GitHub
> 
> 3004.388.6 final has been released.
> 
> https://www.snbforums.com/threads/asuswrt-merlin-3004-388-6-beta-is-now-available.88336/post-887176
> 
> Will be monitoring closely tonight and tomorrow. (My delay is set to zero)

Doing my rounds this morning! :) How did things work out for you?

Successfully upgraded to 388.6 automatically last night on the GT-AXE11000 and the RT-AX88U Pro.
Woke up this morning to all the routers upgraded and no issues, all the scripts continue to work, etc.

**Comment by ExtremeFiretop** [comment]
> You know what I just thought about, right now our script is at the mercy of the routers automatic watchdog for updates, unless you go to the UI and click "check now" for updates the scripts "check" doesn't find anything.
> 
> Would be nice if the scripts check forced the watchdog check when you ran from the script UI manually. I'll have to look into if that's possible.

In reply to this above, I can make the WebUI notification blink with: nvram set webs_state_flag=1 and stop with nvram set webs_state_flag=0
And seems I can force an update check on the router by running this: /usr/sbin/webs_update.sh

**Comment by Martinski4GitHub** [comment]
> > You know what I just thought about, right now our script is at the mercy of the routers automatic watchdog for updates, unless you go to the UI and click "check now" for updates the scripts "check" doesn't find anything.
> > Would be nice if the scripts check forced the watchdog check when you ran from the script UI manually. I'll have to look into if that's possible.
> 
You're absolutely right. I just submitted PR #77 with a possible solution. Note that, IMO, the F/W Update checks should be done **ONLY** if the user has enabled that option (either via the router's webGUI, or the script menu); otherwise, we should honor the user's selection if it's disabled.

**Comment by Martinski4GitHub** [comment]
> > @Martinski4GitHub
> > 3004.388.6 final has been released.
> > https://www.snbforums.com/threads/asuswrt-merlin-3004-388-6-beta-is-now-available.88336/post-887176
> > Will be monitoring closely tonight and tomorrow. (My delay is set to zero)
> 
> Doing my rounds this morning! :) How did things work out for you?
> 
There's no new F/W update available for my RT-AC86U, so I'll have to wait.

**Comment by ExtremeFiretop** [comment]
> > > You know what I just thought about, right now our script is at the mercy of the routers automatic watchdog for updates, unless you go to the UI and click "check now" for updates the scripts "check" doesn't find anything.
> > > Would be nice if the scripts check forced the watchdog check when you ran from the script UI manually. I'll have to look into if that's possible.
> 
> You're absolutely right. I just submitted PR #77 with a possible solution. Note that, IMO, the F/W Update checks should be done **ONLY** if the user has enabled that option (either via the router's webGUI, or the script menu); otherwise, we should honor the user's selection if it's disabled.

Totally agree, i actually took a different route on this lol! I was working on it as well when you submitted your PR.

Have a look at: https://github.com/ExtremeFiretop/MerlinAutoUpdate-Router/commit/af3bd4ce5538be25c919d3f47468a9d1aff7f53a

**Comment by Martinski4GitHub** [comment]
> > > > You know what I just thought about, right now our script is at the mercy of the routers automatic watchdog for updates, unless you go to the UI and click "check now" for updates the scripts "check" doesn't find anything.
> > > > Would be nice if the scripts check forced the watchdog check when you ran from the script UI manually. I'll have to look into if that's possible.
> > 
> > 
> > You're absolutely right. I just submitted PR #77 with a possible solution. Note that, IMO, the F/W Update checks should be done **ONLY** if the user has enabled that option (either via the router's webGUI, or the script menu); otherwise, we should honor the user's selection if it's disabled.
> 
> Totally agree, i actually took a different route on this lol! I was working on it as well when you submitted your PR.
> 
> Have a look at: [af3bd4c](https://github.com/ExtremeFiretop/MerlinAutoUpdate-Router/commit/af3bd4ce5538be25c919d3f47468a9d1aff7f53a)
>
Ah, yes, you changed the settings directory name (added the ".d" suffix) to follow the format established for the standard add-ons. Good call.

**Pull request merged**
