### PR TITLE
Update MerlinAU.sh

### PR DESCRIPTION
**Pull request by Martinski4GitHub**
Improvement in the code that unmounts the USB drives just before the F/W flash.

### CODE REVIEW

**Comment by Martinski4GitHub** [comment]
@ExtremeFiretop,

I think this improvement when unmounting the USB drives may be important enough to go in the 1st release.

**Comment by ExtremeFiretop** [comment]
This seems to take priority then, let me test this now instead of playing with the changelogs.

Report back shortly.

**Review by ExtremeFiretop — APPROVED** [review]

**Comment by ExtremeFiretop** [comment]
Approved. So your adding a stop for nasapps and also defineining the path for the LEDs.

Both good improvements. 
According to Rmerlin here:

https://www.snbforums.com/threads/are-unmount-services-stop-run-at-reboot.35233/post-287011

"Those modules are all related to USB modems/printers, none of them are related to USB storage. "

Is this what you wanted to shut down?

**Comment by ExtremeFiretop** [comment]
https://www.snbforums.com/threads/re-mounting-attached-usb-storage-without-physically-unplug-and-replug.82535/post-811053

**Comment by Martinski4GitHub** [comment]
> Approved. So your adding a stop for nasapps and also defineining the path for the LEDs.
> 
> Both good improvements. According to Rmerlin here:
> 
> https://www.snbforums.com/threads/are-unmount-services-stop-run-at-reboot.35233/post-287011
> 
> "Those modules are all related to USB modems/printers, none of them are related to USB storage. "
> 
> Is this what you wanted to shut down?
> 
Yes, I just want to make sure anything attached to the other USB port is cleanly terminated before unmounting the drive(s) to avoid any potential issues due to a "device busy" state since those "nasapps" might be accessing the USB drive for some reason.

**Comment by ExtremeFiretop** [comment]
> > Approved. So your adding a stop for nasapps and also defineining the path for the LEDs.
> > Both good improvements. According to Rmerlin here:
> > https://www.snbforums.com/threads/are-unmount-services-stop-run-at-reboot.35233/post-287011
> > "Those modules are all related to USB modems/printers, none of them are related to USB storage. "
> > Is this what you wanted to shut down?
> 
> Yes, I just want to make sure anything attached to the other USB port is cleanly terminated before unmounting the drive(s) to avoid any potential issues due to a "device busy" state since those "nasapps" might be accessing the USB drive for some reason.

Merged!

**Pull request merged**
