### PR TITLE
Update MerlinAU.sh for Change-Log Check

### PR DESCRIPTION
**Pull request by ExtremeFiretop**
PR to resolve the discussion relating to changelog verification as best as we can via script.

In response to this message:

https://www.snbforums.com/threads/introducing-merlinau-the-ultimate-firmware-auto-updater-addon.88577/post-887890

### CODE REVIEW

**Comment by ExtremeFiretop** [comment]
The only thing I want to finish with this is I want to make it a config option for advanced users that never want to be interrupted (like myself).

When I say advanced. I may need to make a new sub menu, or just have the option but not display it.

**Comment by ExtremeFiretop** [comment]
Added new advanced menu to hide some of the options least used.

**Comment by ExtremeFiretop** [comment]
Adding in the new configuration option now under advanced options.
Almost done, still a few more things left, but off for dinner now.

**Comment by ExtremeFiretop** [comment]
That's it. Done with the new menu, done with the new log checker, and done with the new configuration option for it.

Chat with you more tomorrow @Martinski4GitHub 
Make sure to check your DMs in the forums ;)

**Comment by Martinski4GitHub** [comment]
> Added new advanced menu to hide some of the options least used.
>
Excellent idea. The top main menu was getting too "crowded" and might no longer fit on a small screen (like my iPad where sometimes I check out the latest GUI changes).

**Comment by ExtremeFiretop** [comment]
> > Added new advanced menu to hide some of the options least used.
> 
> Excellent idea. The top main menu was getting too "crowded" and might no longer fit on a small screen (like my iPad where sometimes I check out the latest GUI changes).

I'm happy you agree, I didn't ask your thought before making the move, but I just assumed that if I was feeling it was crowded that you would be feeling it too haha

**Comment by ExtremeFiretop** [comment]
Oh darn, I messed up the order in the advanced menu.

ROG should be option 5 instead of option 4. Since it's not always displayed on all models, and then all of a sudden it goes from options 3 to 5 on those other models.

**Comment by ExtremeFiretop** [comment]
Quick fixes. You didn't see it, it didn't happen. :D

**Comment by Martinski4GitHub** [comment]
> That's it. Done with the new menu, done with the new log checker, and done with the new configuration option for it.
>
It's looking good. Man, you were busy today!! Plus responding to posts on the SNB Forums, fielding questions. You're a brave soul!!

> 
> Chat with you more tomorrow @Martinski4GitHub Make sure to check your DMs in the forums ;)
>
Will do, later this evening. I was very busy pretty much all today with work-related stuff and some meetings, so I haven't had time to go through all the posts & DMs and respond as needed; but while reading some of the earlier posts with suggestions I like the idea of adding email notifications to some of the events (e.g. at the start of flashing a F/W update, and then another when it's completed, post-reboot). I have code in some of my custom scripts that send email notifications triggered by specific events so I think it can be ported over to do something similar for this script. I'll take a look.

**Comment by ExtremeFiretop** [comment]
> > That's it. Done with the new menu, done with the new log checker, and done with the new configuration option for it.
> 
> It's looking good. Man, you were busy today!! Plus responding to posts on the SNB Forums, fielding questions. You're a brave soul!!
> 
> > Chat with you more tomorrow @Martinski4GitHub Make sure to check your DMs in the forums ;)
> 
> Will do, later this evening. I was very busy pretty much all today with work-related stuff and some meetings, so I haven't had time to go through all the posts & DMs and respond as needed; but while reading some of the earlier posts with suggestions I like the idea of adding email notifications to some of the events (e.g. at the start of flashing a F/W update, and then another when it's completed, post-reboot). I have code in some of my custom scripts that send email notifications triggered by specific events so I think it can be ported over to do something similar for this script. I'll take a look.

I really liked it too, but I kinda put it on the back burner because he mentioned if email was configured in AMTM and we weren't integrated yet... But seems the DMs you'll read later will spice that up.

**Comment by Martinski4GitHub** [comment]
> Quick fixes. You didn't see it, it didn't happen. :D
>
I saw nothing, heard nothing & smelled nothing :>).

**Comment by ExtremeFiretop** [comment]
Okay Martinski my friend. Off to bed..
As you mentioned my day was nuts today...

I was responding on the forums, dealing with work calls, dealing with UPS delivery non-sense, and scripting my little brain out until I think I started reading the numbers at letters and letters as numbers.

**Pull request merged**
