### PR TITLE
Dev 1.3.1 as Next Stable Release

### PR DESCRIPTION
**Pull request by ExtremeFiretop**
Dev 1.3.1 as Next Stable Release

What's Changed/Fixed?:

PR: [ [ #301 ](https://github.com/ExtremeFiretop/MerlinAutoUpdate-Router/pull/301) ] 
- Small Improvements to Changelog Verification. Fixed a monitor bug with changelog verification.

PR: [ [ #302 ](https://github.com/ExtremeFiretop/MerlinAutoUpdate-Router/pull/302) ]
- Removing Cron Jobs from 3rd-party Add-Ons. Added code to remove cron jobs from 3rd-party Add-Ons right before ejecting the USB-attached drive and starting the actual F/W Update process. This is an effort to eliminate the possibility of a cron job starting to execute and accessing the USB drive filesystem. (Thanks [@Martinski4GitHub](https://github.com/Martinski4GitHub) [@Martinski](https://www.snbforums.com/members/69996/))

PR: [ [ #305 ](https://github.com/ExtremeFiretop/MerlinAutoUpdate-Router/pull/305) ]
- Update Minimum Version to 3004.386.12.6. our minimum version is currently 6 versions behind production or about 8 months behind production. Upping to 3 versions behind production. Last update in this regard was about 10 months ago.

PR: [ [ #308  ](https://github.com/ExtremeFiretop/MerlinAutoUpdate-Router/pull/308) ]
- Checking for the Minimum F/W Version supported now takes into account the F/W Branch of the currently installed F/W version. (Thanks [@Martinski4GitHub](https://github.com/Martinski4GitHub) [@Martinski](https://www.snbforums.com/members/69996/))

As always, we highly recommend you update ASAP as this includes lots of functional improvements and little bug fixes.

### CODE REVIEW

**Comment by ExtremeFiretop** [comment]
@Martinski4GitHub 

Updated the notes here and in the forums :) Auto-merge enabled on my side once you approve.
Ignore the out of date warning, it's about the dev/master flag being changed manually after the last failed workflow to update it.

Speaking of which, lets make sure the workflow correctly updates the dev flag once this is merged in.

**Comment by Martinski4GitHub** [comment]
> @Martinski4GitHub
> 
> Updated the notes here and in the forums :) Auto-merge enabled on my side once you approve. Ignore the out of date warning, it's about the dev/master flag being changed manually after the last failed workflow to update it.
> 
> Speaking of which, lets make sure the workflow correctly updates the dev flag once this is merged in.
>
>
Apologies for the delayed response. About 3 weeks ago, my wife's mother had a minor stroke (aka transient ischemic attack) so she's currently still recovering. Tonight during our dinner, my wife's father called and said that her mother was not feeling well, so we drove to their home to check and make sure there was not an emergency situation.

Anyway, I'll approve this now. Hopefully, everything will just work.

**Review by Martinski4GitHub — APPROVED** [review]
Good to go!!!

**Comment by ExtremeFiretop** [comment]
> > @Martinski4GitHub
> > Updated the notes here and in the forums :) Auto-merge enabled on my side once you approve. Ignore the out of date warning, it's about the dev/master flag being changed manually after the last failed workflow to update it.
> > Speaking of which, lets make sure the workflow correctly updates the dev flag once this is merged in.
> 
> Apologies for the delayed response. About 3 weeks ago, my wife's mother had a minor stroke (aka transient ischemic attack) so she's currently still recovering. Tonight during our dinner, my wife's father called and said that her mother was not feeling well, so we drove to their home to check and make sure there was not an emergency situation.
> 
> Anyway, I'll approve this now. Hopefully, everything will just work.

I'm sorry to hear that, I do hope the recovery goes well. I'm sure she appreciates the support!

**Comment by ExtremeFiretop** [comment]
@Martinski4GitHub 

Well now I'm very confused.

It seems to have updated the branch, but failed the workflow?

**Comment by Martinski4GitHub** [comment]
> > > @Martinski4GitHub
> > > Updated the notes here and in the forums :) Auto-merge enabled on my side once you approve. Ignore the out of date warning, it's about the dev/master flag being changed manually after the last failed workflow to update it.
> > > Speaking of which, lets make sure the workflow correctly updates the dev flag once this is merged in.
> > 
> > 
> > Apologies for the delayed response. About 3 weeks ago, my wife's mother had a minor stroke (aka transient ischemic attack) so she's currently still recovering. Tonight during our dinner, my wife's father called and said that her mother was not feeling well, so we drove to their home to check and make sure there was not an emergency situation.
> >
>> Anyway, I'll approve this now. Hopefully, everything will just work.
> 
> I'm sorry to hear that, I do hope the recovery goes well. I'm sure she appreciates the support!
>
Thank you. We're all very hopeful that she'll have a full recovery because it was not a full stroke, and her cognitive and language skills were not affected; only some of her physical coordination was affected. The doctors are very optimistic as well and said that thankfully it was only a minor stroke and was treated on time.

**Comment by Martinski4GitHub** [comment]
> @Martinski4GitHub
> 
> Well now I'm very confused.
> 
> It seems to have updated the branch, but failed the workflow?
>
>
I noticed it didn't merge automatically after the approval and thought it might have been due to the "out-of-date warning." 🤷

**Comment by ExtremeFiretop** [comment]
> > @Martinski4GitHub
> > Well now I'm very confused.
> > It seems to have updated the branch, but failed the workflow?
> 
> I noticed it didn't merge automatically after the approval and thought it might have been due to the "out-of-date warning." 🤷

I fixed it, the problem is the sed command didn't make any changes to the file, because the file already included "dev" and "1.3.1" so it failed to commit any changes. And cancelled the workflow.

So I made that step optional, if there is changes, commit them, else skip that step. Now it worked.
Next time we should try without updating the version early. As for the branch, I'm about to fix the out of sync warning now.

**Comment by Martinski4GitHub** [comment]
> > > @Martinski4GitHub
> > > Well now I'm very confused.
> > > It seems to have updated the branch, but failed the workflow?
> > 
> > 
> > I noticed it didn't merge automatically after the approval and thought it might have been due to the "out-of-date warning." 🤷
> 
> I fixed it, the problem is the sed command didn't make any changes to the file, because the file already included "dev" and "1.3.1" so it failed to commit any changes. And cancelled the workflow.
> 
> So I made that step optional, if there is changes, commit them, else skip that step. Now it worked. Next time we should try without updating the version early. As for the branch, I'm about to fix the out of sync warning now.
>
>
I'm very used to updating the version string on my 'development' branch as soon as some code changes are made so that during testing & verification I know I'm working with & executing a ***new*** development version and not still the 'stable' version.

**Comment by ExtremeFiretop** [comment]
> > > > @Martinski4GitHub
> > > > Well now I'm very confused.
> > > > It seems to have updated the branch, but failed the workflow?
> > > 
> > > 
> > > I noticed it didn't merge automatically after the approval and thought it might have been due to the "out-of-date warning." 🤷
> > 
> > 
> > I fixed it, the problem is the sed command didn't make any changes to the file, because the file already included "dev" and "1.3.1" so it failed to commit any changes. And cancelled the workflow.
> > So I made that step optional, if there is changes, commit them, else skip that step. Now it worked. Next time we should try without updating the version early. As for the branch, I'm about to fix the out of sync warning now.
> 
> I'm very used to updating the version string on my 'development' branch as soon as some code changes are made so that during testing & verification I know I'm working with & executing a _**new**_ development version and not still the 'stable' version.

Oh it's not just you, I also updated it early on my dev branch, if we do, and no changes are made to the file at least it will skip it now without failing.

I just wanted to see that step in action, but considering the out of sync warning is now fixed, it should run next time anyways to update the branch string from dev to master.

**Pull request merged**
