### PR TITLE
Update MerlinAU.sh

### PR DESCRIPTION
**Pull request by Martinski4GitHub**
Added code to support email notifications for the following events:

- When the script detects that a new F/W Update version is available.
- At the start of flashing a new F/W Update version.
- At the completion of flashing the F/W - post reboot.

The email notification mechanism uses AMTM email configuration setup so the option for F/W Update notifications becomes visible on the menu only if the user has chosen to enable and set up email notifications via AMTM.

### CODE REVIEW

**Comment by Martinski4GitHub** [comment]
@ExtremeFiretop,

Well, it turned out that porting the code I had written before for email notifications was easier than I thought so the integration & testing were completed faster than my initial estimate. So far it's working well on side of the fence.

If you have time, please try to set up email notifications via AMTM first, and then enable the option in the main menu so you can test the feature as you run your own test cycles.

BTW, I put the new option at the top main menu.  I'm not quite sure whether it should be on the new "Advance Options" menu. I really have no personal preference at this point so either way would be OK with me. The option is not visible at all unless you have AMTM optional feature enabled as well.

**Comment by ExtremeFiretop** [comment]
> @ExtremeFiretop,
> 
> Well, it turned out that porting the code I had written before for email notifications was easier than I thought so the integration & testing were completed faster than my initial estimate. So far it's working well on my side of the fence.
> 
> If you have time, please try to set up email notifications via AMTM first, and then enable the option in the main menu so you can test the feature as you run your own test cycles.
> 
> BTW, I put the new option at the top main menu. I'm not quite sure whether it should be on the new "Advanced Options" menu. I really have no personal preference at this point so either way would be OK with me. The option is not visible at all unless you have AMTM optional feature enabled as well.

I'm on it! Test is my middle man, after broken that is. 😆😉

**Comment by ExtremeFiretop** [comment]
I think I would recommend leaving this setting out in the open on the main menu if configured in AMTM.

We have more advanced options coming for the advanced menu anyways (like the option to enable beta to production firmware upgrades)

**Comment by ExtremeFiretop** [comment]
@Martinski4GitHub 

It's perfect. I can't find any bugs. 
Coming from yours Truly, Extreme Test Firetop

**Comment by ExtremeFiretop** [comment]
I think now that you implemented this, I'll take a different angle to advise for firmwares that need approval to flash due to the new changelog verification I just implemented.

**Comment by Martinski4GitHub** [comment]
> @Martinski4GitHub
> 
> It's perfect. I can't find any bugs. Coming from yours Truly, Extreme Test Firetop
> 
Excellent!! That's what I like to hear :>) Home run on 1st try.

**Comment by Martinski4GitHub** [comment]
> I think I would recommend leaving this setting out in the open on the main menu if configured in AMTM.
> 
> We have more advanced options coming for the advanced menu anyways (like the option to enable beta to production firmware upgrades)
>
That sounds good to me.

**Pull request merged**
