### PR TITLE
Keep ZeroTier connection during F/W updates.

### PR DESCRIPTION
**Pull request by Martinski4GitHub**
Updated code to keep ZeroTier VPN connection alive during F/W updates.
Also, if OpenSSH is being used for remote SSH access the server is kept alive as well.

### CODE REVIEW

**Comment by ExtremeFiretop** [comment]
Morning!

Looks great! Did you want me to merge this straight into dev so your friend can test it out?

**Comment by ExtremeFiretop** [comment]
So few changes it could be rolled back with my eyes closed.

I'll just merge it in and wait for final results from you :)

**Review by ExtremeFiretop — APPROVED** [review]

**Comment by Martinski4GitHub** [comment]
> Morning!
> 
> Looks great! Did you want me to merge this straight into dev so your friend can test it out?
>
See my comment on the other PR. My friend got the latest script from my 'develop' branch for testing & validation, so we're good. That was a good thought, though! Thanks!!

**Comment by ExtremeFiretop** [comment]
Synced with Gnuton in commit: https://github.com/ExtremeFiretop/MerlinAutoUpdate-Router/pull/186/commits/9f03004dfa959deba362de4e2ad16979b120f327

**Comment by Martinski4GitHub** [comment]
@ExtremeFiretop,

My friend just emailed me that his testing with **ZeroTier** was successful. He could not do it earlier today because access to the internet could not be interrupted so he had to wait until everyone had gone to sleep to fully test the functionality.
So we're good to go with this PR.

**Comment by ExtremeFiretop** [comment]
> @ExtremeFiretop,
> 
> My friend just emailed me that his testing with **ZeroTier** was successful. He could not do it earlier today because access to the internet could not be interrupted so he had to wait until everyone had gone to sleep to fully test the functionality. So we're good to go with this PR.

Fantastic news. No rush. I finally got some headway I think with RTRMON last night so that's what was mostly keeping me busy.

Tell your friend thanks for testing!

**Comment by Martinski4GitHub** [comment]
> > @ExtremeFiretop,
> > My friend just emailed me that his testing with **ZeroTier** was successful. He could not do it earlier today because access to the internet could not be interrupted so he had to wait until everyone had gone to sleep to fully test the functionality. So we're good to go with this PR.
> 
> Fantastic news. No rush. I finally got some headway I think with RTRMON last night so that's what was mostly keeping me busy.
> 
Sounds like you're making good, solid progress.

>
> Tell your friend thanks for testing!
>
Will do.

**Pull request merged**
