### PR TITLE
Update MerlinAU.sh

### PR DESCRIPTION
**Pull request by Martinski4GitHub**
Trivial changes.

### CODE REVIEW

**Review by ExtremeFiretop — APPROVED** [review]

**Comment by ExtremeFiretop** [comment]
Trivial is still important! I like how you keep things in check ;)

**Comment by ExtremeFiretop** [comment]
How are we feeling about "0.2.31" being the next main release, or should we give it a little more time before flagging it as such?

Let me know! :)

**Comment by Martinski4GitHub** [comment]
> How are we feeling about "0.2.31" being the next main release, or should we give it a little more time before flagging it as such?
> 
> Let me know! :)
> 
Sounds good to me. But first, let me give my friend this latest '**Dev**' version with all the recent enhancements so he can give it a "test drive" on his router. Often, he has good suggestions or might see something we fail to see because we are "too close to it." BTW, his F/W update went without any problems so he's pleased with the results. He says he'd like to use it on his parents' ASUS router as well because he's not always able to make it to their home to do F/W updates, and this allows him to schedule it beforehand up to 30 days after it comes out.

**Comment by ExtremeFiretop** [comment]
> > How are we feeling about "0.2.31" being the next main release, or should we give it a little more time before flagging it as such?
> > Let me know! :)
> 
> Sounds good to me. But first, let me give my friend this latest '**Dev**' version with all the recent enhancements so he can give it a "test drive" on his router. Often, he has good suggestions or might see something we fail to see because we are "too close to it." BTW, his F/W update went without any problems so he's pleased with the results. He says he'd like to use it on his parents' ASUS router as well because he's not always able to make it to their home to do F/W updates, and this allows him to schedule it beforehand up to 30 days after it comes out.

Sounds good to me! I myself will be using our script on my primary router going forwards (as I have been this whole time to test). I work from home, It's always in arms reach, if something goes wrong I know how to reset it, or even do a recovery if absolutely required.

So far though I'm pretty content with the logic we put down, I'm not overly concerned.

**Comment by ExtremeFiretop** [comment]
@Martinski4GitHub 

So 3 things I've noticed while testing on the RT-AX88U Pro at side gig. (Not the same as my AX88U I have at home).

1. Doing a script update doesn't automatically reload the script when it's done. 
It still returns on the main menu of the older script. So you have to exit and then restart the script to see the updated version.

2. The router attempts to login to get the cookie before your "are you sure prompt". Meaning if I logged out once I saw that prompt and hit "y" it would still fail as the login step has already passed (and failed)

3. On the AX88U Pro, it never completed the flash from the Web UI on the second run, the first run fails because I was logged into the web UI, the second froze at "Flashing, please wait for reboot" and didn't reboot or do anything for 5+ minutes.

I logged into the web UI, rebooted the router, and update had not completed.
I'll be digging through the logs myself to see what happened. 

Attaching relevant logs here:

[syslog.txt](https://github.com/ExtremeFiretop/MerlinAutoUpdate-Router/files/13697387/syslog.txt)
[RT-AX88U_Pro_FW_Update_2023-12-17_13_05_30.log](https://github.com/ExtremeFiretop/MerlinAutoUpdate-Router/files/13697388/RT-AX88U_Pro_FW_Update_2023-12-17_13_05_30.log)
[RT-AX88U_Pro_FW_Update_2023-12-17_13_03_31.log](https://github.com/ExtremeFiretop/MerlinAutoUpdate-Router/files/13697389/RT-AX88U_Pro_FW_Update_2023-12-17_13_03_31.log)

**Comment by ExtremeFiretop** [comment]
@Martinski4GitHub 

Started addressing the issues in PR: https://github.com/ExtremeFiretop/MerlinAutoUpdate-Router/pull/36

**Pull request merged**
