### PR TITLE
Dev 1.0.10 as Next Stable Release

### PR DESCRIPTION
**Pull request by ExtremeFiretop**
Dev 1.0.10 as Next Stable Release

*IMPORTANT BUG-FIX*
In response to a report made in the forums by: [TonyK132](https://www.snbforums.com/members/tonyk132.54189/)
https://www.snbforums.com/threads/merlinau-v1-0-9-the-ultimate-firmware-auto-updater-now-available-in-amtm.88577/post-898975

We have created PR: 176 "Improvements when calling the crontab cmd."
https://github.com/ExtremeFiretop/MerlinAutoUpdate-Router/pull/176

Also PR: 178 "Improving code to avoid unset variables."
https://github.com/ExtremeFiretop/MerlinAutoUpdate-Router/pull/178

PR: 180
https://github.com/ExtremeFiretop/MerlinAutoUpdate-Router/pull/180
Included debug logging if the router goes through the memory cleanup process so the logs will give us a very detailed breakdown of the memory status.

All submitted by @Martinski4GitHub .
MAJOR THANK YOU! This was one of those tricky ones. Full props and very impressed by Martinski's amazing skill!

### CODE REVIEW

**Comment by ExtremeFiretop** [comment]
@Martinski4GitHub 

This was a full @Martinski4GitHub special release!
You may as well have the honors to approve and submit the merge! :)

I'll start working on the post on SNB forums

**Comment by ExtremeFiretop** [comment]
Post is ready when this is merged :)
Your all clear to merge on my side!

**Comment by Martinski4GitHub** [comment]
> Post is ready when this is merged :) Your all clear to merge on my side!
>
I've waited over 5 minutes already and merging is still blocked. Don't know why. Perhaps the incomplete check?? See attached screenshot.

MergingBlocked

**Comment by ExtremeFiretop** [comment]
> > Post is ready when this is merged :) Your all clear to merge on my side!
> 
> I've waited over 5 minutes already and merging is still blocked. Don't know why. Perhaps the incomplete check?? See attached screenshot.
> 
> MergingBlocked

Weird, are you able to approve this PR?

**Review by Martinski4GitHub — APPROVED** [review]
Approved.

**Comment by ExtremeFiretop** [comment]
Interesting, so you approving solved the block, but it still won't auto merge without all the rules being run, but we have a rule that only runs after the merge is done (tag-and-release Expected — Waiting for status to be reported)

So I guess I can never use the auto-merge feature. But the approval did work.

**Comment by ExtremeFiretop** [comment]
Try now?

**Comment by Martinski4GitHub** [comment]
> Interesting, so you approving solved the block, but it still won't auto merge without all the rules being run, but we have a rule that only runs after the merge is done (tag-and-release Expected — Waiting for status to be reported)
> 
> So I guess I can never use the auto-merge feature. But the approval did work.
Yeah, I was able to approve it, but it looks like the "incomplete" check is what's causing the problem.

WaitingForCheck

**Comment by Martinski4GitHub** [comment]
> Try now?
>
Same as before. The incomplete check is holding up the merge for some reason.

**Comment by ExtremeFiretop** [comment]
> > Try now?
> 
> Same as before. The incomplete check is holding up the merge for some reason.

I'll just push it through now with bypassing the check, but we should make a mental note of this.

**Comment by Martinski4GitHub** [comment]
Latest status:

WaitingForCheck2

**Comment by ExtremeFiretop** [comment]
> Latest status:
> 
> WaitingForCheck2

Confirmed on my side too.
I pushed it through, but we should investigate if/what we can do about that.

**Comment by ExtremeFiretop** [comment]
@Martinski4GitHub 

I can confirm it correctly tagged the release, but it seems we can't merge because it's a requirement that all rules be passed before the merge, but one of our rules only runs after the merge is completed lol.

Will have to think a bit on that

**Comment by Martinski4GitHub** [comment]
> @Martinski4GitHub
> 
> I can confirm it correctly tagged the release, but it seems we can't merge because it's a requirement that all rules be passed before the merge, but one of our rules only runs after the merge is completed lol.
> 
> Will have to think a bit on that
>
Is there a way to define a rule as required for "pre-merge" only & other rules for "post-merge" only?

**Comment by ExtremeFiretop** [comment]
> > @Martinski4GitHub
> > I can confirm it correctly tagged the release, but it seems we can't merge because it's a requirement that all rules be passed before the merge, but one of our rules only runs after the merge is completed lol.
> > Will have to think a bit on that
> 
> Is there a way to define a rule as required for "pre-merge" only & other rules for "post-merge" only?

I think I solved the issue.
I had made it a required rule for the main branch, but I don't think it needs to be a required rule to actually run.

So I removed it from the required rule list, but the rule is still active. I think in theory this is what we want.

**Comment by ExtremeFiretop** [comment]
We will test it again in 1.1.0 and I'll have you merge that one into production to confirm! :)

**Comment by Martinski4GitHub** [comment]
> > Is there a way to define a rule as required for "pre-merge" only & other rules for "post-merge" only?
> 
> I think I solved the issue. I had made it a required rule for the main branch, but I don't think it needs to be a required rule to actually run.
> 
> So I removed it from the required rule list, but the rule is still active. I think in theory this is what we want.
>
Yeah, that sounds like it should work since the rule remains active and should run, but it's no longer a prerequisite for merging "develop" into the "main" branch.

**Comment by ExtremeFiretop** [comment]
> > > Is there a way to define a rule as required for "pre-merge" only & other rules for "post-merge" only?
> > 
> > 
> > I think I solved the issue. I had made it a required rule for the main branch, but I don't think it needs to be a required rule to actually run.
> > So I removed it from the required rule list, but the rule is still active. I think in theory this is what we want.
> 
> Yeah, that sounds like it should work since the rule remains active and should run, but it's no longer a prerequisite for merging "develop" into the "main" branch.

It's all a learning curve, but we are like 98% to perfection, I'm hoping the next test solidifies everything as being 100% as designed/expected.

**Comment by Martinski4GitHub** [comment]
> > 
> > Yeah, that sounds like it should work since the rule remains active and should run, but it's no longer a prerequisite for merging "develop" into the "main" branch.
> 
> It's all a learning curve, but we are like 98% to perfection, I'm hoping the next test solidifies everything as being 100% as designed/expected.
>
Oh, yeah, absolutely. And I'd bet that we're using perhaps only about 20% of the full capabilities in GitHub (if we're lucky).

**Comment by ExtremeFiretop** [comment]
> > > Yeah, that sounds like it should work since the rule remains active and should run, but it's no longer a prerequisite for merging "develop" into the "main" branch.
> > 
> > 
> > It's all a learning curve, but we are like 98% to perfection, I'm hoping the next test solidifies everything as being 100% as designed/expected.
> 
> Oh, yeah, absolutely. And I'd bet that we're using perhaps only about 20% of the full capabilities in GitHub (if we're lucky).

Everytime I look for a feature I can seem to find it in the GitHub desktop app if it isn't in the webUI.

For example I had accidentally uploaded my 1.1.0 to the wrong branch and updated the dev branch with my changes instead of 1.1.0

I freaked out for a second, looked online couldn't find a rollback or undo for a specific commit (merges from PRs is no problem online)

So I opened the desktop app, and bamn right there at the top of my screen was my latest mistake of a commit to dev, I right locked and hit rollback and instantly it disappeared from GitHub web.

Absolutely love some of the more "advanced" control of the GitHub App and CLI.

We may only be using 20% of GitHub, but for our use case I can't possibly see a reason to use anymore lol.

**Pull request merged**
