### PR TITLE
Dev 1.0.5 Targeted as Next Stable Release

### PR DESCRIPTION
**Pull request by ExtremeFiretop**
MerlinAU Version 1.0.5 released.

What's Changed/Fixed?
PR: [132 ](https://github.com/ExtremeFiretop/MerlinAutoUpdate-Router/pull/132)- Redirect Unzip Output to the logs.

PR: [133](https://github.com/ExtremeFiretop/MerlinAutoUpdate-Router/pull/133) - Menu Patch for clarity and remove the possibility of confusing language.

PR: [136](https://github.com/ExtremeFiretop/MerlinAutoUpdate-Router/pull/136) - Added email notification on failure to decompress F/W ZIP file. (Thanks @Martinski4GitHub )
Also added logging of F/W ZIP file contents. General tightening up some code & general code improvements.

PR: [138](https://github.com/ExtremeFiretop/MerlinAutoUpdate-Router/pull/138) and [139](https://github.com/ExtremeFiretop/MerlinAutoUpdate-Router/pull/139) in relation to bug Fixes for the Cron Job Translations I made. (Thanks @Martinski4GitHub )

PR: https://github.com/ExtremeFiretop/MerlinAutoUpdate-Router/pull/142 Reworked the cron translation and improved validation of entered cron schedules (Thanks @Martinski4GitHub )

As always, we highly recommend you update whenever possible. Enjoy the new release!

### CODE REVIEW

**Comment by ExtremeFiretop** [comment]
You are now a code owner btw as per github! I had to make a codeowners file.
Turned on Auto-Merge. Feel free to sneak any last PR's in dev if you want before merging, else the merge button is all yours to go live! ;)

**Comment by ExtremeFiretop** [comment]
@Martinski4GitHub 

Btw when you hit merge, lets monitor the workflow to make sure it correctly tags and marks this as a release.

**Comment by Martinski4GitHub** [comment]
> @Martinski4GitHub
> 
> You are now a code owner btw as per github! I had to make a codeowners file. Turned on Auto-Merge. Feel free to sneak any last PR's in dev if you want before merging, else the merge button is all yours to go live! ;)
>
I'm about to submit a PR for the "Cron Job Schedule" validator function & changes to the translation function.
I'd like you to review & verify that it's all working well on your side and get the expected results.
I've been testing the changes myself but I need a 2nd pair of eyes to double-check.

**Comment by ExtremeFiretop** [comment]
> > @Martinski4GitHub
> > You are now a code owner btw as per github! I had to make a codeowners file. Turned on Auto-Merge. Feel free to sneak any last PR's in dev if you want before merging, else the merge button is all yours to go live! ;)
> 
> I'm about to submit a PR for the "Cron Job Schedule" validator function & changes to the translation function. I'd like you to review & verify that it's all working well on your side and get the expected results. I've been testing the changes myself but I need a 2nd pair of eyes to double-check.

No worries I'm actually around doing some scripting for a work release (Powershell stuff) submit it this way when your done and I'll validate the functionality before merging into dev (just since we have this pending)

Once it's in dev it instantly gets added to this PR.

**Comment by ExtremeFiretop** [comment]
@Martinski4GitHub 

Updated change-notes. One last PR before the release! :)

**Comment by ExtremeFiretop** [comment]
@Martinski4GitHub 

I'm done for the night when it comes to work :) Feel free to merge this whenever your ready, I'm being summoned by my higher power!

**Comment by Martinski4GitHub** [comment]
>
> I'm done for the night when it comes to work buddy :) Feel free to merge this whenever your ready, I'm being summoned by my higher power!
>
My apologies for the delay. I found a possible issue so I was looking into it and time just flew by. 
But I got it handled now and I'm currently testing everything again. Once I'm done, I'm going to submit another PR and will need you to review & validate it again tomorrow when you have time with your usual thorough testing. If you're happy with all the results you can go ahead and merge it, and then make a release anytime you feel ready. 

You don't need to wait for me as I'll be busy tomorrow with my day job commitments that I need to take care of first.

Have a good night, buddy.

**Comment by ExtremeFiretop** [comment]
> > I'm done for the night when it comes to work buddy :) Feel free to merge this whenever your ready, I'm being summoned by my higher power!
> 
> My apologies for the delay. I found a possible issue so I was looking into it and time just flew by. But I got it handled now and I'm currently testing everything again. Once I'm done, I'm going to submit another PR and will need you to review & validate it again tomorrow when you have time with your usual thorough testing. If you're happy with all the results you can go ahead and merge it, and then make a release anytime you feel ready.
> 
> You don't need to wait for me as I'll be busy tomorrow with my day job commitments that I need to take care of first.
> 
> Have a good night, buddy.

Sounds good buddy no worries! Take your time!

What was the issue? Was it related to the latest PR? How is that possible when everything correctly worked in our tests? Lol!

**Comment by Martinski4GitHub** [comment]
> 
> Sounds good buddy no worries! Take your time!
> 
> What was the issue? Was it related to the latest PR? How is that possible when everything correctly worked in our tests? Lol!
>
I ran our script through the custom Linter tool we use for work (which is customized to check against the company's coding standards, one for every programming language our various s/w dev. teams use), and it flagged the following syntax:

`month_text="$(echo "$month_text" | tr [A-Z] [a-z])"`

There are 2 recommended coding standards:

`month_text="$(echo "$month_text" | tr '[:upper:]' '[:lower:]')"`

`month_text="$(echo "$month_text" | tr 'A-Z' 'a-z')"`

The first one applies to a full Linux Bash interpreter using the full GNU tools, so it doesn't work in ASUS routers.
The 2nd syntax is the next level down which works in our routers so that's what I changed all instances to.

Long story short, it was not a problem per se, but I always like to follow my company's current coding standards (as closely as possible - sometimes is not even possible because of the huge discrepancies between running on a full Linux distro vs the stripped-down, embedded version of ASUS).

Anyway, I ran all the tests again and it's all good. While doing all this, I also decided to add a small function that capitalizes the first char in the "month" & "day of the week" abbreviations (e.g. "mon" --> "Mon",  "jan" --> "Jan"). This way people won't be wondering whether their cron job failed because of the "all lowercase" names. Just one less thing to deal with. :>)

BTW, I usually run our script through the custom Linter tool at least a couple of times a week - sometimes more if a lot of code has been changed or added recently. - just to try to keep a "clean" code.

**Comment by ExtremeFiretop** [comment]
> > Sounds good buddy no worries! Take your time!
> > What was the issue? Was it related to the latest PR? How is that possible when everything correctly worked in our tests? Lol!
> 
> I ran our script through the custom Linter tool we use for work (which is customized to check against the company's coding standards, one for every programming language our various s/w dev. teams use), and it flagged the following syntax:
> 
> `month_text="$(echo "$month_text" | tr [A-Z] [a-z])"`
> 
> There are 2 recommended coding standards:
> 
> `month_text="$(echo "$month_text" | tr '[:upper:]' '[:lower:]')"`
> 
> `month_text="$(echo "$month_text" | tr 'A-Z' 'a-z')"`
> 
> The first one applies to a full Linux Bash interpreter using the full GNU tools, so it doesn't work in ASUS routers. The 2nd syntax is the next level down which works in our routers so that's what I changed all instances to.
> 
> Long story short, it was not a problem per se, but I always like to follow my company's current coding standards (as closely as possible - sometimes is not even possible because of the huge discrepancies between running on a full Linux distro vs the stripped-down, embedded version of ASUS).
> 
> Anyway, I ran all the tests again and it's all good. While doing all this, I also decided to add a small function that capitalizes the first char in the "month" & "day of the week" abbreviations (e.g. "mon" --> "Mon", "jan" --> "Jan"). This way people won't be wondering whether their cron job failed because of the "all lowercase" names. Just one less thing to deal with. :>)
> 
> BTW, I usually run our script through the custom Linter tool at least a couple of times a week - sometimes more if a lot of code has been changed or added recently. - just to try to keep a "clean" code.

Your good, you always deserve 5 stars buddy, no joke.
Of course it has to flag my line *rolls eyes*. That's okay though, I live and learn. At least I didn't actually case a bug.

You even addressed the lower case abbreviations (sorry for the embarrassing mistake on my part!)

I think that's also a hurdle for me, the fact that these aren't full Linux systems and are embedded systems instead, some functions I know for a fact work on my VM in shell break on our routers and that just ads to all my fun lol!

I basically stopped testing on my VM some time ago because it wasn't a good apples to apple comparison I was adding code that wasn't compatible or fully compatible without extra software, etc lol.

At some point I just move on to testing the functions on the actual router itself, but if course that's carries a little more risk if something goes wrong than a VM (which was my original reason for setting it up. )

However really the worse that's happened in testing on the router itself is I've felt the script in debug mode when going to bed and it actually does the things on the router lol! But hasn't broken it so who doesn't like a little re-flash once in a while right? Lol

I'm off to bed, have a goodnight my friend, chat soon, I know you'll be busy tomorrow so no rush for the next release (whenever it is)!

**Comment by ExtremeFiretop** [comment]
> > Sounds good buddy no worries! Take your time!
> > What was the issue? Was it related to the latest PR? How is that possible when everything correctly worked in our tests? Lol!
> 
> I ran our script through the custom Linter tool we use for work (which is customized to check against the company's coding standards, one for every programming language our various s/w dev. teams use), and it flagged the following syntax:
> 
> `month_text="$(echo "$month_text" | tr [A-Z] [a-z])"`
> 
> There are 2 recommended coding standards:
> 
> `month_text="$(echo "$month_text" | tr '[:upper:]' '[:lower:]')"`
> 
> `month_text="$(echo "$month_text" | tr 'A-Z' 'a-z')"`
> 
> The first one applies to a full Linux Bash interpreter using the full GNU tools, so it doesn't work in ASUS routers. The 2nd syntax is the next level down which works in our routers so that's what I changed all instances to.
> 
> Long story short, it was not a problem per se, but I always like to follow my company's current coding standards (as closely as possible - sometimes is not even possible because of the huge discrepancies between running on a full Linux distro vs the stripped-down, embedded version of ASUS).
> 
> Anyway, I ran all the tests again and it's all good. While doing all this, I also decided to add a small function that capitalizes the first char in the "month" & "day of the week" abbreviations (e.g. "mon" --> "Mon", "jan" --> "Jan"). This way people won't be wondering whether their cron job failed because of the "all lowercase" names. Just one less thing to deal with. :>)
> 
> BTW, I usually run our script through the custom Linter tool at least a couple of times a week - sometimes more if a lot of code has been changed or added recently. - just to try to keep a "clean" code.

Linters, such fancy tools, but @Martinski4Github you are my linter! Your linter didn't know which of the 2 was best, you did, your the ultimate linter 😜

**Comment by ExtremeFiretop** [comment]
@Martinski4GitHub 

The workflow didn't work originally, I had to make a few changes:

1. Update the name to include .yml: https://github.com/ExtremeFiretop/MerlinAutoUpdate-Router/commit/5237ff6a997b0b228dff15855a6e41474bef4464

2. Resolve issues with: set-output command is being deprecate
https://github.com/ExtremeFiretop/MerlinAutoUpdate-Router/commit/0f11a624d9c4e4e7fcc61f80aa1701f24cc56aea

3. Resolve issues with: Node 16 reaching its end of life 
https://github.com/ExtremeFiretop/MerlinAutoUpdate-Router/commit/c9446d9e3c73d059625a5370568bb50e170c0ac2

4. Resolved issues with: lack of permission to create release
https://github.com/ExtremeFiretop/MerlinAutoUpdate-Router/commit/52e25a49f9e6c3af53495484b0dabcdf278d31ce

**Comment by Martinski4GitHub** [comment]
> 
> The workflow didn't work originally, I had to make a few changes:
> 
Good job man!! You got it to work like you wanted.

**Comment by ExtremeFiretop** [comment]
> > The workflow didn't work originally, I had to make a few changes:
> 
> Good job man!! You got it to work like you wanted.

I knew you were gonna be busy that day so I just figured I'd take my time testing and then release when I was happy as you said :)
Now tagging specific releases and making releases is one less thing to worry about :)

(As long as everything continues to work going forwards!) I'll monitor the next release or two to be sure before I completely drop my guide lol!

**Pull request merged**
