### PR TITLE
Dev 1.3.4 at Next Stable Release

### PR DESCRIPTION
**Pull request by ExtremeFiretop**
MerlinAU 1.3.4 Released!

What's Changed/Fixed?:

PR: [ [#346 ](https://github.com/ExtremeFiretop/MerlinAutoUpdate-Router/pull/346)]
Blocked Versions and Documentation Updated. Rather be safe then sorry. 
Models added to the block list include:  **RT-AC1900P, RT-N16, RT-AC68UF, RT-AC68P**

Updated Wiki: https://github.com/ExtremeFiretop/MerlinAutoUpdate-Router/wiki
To document new additional features.

As always, we highly recommend you update ASAP as this includes functional improvements and little bug fixes.

### CODE REVIEW

**Comment by ExtremeFiretop** [comment]
All good to go on my side.

The 3 important things are ready:

1. Forms post update
2. Readme update
3. Version.txt update

Activating Auto-merge on this PR for automatic merge once approved :)

**Comment by ExtremeFiretop** [comment]
@Martinski4GitHub 

Workflow worked perfectly this time! :)

**Comment by Martinski4GitHub** [comment]
> All good to go on my side.
> 
> The 3 important things are ready:
> 
>     1. Forms post update
>     2. Readme update
>     3. Version.txt update
> 
> Activating Auto-merge on this PR for automatic merge once approved :)
>
>
Apologies for the late response. I've been very busy with work (and putting in some "overtime") since Monday, so when I come home I'm just ready to take a short nap, have dinner, try to relax & decompress while watching some TV show or movie, and then go to sleep. But things are finally getting "under control" now, so it should be more "normal" work from here on out (until the next "fire" to put out rises).

Anyway, I'm glad the latest workflow changes worked successfully this time. Great job, bud!!

**Comment by ExtremeFiretop** [comment]
> > All good to go on my side.
> > The 3 important things are ready:
> > ```
> > 1. Forms post update
> > 2. Readme update
> > 3. Version.txt update
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Activating Auto-merge on this PR for automatic merge once approved :)
> 
> Apologies for the late response. I've been very busy with work (and putting in some "overtime") since Monday, so when I come home I'm just ready to take a short nap, have dinner, try to relax & decompress while watching some TV show or movie, and then go to sleep. But things are finally getting "under control" now, so it should be more "normal" work from here on out (until the next "fire" to put out rises).
> 
> Anyway, I'm glad the latest workflow changes worked successfully this time. Great job, bud!!

Totally understand. Been there done that! 

My time acting finished so I've been getting some free time back again as well :)

And yes! Very happy to see the workflow is finally working as intended!

**Comment by Martinski4GitHub** [comment]
> MerlinAU 1.3.4 Released!
> 
> What's Changed/Fixed?:
> 
> PR: [ [#346 ](https://github.com/ExtremeFiretop/MerlinAutoUpdate-Router/pull/346)] Blocked Versions ... 
> 
>
I know what you meant above because I'm privy to the PRs and our conversations, but I think for outside users the phrase "Blocked Versions" can be confusing or misleading. I would prefer the phrase "Blocked unsupported router models" to make it crystal clear, especially in the message intended for SNB Forums users.

My 2 cents.

**Comment by ExtremeFiretop** [comment]
> > MerlinAU 1.3.4 Released!
> > What's Changed/Fixed?:
> > PR: [ [#346 ](https://github.com/ExtremeFiretop/MerlinAutoUpdate-Router/pull/346)] Blocked Versions ...
> 
> I know what you meant above because I'm privy to the PRs and our conversations, but I think for outside users the phrase "Blocked Versions" can be confusing or misleading. I would prefer the phrase "Blocked unsupported router models" to make it crystal clear, especially in the message intended for SNB Forums users.
> 
> My 2 cents.

Done!

**Comment by ExtremeFiretop** [comment]
I'm assuming you don't have much "winter prep" to do where you are? Do you get cold weather?

**Comment by Martinski4GitHub** [comment]
> I'm assuming you don't have much "winter prep" to do where you are? Do you get cold weather?
>
Not much "winter prep" is really needed around here, except to make sure the windows and door frames have been properly sealed & insulated with caulking, weather strips & whatnot.  And, of course, take out the heavy winter jackets, sweaters & coats. The coldest it gets here is around ~40°F unless you go to the mountains.

**Comment by ExtremeFiretop** [comment]
> > I'm assuming you don't have much "winter prep" to do where you are? Do you get cold weather?
> 
> Not much "winter prep" is really needed around here, except to make sure the windows and door frames have been properly sealed & insulated with caulking, weather strips & whatnot. And, of course, take out the heavy winter jackets, sweaters & coats. The coldest it gets here is around ~40°F unless you go to the mountains.

I'm jealous! Only 40F! That's not even freezing! While I'm getting free time back from work, I'm busy doing the yearly prep around the place. We have to cover plants. Take down AC units/cover them. Also seal windows and door frames. Get the heat turned on (in this buildings it's boilers to heat) get the winter tires on rims and mount those, etc.

It's always the sign that the winter is coming. It can get as low as -40C here, at that point you also usually want to get a heating block for your car. It's a fun time of year...

**Comment by Martinski4GitHub** [comment]
> > > I'm assuming you don't have much "winter prep" to do where you are? Do you get cold weather?
> > 
> > 
> > Not much "winter prep" is really needed around here, except to make sure the windows and door frames have been properly sealed & insulated with caulking, weather strips & whatnot. And, of course, take out the heavy winter jackets, sweaters & coats. The coldest it gets here is around ~40°F unless you go to the mountains.
> 
> I'm jealous! Only 40F! That's not even freezing! While I'm getting free time back from work, I'm busy doing the yearly prep around the place. We have to cover plants. Take down AC units/cover them. Also seal windows and door frames. Get the heat turned on (in this buildings it's boilers to heat) get the winter tires on rims and mount those, etc.
> 
> It's always the sign that the winter is coming. It can get as low as -40C here, at that point you also usually want to get a block heater for your car. It's a fun time of year...
>
>
I know what you mean, bud. I have relatives who live in areas where it gets freezing cold & snowstorms!! And I've been there visiting when they're "prepping" for the winter months. But even then, they say they would not live anywhere else.

I do prefer cold weather over summer heat any time & every time; but freezing cold?? Not for me, thanks :>).

As mentioned before, I was raised in Southern California so my body has never acclimated to temperatures below 32°F LOL!!! :>). Even though I did my undergraduate & graduate studies in the Midwest of the US (Illinois & Michigan), I never really got accustomed to "freezing my balls off." LOL :>). I'm all in for temperate coastal weather.

**Comment by Martinski4GitHub** [comment]
@ExtremeFiretop,
About to start watching a movie with the wife. Talk to you later or tomorrow.
Take care, bud.

**Comment by ExtremeFiretop** [comment]
> 
> I do prefer cold weather over summer heat any time & every time; but freezing cold?? Not for me, thanks :>).

I I'm the same way, I prefer the cold over the heat, it's easier to deal with the cold to heat up than it is with the heat to cool down.

But then again, anything colder than -20 and it hurts to be outside no matter where your born hahaha! I also noticed sure if I'd live anywhere else. Most places I've seen that stay warm all year have other issues. (Such as tropical storms) Which we don't have here.

I rather just shovel snow than risk having my roof blow away in that sense I guess! 🤣 It still sucks however you slice it.

> 
> As mentioned before, I was raised in Southern California so my body has never acclimated to temperatures below 32°F LOL!!! :>). Even though I did my undergraduate & graduate studies in the Midwest of the US (Illinois & Michigan), I never really got accustomed to "freezing my balls off." LOL :>). I'm all in for temperate coastal weather.

Winter sports can be a good way to ignore the cold, but only for a few hours. Have you ever tried skiing or snowboarding while visiting relatives? 

I learned to snowboard but mostly just to have an excuse to snowmobile up a steep hill haha! 😆

**Comment by ExtremeFiretop** [comment]
> @ExtremeFiretop, About to start watching a movie with the wife. Talk to you later or tomorrow. Take care, bud.

No worries! Sorry for the delay, was out grabbing some food. Enjoy the movie!

**Comment by Martinski4GitHub** [comment]
> > I do prefer cold weather over summer heat any time & every time; but freezing cold?? Not for me, thanks :>).
> 
> I I'm the same way, I prefer the cold over the heat, it's easier to deal with the cold to heat up than it is with the heat to cool down.
> 
>
Exactly!! Jackets, sweaters & coats, brother!!! And then a nice cup of hot coffee or chocolate with cinnamon and a little milk, and you're in heaven!! :>).

>
> But then again, anything colder than -20 and it hurts to be outside no matter where your born hahaha! 
>
At that temperature, it's just brutal torture & inhumane to be outside, LOL!!!

>
> I also noticed sure if I'd live anywhere else. Most places I've seen that stay warm all year have other issues. (Such as tropical storms) Which we don't have here.
> 
> I rather just shovel snow than risk having my roof blow away in that sense I guess! 🤣 It still sucks however you slice it.
>
>
I hear you, bud!!

>
>
> > As mentioned before, I was raised in Southern California so my body has never acclimated to temperatures below 32°F LOL!!! :>). Even though I did my undergraduate & graduate studies in the Midwest of the US (Illinois & Michigan), I never really got accustomed to "freezing my balls off." LOL :>). I'm all in for temperate coastal weather.
> 
> Winter sports can be a good way to ignore the cold, but only for a few hours. Have you ever tried skiing or snowboarding while visiting relatives?
> 
> I learned to snowboard but mostly just to have an excuse to snowmobile up a steep hill haha! 😆
>
>
I have tried skiing and riding a rented snowmobile before. They're fun to do, but I'm not sure it's something that I'd like to do as a sport. I prefer playing indoor sports where you have climate control (i.e. basketball, racketball, swimming, etc.) so you can do them all year round.

**Comment by ExtremeFiretop** [comment]
> 
> I have tried skiing and riding a rented snowmobile before. They're fun to do, but I'm not sure it's something that I'd like to do as a sport. I prefer playing indoor sports where you have climate control (i.e. basketball, racketball, swimming, etc.) so you can do them all year round.

I was thinking about it earlier today, but you said you were near the coast right? What about what sports? Like water skiing or water boarding? Wake boarding/surfing?

Those are kinda similar right? I've never actually tried anything more than wake boarding lol

**Comment by Martinski4GitHub** [comment]
> > I have tried skiing and riding a rented snowmobile before. They're fun to do, but I'm not sure it's something that I'd like to do as a sport. I prefer playing indoor sports where you have climate control (i.e. basketball, racketball, swimming, etc.) so you can do them all year round.
> 
> I was thinking about it earlier today, but you said you were near the coast right? What about what sports? Like water skiing or water boarding? Wake boarding/surfing?
> 
> Those are kinda similar right? I've never actually tried anything more than wake boarding lol
>
>
Even though I've lived near a beach for most of my life, I've never tried any of those sports, LOL!! :>)
Once I started working full time, got married, had kids, etc., my spare time got really short to play sports of any kind. I did join a local gym some time ago with a promotion, and on the weekends I enjoyed swimming in the indoor pool for 30 minutes or so. I also found a friend and played racketball whenever we were in the gym a the same time.

**Comment by ExtremeFiretop** [comment]
@102.2 officially released. 

Not many people with the 4 new router models but we are about to be tested!

So far, everyone reporting that the flash is working correctly!

**Comment by ExtremeFiretop** [comment]
@Martinski4GitHub 

102.2 officially released. 

Not many people with the 4 new router models but we are about to be tested!

So far, everyone reporting that the flash is working correctly!

**Comment by Martinski4GitHub** [comment]
> @Martinski4GitHub
> 
> 102.2 officially released.
> 
> Not many people with the 4 new router models but we are about to be tested!
> 
> So far, everyone reporting that the flash is working correctly!
>
Among the few people who have one of the 4 router models currently supported by the 3006.102.xx F/W, I'm wondering how many are using the MerlinAU script. Getting real-life testing is always good, but perhaps not too many installations around this new F/W.

**Comment by ExtremeFiretop** [comment]
> > @Martinski4GitHub
> > 102.2 officially released.
> > Not many people with the 4 new router models but we are about to be tested!
> > So far, everyone reporting that the flash is working correctly!
> 
> Among the few people who have one of the 4 router models currently supported by the 3006.102.xx F/W, I'm wondering how many are using the MerlinAU script. Getting real-life testing is always good, but perhaps not too many installations around this new F/W.

I know of me and Tom ([visortgw](https://www.snbforums.com/members/visortgw.41161/)) so far! :) Lol

**Comment by Martinski4GitHub** [comment]
> > > @Martinski4GitHub
> > > 102.2 officially released.
> > > Not many people with the 4 new router models but we are about to be tested!
> > > So far, everyone reporting that the flash is working correctly!
> > 
> > 
> > Among the few people who have one of the 4 router models currently supported by the 3006.102.xx F/W, I'm wondering how many are using the MerlinAU script. Getting real-life testing is always good, but perhaps not too many installations around this new F/W.
> 
> I know of me and Tom ([visortgw](https://www.snbforums.com/members/visortgw.41161/)) so far! :) Lol
>
LOL!!😉 At least that's better than ZERO users!!!
I'm guessing there are not many Gnuton installations yet either. Perhaps next year, as the BE-class routers get more popular and less expensive, there will be an uptick in router installs.

**Comment by ExtremeFiretop** [comment]
> > > > @Martinski4GitHub
> > > > 102.2 officially released.
> > > > Not many people with the 4 new router models but we are about to be tested!
> > > > So far, everyone reporting that the flash is working correctly!
> > > 
> > > 
> > > Among the few people who have one of the 4 router models currently supported by the 3006.102.xx F/W, I'm wondering how many are using the MerlinAU script. Getting real-life testing is always good, but perhaps not too many installations around this new F/W.
> > 
> > 
> > I know of me and Tom ([visortgw](https://www.snbforums.com/members/visortgw.41161/)) so far! :) Lol
> 
> LOL!!😉 At least that's better than ZERO users!!! I'm guessing there are not many Gnuton installations yet either. Perhaps next year, as the BE-class routers get more popular and less expensive, there will be an uptick in router installs.

We have actually a decent amount of Installs on Gnuton, I think people on Gnuton are more excited because of the fact that their update schedules aren't so consistent as Merlin.

I'm the case of Gnuton, we are still waiting for a new update since we officially added Gnuton support.

I'm still waiting to see the first wave of Gnuton users test once Gnuton actually makes a new release

**Pull request merged**
