### PR TITLE
Some code improvements.

### PR DESCRIPTION
**Pull request by Martinski4GitHub**
Just some minor code improvements.

### CODE REVIEW

**Comment by Martinski4GitHub** [comment]
@ExtremeFiretop,

This evening, I ran our script through the Linter tool and the code came out "clean" (i.e. no code was flagged for possible issues). However, I did review some new "warnings" that came out (there was a new release version of the Linter tool last week), and there was nothing major but I ended up making some minor code improvements to remove those warnings.

Also, see the additional line `FlashStarted=false` after returning to the Main Menu. I think this was needed in such cases.

Please review and comment as needed.

**Comment by ExtremeFiretop** [comment]
> @ExtremeFiretop,
> 
> This evening, I ran our script through the Linter tool and the code came out "clean" (i.e. no code was flagged for possible issues). However, I did review some new "warnings" that came out (there was a new release version of the Linter tool last week), and there was nothing major but I ended up making some minor code improvements to remove those warnings.
> 
> Also, see the additional line `FlashStarted=false` after returning to the Main Menu. I think this was needed in such cases.
> 
> Please review and comment as needed.

I just pumped out a release but luckily I don't think this is anything major either, much appreciate you running it through the linter tool!

I'll sync up Gnuton in a moment, did you happen to run the Gnuton branch through this new version of the linter tool?

**Review by ExtremeFiretop — APPROVED** [review]

**Comment by Martinski4GitHub** [comment]
>
> 
> I'll sync up Gnuton in a moment, did you happen to run the Gnuton branch through this new version of the linter tool?
>
>
No, I haven't done that in a while. I'll do it sometime this week & let you know.
This evening I'll try to address the remaining webGUI issues with **scMerlin** & **YazDHCP** add-ons (I'll send you a PM about that).

**Comment by ExtremeFiretop** [comment]
And here:

https://github.com/ExtremeFiretop/MerlinAutoUpdate-Router/pull/186/commits/1c62b1ad4a5680b0b0198b445eca754032746b33

**Pull request merged**
