### PR TITLE
More fixes & code improvements

### PR DESCRIPTION
**Pull request by Martinski4GitHub**
Some additional fixes, code improvements & fine-tuning.

### CODE REVIEW

**Review by ExtremeFiretop — APPROVED** [review]

**Comment by ExtremeFiretop** [comment]
I won't say the combination here, but it works perfectly!

**Comment by Martinski4GitHub** [comment]
> I won't say the combination here, but it works perfectly!
>
Excellent. Thanks for testing & verifying. And yeah, I think we should start being careful about spreading "too much detailed info" about it ;>).

**Comment by Martinski4GitHub** [comment]
@ExtremeFiretop,

Today, while talking with my friend at work about MerlinAU, he mentioned that the option to keep remote VPN access (e.g. Tailscale) "alive" as long as possible during F/W updates was a very good idea, and he suggested adding **ZeroTier** as well, and possibly **OpenSSH**. He knows several people who use ZeroTier to access remote routers (not always ASUS models), and a few people using OpenSSH rather than Dropbear for remote SSH access (I actually use OpenSSH for work access via OpenVPN, and have an OpenSSH server on my own ASUS router).

What do you think about his suggestion?

I think he has good points. I've seen some people on the SNB Forums who have installed ZeroTier on their routers, so it may be just a matter of time before one of them wants to run MerlinAU via their ZeroTier network. Installing OpenSSH on the router seems extremely rare (so far) since it requires much more effort and knowledge to do it, so I'd say the chances of that use-case are extremely low.

I've already modified my local copy of the script and tested it with OpenSSH, and it works just like with Tailscale. Without the changes, the OpenSSH session could have been terminated too early before reaching the actual F/W flash.

**Comment by ExtremeFiretop** [comment]
> @ExtremeFiretop,
> 
> Today, while talking with my friend at work about MerlinAU, he mentioned that the option to keep remote VPN access (e.g. Tailscale) "alive" as long as possible during F/W updates was a very good idea, and he suggested adding **ZeroTier** as well, and possibly **OpenSSH**. He knows several people who use ZeroTier to access remote routers (not always ASUS models), and a few people using OpenSSH rather than Dropbear for remote SSH access (I actually use OpenSSH for work access via OpenVPN, and have an OpenSSH server on my own ASUS router).
> 
> What do you think about his suggestion?
> 
> I think he has good points. I've seen some people on the SNB Forums who have installed ZeroTier on their routers, so it may be just a matter of time before one of them wants to run MerlinAU via their ZeroTier network. Installing OpenSSH on the router seems extremely rare (so far) since it requires much more effort and knowledge to do it, so I'd say the chances of that use-case are extremely low, but still possible.
> 
> I've already modified my local copy of the script and tested it with OpenSSH, and it works just like with Tailscale. Without the changes, the OpenSSH session could have been terminated too early before reaching the actual F/W flash.

I believe it should be an easy addition, we would just need to reword the option back again from "Toggle Tailscale" back to "Toggle VPN Access" if we are to include more VPN solutions, also, we should list all the VPN solutions we are keeping alive with this feature in the toggle menu.

But as long as it's just adding some more services to skip, I don't see this as an issue at all. If I remember correct, we had already made the skipped services list a space separated list incase we decided to add more some day.

**Comment by ExtremeFiretop** [comment]
Keep in mind I don't have any of those solutions setup to test though

**Comment by Martinski4GitHub** [comment]
> Keep in mind I don't have any of those solutions setup to test though
>
>
OK, I've submitted PR #278. When we discussed his suggestions, my friend offered to test & verify the changes with ZeroTier (which I don't have installed). He usually gets back to me with feedback within 24 hours.

**Comment by ExtremeFiretop** [comment]
> > Keep in mind I don't have any of those solutions setup to test though
> 
> OK, I've submitted PR #278. When we discussed his suggestions, my friend offered to test & verify the changes with ZeroTier (which I don't have installed). He usually gets back to me with feedback within 24 hours.

No rush! I merged it into dev already in case it's easier for him to test.

But let me know the results in your PR ;)

**Comment by Martinski4GitHub** [comment]
> > > Keep in mind I don't have any of those solutions setup to test though
> > 
> > 
> > OK, I've submitted PR #278. When we discussed his suggestions, my friend offered to test & verify the changes with ZeroTier (which I don't have installed). He usually gets back to me with feedback within 24 hours.
> 
> No rush! I merged it into dev already in case it's easier for him to test.
> 
>
Sorry, I didn't specify that my friend already has the URL for the 'develop' branch of my GitHub repository so he can download the script from there for testing & validation purposes. He said he would send me his feedback either tonight or tomorrow.

>
> But let me know the results in your PR ;)
>
Will do. I hope you're having a very good evening & a great weekend, bud.

P.S.
Just FYI, this evening we're going out to dinner with the family and then watch a movie so I'll be offline until very late tonight.

**Comment by ExtremeFiretop** [comment]
> Will do. I hope you're having a very good evening & a great weekend, bud.

It's been okay, I'm about to give up on helping Viktor at this point because I've reworked it so many times and the user is still having issues, I'm not sure If i'm just not understanding the requirements correctly of if it's a moving target but im out of steam.

> 
> P.S. Just FYI, this evening we're going out to dinner with the family and then watch a movie so I'll be offline until very late tonight.

No worries, I just woke up cause the girlfriend was kicking me in her sleep, so I figured I'd spend an hour or so syncing up some changes to Gnuton and doing a quick review of some of the latest code.

**Comment by ExtremeFiretop** [comment]
Hope the movie was good!

**Comment by Martinski4GitHub** [comment]
> Hope the movie was good!
>
After going out for an early dinner, we watched "Oppenheimer." It was good and a long one (almost 3 hours).

**Comment by ExtremeFiretop** [comment]
> > Hope the movie was good!
> 
> After going out for an early dinner, we watched "Oppenheimer." It was good and a long one (almost 3 hours).

Good movie! Have it on Plex 😜

**Comment by Martinski4GitHub** [comment]
> > Will do. I hope you're having a very good evening & a great weekend, bud.
> 
> It's been okay, I'm about to give up on helping Viktor at this point because I've reworked it so many times and the user is still having issues, I'm not sure If i'm just not understanding the requirements correctly or if it's a moving target but im out of steam.
> 
>
It's more challenging when you might not completely know what's "behind the curtain" and trying to find a solution. IOW, it's like trying to understand what's inside a "black box" when all you have seen is one blurry snapshot. Or, there may be more moving parts that contribute to the functionality that you're trying to wrap your head around.

**Comment by ExtremeFiretop** [comment]
> > > Will do. I hope you're having a very good evening & a great weekend, bud.
> > 
> > 
> > It's been okay, I'm about to give up on helping Viktor at this point because I've reworked it so many times and the user is still having issues, I'm not sure If i'm just not understanding the requirements correctly or if it's a moving target but im out of steam.
> 
> It's more challenging when you might not completely know what's "behind the curtain" and trying to find a solution. IOW, it's like trying to understand what's inside a "black box" when all you have seen is one blurry snapshot. Or, there may be more moving parts that contribute to the functionality that you're trying to wrap your head around.

I feel I get something working for me, but then he tries it and has completely different results.
I troubleshooted until I noticed my methodology for identifying which client lands in which VLAN was wrong and not reliable enough, so I changed it, now we are having a completely different set of issues... Like ugh

I agree part of the issue is lack of knowledge of what is happening behind the curtain, the other issue is the pure variations of configurations people can use. Having a single "methodology" for all of them isn't really working out how we might of expected.

**Comment by Martinski4GitHub** [comment]
> > > > Will do. I hope you're having a very good evening & a great weekend, bud.
> > > 
> > > 
> > > It's been okay, I'm about to give up on helping Viktor at this point because I've reworked it so many times and the user is still having issues, I'm not sure If i'm just not understanding the requirements correctly or if it's a moving target but im out of steam.
> > 
> > 
> > It's more challenging when you might not completely know what's "behind the curtain" and trying to find a solution. IOW, it's like trying to understand what's inside a "black box" when all you have seen is one blurry snapshot. Or, there may be more moving parts that contribute to the functionality that you're trying to wrap your head around.
> 
> I feel I get something working for me, but then he tries it and has completely different results. I troubleshooted until I noticed my methodology for identifying which client lands in which VLAN was wrong and not reliable enough, so I changed it, now we are having a completely different set of issues... Like ugh
> 
> I agree part of the issue is lack of knowledge of what is happening behind the curtain, the other issue is the pure variations of configurations people can use. Having a single "methodology" for all of them isn't really working out how we might of expected.
>
>
Perhaps there are many more moving parts that you still have to figure out to be able to clearly "see the pattern" of all the different variations.

**Comment by ExtremeFiretop** [comment]
> > > > > Will do. I hope you're having a very good evening & a great weekend, bud.
> > > > 
> > > > 
> > > > It's been okay, I'm about to give up on helping Viktor at this point because I've reworked it so many times and the user is still having issues, I'm not sure If i'm just not understanding the requirements correctly or if it's a moving target but im out of steam.
> > > 
> > > 
> > > It's more challenging when you might not completely know what's "behind the curtain" and trying to find a solution. IOW, it's like trying to understand what's inside a "black box" when all you have seen is one blurry snapshot. Or, there may be more moving parts that contribute to the functionality that you're trying to wrap your head around.
> > 
> > 
> > I feel I get something working for me, but then he tries it and has completely different results. I troubleshooted until I noticed my methodology for identifying which client lands in which VLAN was wrong and not reliable enough, so I changed it, now we are having a completely different set of issues... Like ugh
> > I agree part of the issue is lack of knowledge of what is happening behind the curtain, the other issue is the pure variations of configurations people can use. Having a single "methodology" for all of them isn't really working out how we might of expected.
> 
> Perhaps there are many more moving parts that you still have to figure out to be able to clearly "see the pattern" of all the different variations.

Agreed. 
It may take more brain power, which right now I'm not providing or capable of providing.

I'm still not sure I understand what the purpose of displaying the VLANs are at all, every client has to be connected through a wireless or wired interface, if we can get all the client info from those interfaces, why are we bothering trying to see which VLAN they are in? I'm not sure I understand the goal lol

**Comment by Martinski4GitHub** [comment]
> > > > > > Will do. I hope you're having a very good evening & a great weekend, bud.
> > > > > 
> > > > > 
> > > > > It's been okay, I'm about to give up on helping Viktor at this point because I've reworked it so many times and the user is still having issues, I'm not sure If i'm just not understanding the requirements correctly or if it's a moving target but im out of steam.
> > > > 
> > > > 
> > > > It's more challenging when you might not completely know what's "behind the curtain" and trying to find a solution. IOW, it's like trying to understand what's inside a "black box" when all you have seen is one blurry snapshot. Or, there may be more moving parts that contribute to the functionality that you're trying to wrap your head around.
> > > 
> > > 
> > > I feel I get something working for me, but then he tries it and has completely different results. I troubleshooted until I noticed my methodology for identifying which client lands in which VLAN was wrong and not reliable enough, so I changed it, now we are having a completely different set of issues... Like ugh
> > > I agree part of the issue is lack of knowledge of what is happening behind the curtain, the other issue is the pure variations of configurations people can use. Having a single "methodology" for all of them isn't really working out how we might of expected.
> > 
> > 
> > Perhaps there are many more moving parts that you still have to figure out to be able to clearly "see the pattern" of all the different variations.
> 
> Agreed. It may take more brain power, which right now I'm not providing or capable of providing.
> 
> I'm still not sure I understand what the purpose of displaying the VLANs are at all, every client has to be connected through a wireless or wired interface, if we can get all the client info from those interfaces, why are we bothering trying to see which VLAN they are in? I'm not sure I understand the goal lol
>
>
Perhaps Viktor is trying to duplicate the info provided on the webGUI WRT clients on VLANs vs clients on regular LANs. But then again, I don't have a BE-class router that shows what you guys are talking about so I'm just a clueless bystander :>).

Well, I'm going to hit the sack now. Have a good night, bud. We'll talk tomorrow after my friend sends me his feedback (I told him there was no rush, but hopefully he'll have the time to test & verify).

**Comment by ExtremeFiretop** [comment]
Sleep with my friend.
As you told your buddy it's no rush. I'll have Gnuton fully synced up by the time you wake up.

Just did the bigger PR. The others should be fairly quick.

**Comment by ExtremeFiretop** [comment]
Synced with Gnuton in commit: https://github.com/ExtremeFiretop/MerlinAutoUpdate-Router/pull/186/commits/2340cb3e5a8c6fb634c9de74abff2e72335a4b00

**Pull request merged**
