### PR TITLE
Fix Future Estimates

### PR DESCRIPTION
**Pull request by ExtremeFiretop**
Fix Future Estimates

### CODE REVIEW

**Comment by ExtremeFiretop** [comment]
I basically re-did it all. :D
This time, better?

let me know :)

**Comment by ExtremeFiretop** [comment]
@Martinski4GitHub 

I basically re-did it all. :D This time, better?
let me know :)

**Comment by ExtremeFiretop** [comment]
This seems to work with cron schedules like this:

*/15 * * * *
Or like this:
0-59/15 * * * *
Or like this:
5 * * * *
Which none of these worked previously with the current method in the dev branch.

**Comment by ExtremeFiretop** [comment]
@Martinski4GitHub 

I woke up this morning and still noticed a bug with "bad number" with specific crons and I realized it was because some days would come back as "00" and my code was scrapping the first zero away, but in those cases it was scrapping all the zeros away making it a null value.

This has been resolved in commit: https://github.com/ExtremeFiretop/MerlinAutoUpdate-Router/pull/208/commits/5d6a11929f70ca774a56880c7376bd779095841e
I made the removal of the first 0 more specific and also assigned defaults incase somehow it still gets nulled somehow.

**Comment by ExtremeFiretop** [comment]
@Martinski4GitHub 

Commit: https://github.com/ExtremeFiretop/MerlinAutoUpdate-Router/pull/208/commits/04a34ac5061e4367d0befa601e14ce9a5f61cc2a

Is as per Viktors suggestion in the SNB forums.

**Comment by ExtremeFiretop** [comment]
> @ExtremeFiretop,
> 
> Apologies for the "radio silence." As you know, I was busy with family events during the weekend, and today I was busy with work commitments as well. I'll take a closer look at your latest code changes sometime this week, but I'm not sure when exactly (most likely until Wednesday evening at the earliest). After a quick look, I'd say that you're certainly honing your shell scripting skills, and that, in and of itself, is great to see. Good job bud.

I've been looking at your code since October of last year 8 months ago, surely at some point some of it has to sink in, right? lol!

**Comment by Martinski4GitHub** [comment]
@ExtremeFiretop,

This evening, I've been running tests & validation using the latest code changes. So far everything is looking good. I'm going to have dinner right now and will come back to complete the testing & my review. It's likely this PR will be merged before I go to bed tonight. Good job bud.

**Comment by ExtremeFiretop** [comment]
> @ExtremeFiretop,
> 
> This evening, I've been running tests & validation using the latest code changes. So far everything is looking good. I'm going to have dinner right now and will come back to complete the testing & my review. It's likely this PR will be merged before I go to bed tonight. Good job bud.

I'm about to go to bed myself cause as I mentioned I need to start getting myself back on a regular schedule, but if there's anything outstanding or you notice feel free to comment in a review or submit a PR and I'll see it first thing in the morning.

I did test this a bunch and it seemed to work as a cron, interactively, with no delay, with a long delay, with all types of crons. I was happy with this solution.

Thanks Martinski, Hope you've been doing good and work is treating you well, you know where to find me if you ever want to chat or discuss 😁

**Comment by Martinski4GitHub** [comment]
> 
> I'm about to go to bed myself cause as I mentioned I need to start getting myself back on a regular schedule, but if there's anything outstanding or you notice feel free to comment in a review or submit a PR and I'll see it first thing in the morning.
> 
> I did test this a bunch and it seemed to work as a cron, interactively, with no delay, with a long delay, with all types of crons. I was happy with this solution.
> 
> Thanks Martinski, Hope you've been doing good and work is treating you well, you know where to find me if you ever want to chat or discuss 😁
>
Thanks. Life & work has been good so far. This past week I was very busy with part of the planning phase of the next project so after the long hours, I took time in the evenings to relax, decompress, and spend time with the family.

Anyway, I finished testing and found no problems with my test cases. I did find some code to "clean up" and also ran the latest code through the Linter tool which pointed to some minor cleanup to do as well.

I'm going to merge this PR into the 'develop' branch and address the cleanup in a separate PR.

**Review by Martinski4GitHub — APPROVED** [review]
Approved.

**Comment by ExtremeFiretop** [comment]
> I'm going to merge this PR into the 'develop' branch and address the cleanup in a separate PR.

Thanks for the review my friend, and for testing and validating the behavior. :)
I'm awake again, it's early but it was a solid 5-6 hours, it's going in the right direction.

Feel free to submit a PR with your cleanup and take your time, and I'll review when I get it :)
I know how you feel about work, it's been randomly busy at my work as well.

I'm assuming this release can go out the door after your PR, it seems Gnuton is almost ready for his full release, but our Gnuton branch is synced up so I'll have a users do a final test with the Gnuton branch once the official firmware is released.

**Pull request merged**
