### PR TITLE
Update MerlinAU.sh

### PR DESCRIPTION
**Pull request by Martinski4GitHub**
Minor rewording & increased the size of the heading & font used for the body of the email (to help those of us with "old" eyes trying to read an email alert at 3:00 in the morning :>).

### CODE REVIEW

**Comment by Martinski4GitHub** [comment]
@ExtremeFiretop,
I'm going to go to sleep early today, so tomorrow I'll work on the new menu item to select the email format type. As mentioned, this is not critical so it's up to you if you want to wait, or if you rather issue a release of what we have so far, especially with the BackupMon versioning scheme fix.

**Review by ExtremeFiretop — APPROVED** [review]

**Comment by ExtremeFiretop** [comment]
> Minor rewording & increased the size of the heading & font used for the body of the email (to help those of us with "old" eyes trying to read an email alert at 3:00 in the morning :>).

Literally just happened to me and I don't have old eyes lol!
I kept my script in debug mode and went to bed, it's scheduled for Sundays at 4AM. So tonight. It's now early in the morning and my phone went off ding ding ding.

Wake up, check it, and the router backed up and flashed itself successfully overnight from 388.6 to 388.6 LOL.
Oh well, checked the logs and everything still clean as a can be, I made sure to return it to the production version.

But me reading the emails at 4AM was a blurry mess to say the least LOL!

**Comment by ExtremeFiretop** [comment]
> @ExtremeFiretop, I'm going to go to sleep early today, so tomorrow I'll work on the new menu item to select the email format type. As mentioned, this is not critical so it's up to you if you want to wait, or if you rather issue a release of what we have so far, especially with the BackupMon versioning scheme fix.

No worries @Martinski4GitHub enjoy and rest well buddy. Chat more when you wake up :)
We still have time, I realize the firmware release RMerlin is working on is a security fix, so it may be pumped out quickly.

But I think we still have time, I'll give it until end of the weekend. (My Time) so end of Sunday, else I'll release as is.
I think people just haven't realized backupmon is broken yet, I rather have the fix out before people do lol!

**Comment by ExtremeFiretop** [comment]
@Martinski4GitHub 

FYI: I touched up backupmon messaging for the logs in commit: https://github.com/ExtremeFiretop/MerlinAutoUpdate-Router/commit/685cd721b8498c404b5234f9fc50a2694d98c84b

Only reason was to cleanup the messages in the logs as found below:

> 2024-02-18 04:00:33 \nBackup Started (by BACKUPMON)
> 2024-02-18 04:02:05 Backup Finished\n
> 2024-02-18 04:02:05 Backup Completed Successfully\n

I also noticed I forgot to up the minimum version in the error message from 1.44 to 1.5.3 which was updated in that commit.
Just small things, no need for a PR. But wanted you aware none the less.

**Pull request merged**
