### PR TITLE
Dev 1.2.7 as Next Stable Release

### PR DESCRIPTION
**Pull request by ExtremeFiretop**
**TASK LIST:**

1. Update Readme = COMPLETED
2. Update version.txt = COMPLETED
3. Update Script version = COMPLETED
4. Update Script Branch = COMPLETED
5. Update Forum Post = COMPLETED

MerlinAU Version 1.2.7 released.

What's Changed/Fixed?:
PR: [#271](https://github.com/ExtremeFiretop/MerlinAutoUpdate-Router/pull/271) - Minor change to the "Help" output
-Added the ".sh" file extension to the listed script commands in the "Help" output screen to make it clear that the extension is definitely needed as part of the script filename. 
(Thanks [@Martinski4GitHub](https://github.com/Martinski4GitHub))!

PR: [#273](https://github.com/ExtremeFiretop/MerlinAutoUpdate-Router/pull/273) - Allow script to continue flashing F/W if connection is terminated.
-Made changes to allow script to continue with the F/W flash "curl" command after connection is terminated due to stopping Entware services, including TailScale.
(Thanks [@Martinski4GitHub](https://github.com/Martinski4GitHub))!

PR: [#278](https://github.com/ExtremeFiretop/MerlinAutoUpdate-Router/pull/278) - Keep ZeroTier connection during F/W updates.
-Updated code to keep ZeroTier VPN connection alive during F/W updates. Also, if OpenSSH is being used for remote SSH access the server is kept alive as well.
(Thanks [@Martinski4GitHub](https://github.com/Martinski4GitHub))!

**BUG FIX:** PR: [#280](https://github.com/ExtremeFiretop/MerlinAutoUpdate-Router/pull/280) - Clarify Email Content
-Clarify Email Content as requested by: @maghuro here: https://www.snbforums.com/threads/merlinau-v1-2-6-the-ultimate-firmware-auto-updater-now-available-in-amtm.88577/post-920655
-Also fixed a bug related to the email subject when a node had an update (sent from the primary router)

PR: [#282](https://github.com/ExtremeFiretop/MerlinAutoUpdate-Router/pull/282) - Increased Maximum Postponement Days

-Increased the maximum number of postponement days to 199. This gives users plenty of time to wait and decide when to do the F/W Update, especially for those users who prefer to do it manually. Requested by @Jeffofmany
(Thanks [@Martinski4GitHub](https://github.com/Martinski4GitHub))!

As always, we highly recommend you update ASAP as this includes lots of functional improvements and little bug fixes.

### CODE REVIEW

**Comment by ExtremeFiretop** [comment]
@Martinski4GitHub 

When your ready, approve and merge :)
New forum thread and post is ready as well.

**Comment by ExtremeFiretop** [comment]
Also as an FYI, I want to look into a way to have these 2 steps automated by Github workflow:

1. Update Script version
2. Update Script Branch

We currently use the version.txt to set the version in the release, why not use the same version.txt to populate/update those fields when merging from dev to production.

Food for thought of course.

**Comment by ExtremeFiretop** [comment]
> Also as an FYI, I want to look into a way to have these 2 steps automated by Github workflow:
> 
> 1. Update Script version
> 2. Update Script Branch
> 
> We currently use the version.txt to set the version in the release, why not use the same version.txt to populate/update those fields when merging from dev to production.
> 
> Food for thought of course.

@Martinski4GitHub 

Updated our workflow file here: https://github.com/ExtremeFiretop/MerlinAutoUpdate-Router/commit/7d2327bff993f546c55b1cc19fcfe5a5133385db

To take care of these 2 tasks for us...
If you'd like to see the results of the test run I ran you can find it here: 
https://github.com/ExtremeFiretop/MerlinAutoUpdate-Router/actions

Just look for the latest "DEBUG" Workflow run at the top and click the gear icon to view the log files.

**Comment by Martinski4GitHub** [comment]
> @Martinski4GitHub
> 
> When your ready, approve and merge :) New forum thread and post is ready as well.
> 
> **Edit: Actually** I'm just going to push it out now, cause i gotta head out for the next hour or so, and I don't want to be too off sync with the posting.
>
>
Yep, no need to wait for me. At this point, the code is considered ready for production so "it's swim or sink" time when it comes to issuing the release.😉

**Comment by Martinski4GitHub** [comment]
> Also as an FYI, I want to look into a way to have these 2 steps automated by Github workflow:
> 
>     1. Update Script version
> 
>     2. Update Script Branch
> 
> 
> We currently use the version.txt to set the version in the release, why not use the same version.txt to populate/update those fields when merging from dev to production.
> 
> Food for thought of course.
>
>
Excellent idea! As much as possible, remove the human element (and, therefore, human errors) from the process by automating required steps.

**Comment by Martinski4GitHub** [comment]
> > Also as an FYI, I want to look into a way to have these 2 steps automated by Github workflow:
> > 
> > 1. Update Script version
> > 2. Update Script Branch
> > 
> > We currently use the version.txt to set the version in the release, why not use the same version.txt to populate/update those fields when merging from dev to production.
> > Food for thought of course.
> 
> @Martinski4GitHub
> 
> Updated our workflow file here: [7d2327b](https://github.com/ExtremeFiretop/MerlinAutoUpdate-Router/commit/7d2327bff993f546c55b1cc19fcfe5a5133385db)
> 
> To take care of these 2 tasks for us... If you'd like to see the results of the test run I ran you can find it here: https://github.com/ExtremeFiretop/MerlinAutoUpdate-Router/actions
> 
> Just look for the latest "DEBUG" Workflow run at the top and click the gear icon to view the log files.
>
>
Excellent job, bud!!  Two fewer things to worry about when making a production release.

**Comment by ExtremeFiretop** [comment]
> > > Also as an FYI, I want to look into a way to have these 2 steps automated by Github workflow:
> > > 
> > > 1. Update Script version
> > > 2. Update Script Branch
> > > 
> > > We currently use the version.txt to set the version in the release, why not use the same version.txt to populate/update those fields when merging from dev to production.
> > > Food for thought of course.
> > 
> > 
> > @Martinski4GitHub
> > Updated our workflow file here: [7d2327b](https://github.com/ExtremeFiretop/MerlinAutoUpdate-Router/commit/7d2327bff993f546c55b1cc19fcfe5a5133385db)
> > To take care of these 2 tasks for us... If you'd like to see the results of the test run I ran you can find it here: https://github.com/ExtremeFiretop/MerlinAutoUpdate-Router/actions
> > Just look for the latest "DEBUG" Workflow run at the top and click the gear icon to view the log files.
> 
> Excellent job, bud!! Two fewer things to worry about when making a production release.

I did it manually this time, but I figured the workflow can automate this, so I can forget about it again going forward 🤣

**Comment by Martinski4GitHub** [comment]
> > > > Also as an FYI, I want to look into a way to have these 2 steps automated by Github workflow:
> > > > 
> > > > 1. Update Script version
> > > > 2. Update Script Branch
> > > > 
> > > > We currently use the version.txt to set the version in the release, why not use the same version.txt to populate/update those fields when merging from dev to production.
> > > > Food for thought of course.
> > > 
> > > 
> > > @Martinski4GitHub
> > > Updated our workflow file here: [7d2327b](https://github.com/ExtremeFiretop/MerlinAutoUpdate-Router/commit/7d2327bff993f546c55b1cc19fcfe5a5133385db)
> > > To take care of these 2 tasks for us... If you'd like to see the results of the test run I ran you can find it here: https://github.com/ExtremeFiretop/MerlinAutoUpdate-Router/actions
> > > Just look for the latest "DEBUG" Workflow run at the top and click the gear icon to view the log files.
> > 
> > 
> > Excellent job, bud!! Two fewer things to worry about when making a production release.
> 
> I did it manually this time, but I figured the workflow can automate this, so I can forget about it again going forward 🤣
>
Yep, that's the goal!! 👍

**Pull request merged**
