### PR TITLE
Dev 1.2.4 As Next Stable Release

### PR DESCRIPTION
**Pull request by ExtremeFiretop**
MerlinAU Version 1.2.4 released.

What's Changed/Fixed?:

PR: [#245 ](https://github.com/ExtremeFiretop/MerlinAutoUpdate-Router/pull/245) - Some code improvements. (Thanks [@Martinski4GitHub](https://github.com/Martinski4GitHub))!
Some small general code improvements and cleanup

PR: [#246 ](https://github.com/ExtremeFiretop/MerlinAutoUpdate-Router/pull/246) - Skip Tailscale Daemon Shutdown
This is a new feature which allows MerlinAU to run interactively over an SSH Tailscale connection. 
Previously MerlinAU would shutdown all services including Tailscale, this setting is controllable in the Advanced options.

image

Keep in mind this means that when the flash starts, Tailscale and Diversion (if installed) will still be running.

PR: [#248 ](https://github.com/ExtremeFiretop/MerlinAutoUpdate-Router/pull/248) - Code improvements WRT Entware services. (Thanks [@Martinski4GitHub](https://github.com/Martinski4GitHub))!
This PR includes some code improvements when stopping/starting Entware services.

Special shout-out to @jksmurf to all the help testing the Tailscale functionality.
we highly recommend you update ASAP as this includes lots of functional improvements and little bug fixes.

### CODE REVIEW

**Comment by ExtremeFiretop** [comment]
@Martinski4GitHub 

All went well with this release of MerlinAU and the full release of v3006.102.1

image
image
image
image

**Comment by Martinski4GitHub** [comment]
> @Martinski4GitHub
> 
> All went well with this release of MerlinAU and the full release of v3006.102.1
> 
Cool!!! It's nice to see when everything falls into place. And the latest MerlinAU **1.2.4** release came out just in time!

BTW, I'll send you a PM about a new fixed version of **YazDHCP** to test it on the 3006.102 F/W. I think it should work now, but I'd like have your validation & feedback, as usual.

**Comment by ExtremeFiretop** [comment]
> > @Martinski4GitHub
> > All went well with this release of MerlinAU and the full release of v3006.102.1
> 
> Cool!!! It's nice to see when everything falls into place. And the latest MerlinAU **1.2.4** release came out just in time!
> 
> BTW, I'll send you a PM about a new fixed version of **YazDHCP** to test it on the 3006.102 F/W. I think it should work now, but I'd like have your validation & feedback, as usual.

I had a feeling we were cutting it close.
I knew you were tired this morning and didn't want to drag you through all the hoops so I just pushed it out. 

Happy I listened to my gut feeling that we were cutting something close, because like you said, the timing was perfect. Haha!

Yes please, send me a PM I'm all open for testing for you bud!

**Comment by Martinski4GitHub** [comment]
> > > @Martinski4GitHub
> > > All went well with this release of MerlinAU and the full release of v3006.102.1
> > 
> > 
> > Cool!!! It's nice to see when everything falls into place. And the latest MerlinAU **1.2.4** release came out just in time!
> > BTW, I'll send you a PM about a new fixed version of **YazDHCP** to test it on the 3006.102 F/W. I think it should work now, but I'd like have your validation & feedback, as usual.
> 
> I had a feeling we were cutting it close. I knew you were tired this morning and didn't want to drag you through all the hoops so I just pushed it out.
> 
> Happy I listened to my gut feeling that we were cutting something close, because like you said, the timing was perfect. Haha!
> 
> Yes please, send me a PM I'm all open for testing for you bud!
>
You definitely made the right call this morning to issue the new production release. Excellent job, bud.

**Pull request merged**
