### PR TITLE
Updated MerlinAU.sh

### PR DESCRIPTION
**Pull request by Martinski4GitHub**
Added a new selection in the "Advanced Options" menu to allow users to set an optional secondary email address to receive notifications. This menu item will be displayed only *IF* the "Email Notifications" setting has been **ENABLED**; otherwise, it's hidden. Note that the user can send a TEST email notification from this menu item as well.

### CODE REVIEW

**Comment by ExtremeFiretop** [comment]
>  This menu item will be displayed only _IF_ the "Email Notifications" setting has been **ENABLED**; otherwise, it's hidden. Note that the user can send a TEST email notification from this menu item as well.

I really like this implementation. Let me test and report back shortly!

**Review by ExtremeFiretop — APPROVED** [review]

**Comment by ExtremeFiretop** [comment]
Tested perfectly. Works as advertised.

**Comment by Martinski4GitHub** [comment]
> Tested perfectly. Works as advertised.
>
Glad it all has worked out smoothly so far. Thanks for providing a 2nd pair of eyes to double-check.
As usual, the true test will be when the new version is released and it's running "out in the wild." As proven by the GMX email problem, there could be variations of email servers that might be very particular about how they parse & handle emails.

Anyway, I need to go to sleep now. I wanted to get all the code additions/changes out today to get tested & validated before the next RMerlin F/W release comes out (the 3004.388.6_1 Beta version is already out there).

**Comment by ExtremeFiretop** [comment]
> 
> Glad it all has worked out smoothly so far. Thanks for providing a 2nd pair of eyes to double-check. As usual, the true test will be when the new version is released and it's running "out in the wild." As proven by the GMX email problem, there could be variations of email servers that might be very particular about how they parse & handle emails.

You did good, but when do you not?
I may be the lead of the project on paper, but your a co-owner and really the brains behind the project.

The project lead is really considering me your level 1/2 support, I filter out the useless requests from the good ones and keep a good level of separation between the main dev and the users ;)

> 
> Anyway, I need to go to sleep now. I wanted to get all the code additions/changes out today to get tested & validated before the next RMerlin F/W release comes out (the 3004.388.6_1 Beta version is already out there).

Have a goodnight buddy! Let me take ownership of the backupmon thing. I'll have it ready for you by the time you wake up hopefully :) I also want to get the next release out in the wild before the next F/W drop

**Pull request merged**
